-- Repoints the advertisements table at realistic titles and rate-card pricing.
--
-- NON-DESTRUCTIVE, unlike seed_african_ad_placements.sql which deletes every
-- row first. This only touches the 58 seeded placements, matched by their
-- previous title, so an owner-submitted placement is left alone.
--
-- WHY: every seeded rate was 3-23x the real market. Port Harcourt was priced
-- at ~N11.7m a month against a published N500k, Ibadan at ~N8.1m against a
-- published N500k. Day rates below are derived from Nigerian OOH monthly rate
-- cards (Aug 2026) at N1,500/USD: usd_per_day = naira_per_month / 30 / 1500.
--
-- Safe to re-run: after the first pass the old titles no longer match, so
-- every statement becomes a no-op.

UPDATE advertisements SET title = '3-Face Gantry Billboard, Third Mainland Bridge, Lagos', price_per_day = 56, pricing = 56, description = 'Large-format outdoor billboard with premium visibility — 18m x 9m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Third Mainland Bridge Gantry';
UPDATE advertisements SET title = '3-Face Unipole Billboard, Lekki-Epe Expressway, Lagos', price_per_day = 102, pricing = 102, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Lekki-Epe Expressway Unipole';
UPDATE advertisements SET title = '2-Sided LED Tower, Akin Adesola, Victoria Island, Lagos', price_per_day = 289, pricing = 289, description = 'High-brightness digital LED screen with rotating 10-second slots — 10m x 6m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Victoria Island LED Tower';
UPDATE advertisements SET title = 'Double-Sided Freestanding Screens, Ikeja City Mall, Lagos', price_per_day = 33, pricing = 33, description = 'Indoor retail advertising reaching shoppers at point of purchase — 4m x 3m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Ikeja City Mall Atrium Screen';
UPDATE advertisements SET title = 'Arrivals Wall Lightbox, Murtala Muhammed Airport, Lagos', price_per_day = 78, pricing = 78, description = 'Premium airport advertising reaching business and leisure travellers — 8m x 3m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Murtala Muhammed Airport Arrivals Wall';
UPDATE advertisements SET title = 'Full Vehicle Wrap, Danfo Fleet of 10, Lagos', price_per_day = 27, pricing = 27, description = 'Moving vehicle advertising reaching commuters across the city — Full vehicle, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Danfo Bus Full Wrap (Fleet of 10)';
UPDATE advertisements SET title = '2-Face Digital Board, Oshodi Interchange, Lagos', price_per_day = 80, pricing = 80, description = 'High-brightness digital LED screen with rotating 10-second slots — 8m x 4m, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Oshodi Interchange Digital Board';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Wuse Market Entrance, Abuja', price_per_day = 27, pricing = 27, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Abuja, Nigeria.' WHERE title = 'Wuse Market Entrance Billboard';
UPDATE advertisements SET title = 'Baggage Hall Lightbox, Nnamdi Azikiwe Airport, Abuja', price_per_day = 49, pricing = 49, description = 'Premium airport advertising reaching business and leisure travellers — 6m x 3m, medium traffic. Located at Abuja, Nigeria.' WHERE title = 'Nnamdi Azikiwe Airport Baggage Hall';
UPDATE advertisements SET title = 'Lamp Post Network (20 units), Maitama District, Abuja', price_per_day = 20, pricing = 20, description = 'Eye-level street advertising in high-footfall areas — 1.2m x 1.8m each, medium traffic. Located at Abuja, Nigeria.' WHERE title = 'Maitama District Lamp Posts (20 units)';
UPDATE advertisements SET title = '2-Sided Unipole Billboard, Aba Road, Port Harcourt', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Port Harcourt, Nigeria.' WHERE title = 'Port Harcourt Aba Road Unipole';
UPDATE advertisements SET title = 'Double-Face Eyecatcher Billboard, Ring Road, Ibadan', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, medium traffic. Located at Ibadan, Nigeria.' WHERE title = 'Ibadan Ring Road Billboard';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Kofar Mata Roundabout, Kano', price_per_day = 13, pricing = 13, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Kano, Nigeria.' WHERE title = 'Kano Kofar Mata Roundabout Board';
UPDATE advertisements SET title = 'Drive-Time Radio Slot (60s), Wazobia FM, Lagos', price_per_day = 33, pricing = 33, description = 'Prime-time radio advertising slot with mass local reach — 60 seconds, high traffic. Located at Lagos, Nigeria.' WHERE title = 'Wazobia FM Drive-Time Slot (60s)';
UPDATE advertisements SET title = '2-Face Gantry Billboard, Kwame Nkrumah Circle, Accra', price_per_day = 40, pricing = 40, description = 'Large-format outdoor billboard with premium visibility — 14m x 7m, high traffic. Located at Accra, Ghana.' WHERE title = 'Accra Kwame Nkrumah Circle Gantry';
UPDATE advertisements SET title = 'Food Court Screen Network, Accra Mall, Accra', price_per_day = 22, pricing = 22, description = 'Indoor retail advertising reaching shoppers at point of purchase — Network of 8, high traffic. Located at Accra, Ghana.' WHERE title = 'Accra Mall Food Court Screens';
UPDATE advertisements SET title = 'Departure Lounge Lightboxes, Kotoka Airport, Accra', price_per_day = 52, pricing = 52, description = 'Premium airport advertising reaching business and leisure travellers — 5m x 2.5m, medium traffic. Located at Accra, Ghana.' WHERE title = 'Kotoka Airport Departure Lounge';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Tema Motorway, Tema', price_per_day = 18, pricing = 18, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Tema, Ghana.' WHERE title = 'Tema Motorway Unipole';
UPDATE advertisements SET title = 'Wall Panel Billboard, Kejetia Market, Kumasi', price_per_day = 12, pricing = 12, description = 'Large-format outdoor billboard with premium visibility — 15m x 4m, high traffic. Located at Kumasi, Ghana.' WHERE title = 'Kumasi Kejetia Market Wall';
UPDATE advertisements SET title = 'Rear Window Network (50 vehicles), Trotro Fleet, Accra', price_per_day = 16, pricing = 16, description = 'Moving vehicle advertising reaching commuters across the city — 1m x 0.6m each, high traffic. Located at Accra, Ghana.' WHERE title = 'Trotro Rear Window Network (50 vehicles)';
UPDATE advertisements SET title = '2-Sided Digital Gantry, Mombasa Road, Nairobi', price_per_day = 120, pricing = 120, description = 'High-brightness digital LED screen with rotating 10-second slots — 12m x 5m, high traffic. Located at Nairobi, Kenya.' WHERE title = 'Mombasa Road Digital Gantry';
UPDATE advertisements SET title = '2-Face Static Billboard, Kenyatta Avenue CBD, Nairobi', price_per_day = 45, pricing = 45, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Nairobi, Kenya.' WHERE title = 'Nairobi CBD Kenyatta Avenue Board';
UPDATE advertisements SET title = 'Escalator Wrap Series, Two Rivers Mall, Nairobi', price_per_day = 24, pricing = 24, description = 'Indoor retail advertising reaching shoppers at point of purchase — 6 escalators, medium traffic. Located at Nairobi, Kenya.' WHERE title = 'Two Rivers Mall Escalator Wraps';
UPDATE advertisements SET title = 'International Arrivals Corridor, JKIA, Nairobi', price_per_day = 95, pricing = 95, description = 'Premium airport advertising reaching business and leisure travellers — 10 lightboxes, high traffic. Located at Nairobi, Kenya.' WHERE title = 'JKIA International Arrivals Corridor';
UPDATE advertisements SET title = 'Full Vehicle Branding, Matatu Route 111, Nairobi', price_per_day = 14, pricing = 14, description = 'Moving vehicle advertising reaching commuters across the city — Full vehicle, high traffic. Located at Nairobi, Kenya.' WHERE title = 'Matatu Full Branding (Route 111)';
UPDATE advertisements SET title = '2-Face Static Billboard, Moi Avenue, Mombasa', price_per_day = 18, pricing = 18, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Mombasa, Kenya.' WHERE title = 'Mombasa Moi Avenue Billboard';
UPDATE advertisements SET title = 'Digital Spectacular, N1 Highway, Johannesburg', price_per_day = 320, pricing = 320, description = 'High-brightness digital LED screen with rotating 10-second slots — 15m x 7m, high traffic. Located at Johannesburg, South Africa.' WHERE title = 'N1 Highway Digital Spectacular';
UPDATE advertisements SET title = 'Rooftop Sign, Sandton City, Johannesburg', price_per_day = 180, pricing = 180, description = 'Large-format outdoor billboard with premium visibility — 20m x 8m, high traffic. Located at Johannesburg, South Africa.' WHERE title = 'Sandton City Rooftop Sign';
UPDATE advertisements SET title = 'Platform Screen Network, Gautrain Stations, Johannesburg', price_per_day = 70, pricing = 70, description = 'Moving vehicle advertising reaching commuters across the city — Network of 12, high traffic. Located at Johannesburg, South Africa.' WHERE title = 'Gautrain Station Platform Screens';
UPDATE advertisements SET title = 'Entrance Tower Screens, V&A Waterfront, Cape Town', price_per_day = 110, pricing = 110, description = 'Indoor retail advertising reaching shoppers at point of purchase — 2 towers, 6m x 3m, high traffic. Located at Cape Town, South Africa.' WHERE title = 'V&A Waterfront Entrance Towers';
UPDATE advertisements SET title = 'Baggage Carousel Panels, Cape Town International', price_per_day = 85, pricing = 85, description = 'Premium airport advertising reaching business and leisure travellers — 4 carousels, high traffic. Located at Cape Town, South Africa.' WHERE title = 'Cape Town Intl Baggage Carousels';
UPDATE advertisements SET title = '2-Face Beachfront Billboard, Golden Mile, Durban', price_per_day = 48, pricing = 48, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Durban, South Africa.' WHERE title = 'Durban Golden Mile Beachfront Board';
UPDATE advertisements SET title = 'LED Perimeter Boards, Moses Mabhida Stadium, Durban', price_per_day = 140, pricing = 140, description = 'Live-event advertising with broadcast camera exposure — Pitch-side LED ring, high traffic. Located at Durban, South Africa.' WHERE title = 'Moses Mabhida Stadium LED Perimeter';
UPDATE advertisements SET title = 'Street Pole Network (30 units), Church Square, Pretoria', price_per_day = 26, pricing = 26, description = 'Eye-level street advertising in high-footfall areas — 1m x 1.5m each, medium traffic. Located at Pretoria, South Africa.' WHERE title = 'Pretoria Church Square Street Poles (30)';
UPDATE advertisements SET title = 'Mega Board, 6th October Bridge, Cairo', price_per_day = 95, pricing = 95, description = 'Large-format outdoor billboard with premium visibility — 20m x 8m, high traffic. Located at Cairo, Egypt.' WHERE title = '6th October Bridge Mega Board';
UPDATE advertisements SET title = '2-Sided Digital Unipole, Ring Road, Cairo', price_per_day = 110, pricing = 110, description = 'High-brightness digital LED screen with rotating 10-second slots — 14m x 7m, high traffic. Located at Cairo, Egypt.' WHERE title = 'Cairo Ring Road Digital Unipole';
UPDATE advertisements SET title = 'Terminal 3 Lightbox Series, Cairo International', price_per_day = 60, pricing = 60, description = 'Premium airport advertising reaching business and leisure travellers — 12 lightboxes, high traffic. Located at Cairo, Egypt.' WHERE title = 'Cairo Intl Terminal 3 Lightboxes';
UPDATE advertisements SET title = 'Seafront Billboard, Corniche, Alexandria', price_per_day = 30, pricing = 30, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Alexandria, Egypt.' WHERE title = 'Alexandria Corniche Seafront Board';
UPDATE advertisements SET title = '2-Face Digital Screen, Bole Road, Addis Ababa', price_per_day = 40, pricing = 40, description = 'High-brightness digital LED screen with rotating 10-second slots — 8m x 4m, high traffic. Located at Addis Ababa, Ethiopia.' WHERE title = 'Bole Road Digital Screen';
UPDATE advertisements SET title = 'Jet Bridge Panels, Bole Airport, Addis Ababa', price_per_day = 55, pricing = 55, description = 'Premium airport advertising reaching business and leisure travellers — 6 bridge wraps, high traffic. Located at Addis Ababa, Ethiopia.' WHERE title = 'Addis Ababa Bole Airport Jet Bridges';
UPDATE advertisements SET title = '2-Face Static Billboard, Samora Avenue, Dar es Salaam', price_per_day = 20, pricing = 20, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Dar es Salaam, Tanzania.' WHERE title = 'Dar es Salaam Samora Avenue Board';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Northern Bypass, Kampala', price_per_day = 16, pricing = 16, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, medium traffic. Located at Kampala, Uganda.' WHERE title = 'Kampala Northern Bypass Unipole';
UPDATE advertisements SET title = 'Approach Billboard, Kigali Convention Centre, Kigali', price_per_day = 22, pricing = 22, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Kigali, Rwanda.' WHERE title = 'Kigali Convention Centre Approach';
UPDATE advertisements SET title = 'Bus Shelter Network (25 shelters), Kigali', price_per_day = 13, pricing = 13, description = 'Eye-level street advertising in high-footfall areas — 25 backlit panels, medium traffic. Located at Kigali, Rwanda.' WHERE title = 'Kigali Bus Shelter Network (25 shelters)';
UPDATE advertisements SET title = '2-Face Billboard, Boulevard du 30 Juin, Kinshasa', price_per_day = 24, pricing = 24, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Kinshasa, DR Congo.' WHERE title = 'Kinshasa Boulevard du 30 Juin Board';
UPDATE advertisements SET title = '2-Face Gantry Billboard, Autoroute Péage, Dakar', price_per_day = 28, pricing = 28, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Dakar, Senegal.' WHERE title = 'Dakar Autoroute Péage Gantry';
UPDATE advertisements SET title = '2-Face Billboard, Akwa Boulevard, Douala', price_per_day = 19, pricing = 19, description = 'High-brightness digital LED screen with rotating 10-second slots — 7m x 4m, high traffic. Located at Abidjan, Côte d''Ivoire.' WHERE title = 'Abidjan Plateau Digital Corner';
UPDATE advertisements SET title = 'Digital Wall, Corniche, Casablanca', price_per_day = 85, pricing = 85, description = 'Premium airport advertising reaching business and leisure travellers — 8 lightboxes, medium traffic. Located at Abidjan, Côte d''Ivoire.' WHERE title = 'Abidjan Félix-Houphouët-Boigny Airport';
UPDATE advertisements SET title = 'Arrivals Hall Panels, Menara Airport, Marrakech', price_per_day = 45, pricing = 45, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Douala, Cameroon.' WHERE title = 'Douala Akwa Boulevard Board';
UPDATE advertisements SET title = '2-Face Billboard, Habib Bourguiba Avenue, Tunis', price_per_day = 26, pricing = 26, description = 'High-brightness digital LED screen with rotating 10-second slots — 11m x 6m, high traffic. Located at Casablanca, Morocco.' WHERE title = 'Casablanca Corniche Digital Wall';
UPDATE advertisements SET title = 'Street Pole Network (40 units), Didouche Mourad, Algiers', price_per_day = 22, pricing = 22, description = 'Premium airport advertising reaching business and leisure travellers — 6 lightboxes, high traffic. Located at Marrakech, Morocco.' WHERE title = 'Marrakech Menara Airport Arrivals';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Great East Road, Lusaka', price_per_day = 14, pricing = 14, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Tunis, Tunisia.' WHERE title = 'Tunis Habib Bourguiba Avenue Board';
UPDATE advertisements SET title = '2-Face Billboard, Samora Machel Avenue, Harare', price_per_day = 12, pricing = 12, description = 'Eye-level street advertising in high-footfall areas — 1m x 1.5m each, medium traffic. Located at Algiers, Algeria.' WHERE title = 'Algiers Didouche Mourad Street Poles (40)';
UPDATE advertisements SET title = 'Mall Screen Network, Game City, Gaborone', price_per_day = 15, pricing = 15, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, medium traffic. Located at Lusaka, Zambia.' WHERE title = 'Lusaka Great East Road Unipole';
UPDATE advertisements SET title = '2-Face Billboard, Independence Avenue, Windhoek', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, medium traffic. Located at Harare, Zimbabwe.' WHERE title = 'Harare Samora Machel Avenue Board';
UPDATE advertisements SET title = '2-Face Billboard, Julius Nyerere Avenue, Maputo', price_per_day = 13, pricing = 13, description = 'Indoor retail advertising reaching shoppers at point of purchase — Network of 6, medium traffic. Located at Gaborone, Botswana.' WHERE title = 'Gaborone Game City Mall Screens';
UPDATE advertisements SET title = '2-Sided Digital Corner Screen, Plateau, Abidjan', price_per_day = 62, pricing = 62, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Windhoek, Namibia.' WHERE title = 'Windhoek Independence Avenue Board';
UPDATE advertisements SET title = 'Terminal Lightbox Series, Félix-Houphouët-Boigny Airport, Abidjan', price_per_day = 44, pricing = 44, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, medium traffic. Located at Maputo, Mozambique.' WHERE title = 'Maputo Julius Nyerere Avenue Board';

-- Sanity check: no placement should sit outside the published market band.
SELECT title, price_per_day, round(price_per_day * 30 * 1500 / 1000000.0, 2) AS naira_millions_per_month
FROM advertisements ORDER BY price_per_day DESC LIMIT 5;
