-- Repairs and enriches the media_services marketplace rows.
-- Generated by scripts/generate-media-sql.mjs — do not edit by hand.
-- Non-destructive and safe to re-run:
--   1. fixes titles corrupted to 'â€”' by an earlier seeding
--   2. sets a realistic, type-appropriate image on each known service
--   3. inserts newer services that are not in the table yet

UPDATE media_services SET title = replace(title, 'â€”', '—') WHERE title LIKE '%â€”%';
UPDATE media_services SET description = replace(description, 'â€”', '—') WHERE description LIKE '%â€”%';

UPDATE media_services SET image_url = 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Lens & Light Photography%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Kalahari Films%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Sable Studio%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Ubuntu Digital%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Baobab Motion%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/164829/pexels-photo-164829.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/164829/pexels-photo-164829.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Sahara Sound%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/336232/pexels-photo-336232.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/336232/pexels-photo-336232.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Nairobi Drone Collective%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Accra Creative Lab%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/257904/pexels-photo-257904.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/257904/pexels-photo-257904.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Jollof Post%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/1054713/pexels-photo-1054713.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/1054713/pexels-photo-1054713.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Kigali Sessions%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Zebra Ink%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Lagos Wedding Stories%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Savanna UX%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'AfroBeat Visuals%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/261510/pexels-photo-261510.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/261510/pexels-photo-261510.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Cape Copy Co.%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/4062561/pexels-photo-4062561.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/4062561/pexels-photo-4062561.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Kampala Motion%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/257897/pexels-photo-257897.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/257897/pexels-photo-257897.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Dakar Retouch%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Joburg Influence%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/744318/pexels-photo-744318.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/744318/pexels-photo-744318.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Timbuktu Voices%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Cape Estates Media%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Naija Live%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Serengeti Signs%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Atlas Media%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/279906/pexels-photo-279906.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/279906/pexels-photo-279906.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Accra Food Frames%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Meridian Media Buying%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Kwanza Ads%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Indigo & Ochre%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/265685/pexels-photo-265685.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/265685/pexels-photo-265685.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Harmattan Commerce%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Content Kitchen%';
UPDATE media_services SET image_url = 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=640', thumbnail_url = 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title LIKE 'Summit Frames%';

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Lens & Light Photography — Product Shoots', 'Studio product photography for e-commerce and catalogues. Includes 20 retouched images, white background and lifestyle setups.', 'Photography', 350, 'per shoot', '5 days', 140, 62, 4.8, 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Lens & Light Photography%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Kalahari Films — Brand Video Production', 'Full-service brand films and TV commercials: scripting, shooting, colour grading and sound design. 30-90 second final cuts.', 'Videography', 2500, 'per project', '21 days', 85, 41, 4.9, 'https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Kalahari Films%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Sable Studio — Logo & Brand Identity', 'Complete identity package: logo suite, colour system, typography, brand guidelines PDF and social media kit.', 'Branding', 800, 'per project', '14 days', 210, 98, 4.7, 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Sable Studio%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Ubuntu Digital — Social Media Management', 'Monthly content calendar, 20 designed posts, community management and a performance report across Instagram, X and TikTok.', 'Social Media Management', 450, 'per month', 'ongoing', 96, 54, 4.6, 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Ubuntu Digital%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Baobab Motion — 2D Explainer Animation', 'Animated explainer videos with script, storyboard, voice-over and custom illustration. Up to 90 seconds.', 'Animation', 1200, 'per video', '18 days', 58, 33, 4.8, 'https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Baobab Motion%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Sahara Sound — Radio Jingle & Audio Ads', 'Catchy radio jingles and audio spots in English, French, Swahili or Pidgin. Includes composition, voice talent and mastering.', 'Audio Production', 300, 'per spot', '7 days', 175, 80, 4.5, 'https://images.pexels.com/photos/164829/pexels-photo-164829.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/164829/pexels-photo-164829.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Sahara Sound%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Nairobi Drone Collective — Aerial Coverage', 'Licensed drone pilots for real estate, events and documentaries. 4K footage plus edited highlight reel.', 'Drone Photography', 550, 'per day', '5 days', 64, 29, 4.7, 'https://images.pexels.com/photos/336232/pexels-photo-336232.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/336232/pexels-photo-336232.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Nairobi Drone Collective%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Accra Creative Lab — Web & Landing Page Design', 'Conversion-focused landing pages and small business sites. Design in Figma, responsive build, basic SEO setup.', 'Web Design', 950, 'per site', '14 days', 120, 66, 4.6, 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Accra Creative Lab%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Jollof Post — Video Editing & Colour Grading', 'Post-production for creators and agencies: multi-cam editing, motion titles, colour grading and delivery in all aspect ratios.', 'Video Editing', 200, 'per minute of output', '4 days', 230, 112, 4.8, 'https://images.pexels.com/photos/257904/pexels-photo-257904.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/257904/pexels-photo-257904.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Jollof Post%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Kigali Sessions — Podcast Production', 'End-to-end podcast production: recording, editing, show notes, cover art and distribution to all platforms.', 'Podcast Production', 180, 'per episode', '3 days', 44, 21, 4.9, 'https://images.pexels.com/photos/1054713/pexels-photo-1054713.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/1054713/pexels-photo-1054713.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Kigali Sessions%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Zebra Ink — Print & Packaging Design', 'Flyers, billboards, product packaging and print-ready artwork with supplier liaison for CMYK production.', 'Graphic Design', 260, 'per design', '6 days', 190, 87, 4.5, 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Zebra Ink%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Lagos Wedding Stories — Event Coverage', 'Weddings, launches and conferences covered by a two-person crew. 300+ edited photos and a same-week highlight video.', 'Event Photography', 700, 'per event', '10 days', 155, 74, 4.7, 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Lagos Wedding Stories%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Savanna UX — Mobile App UI/UX Design', 'User research, wireframes and polished UI kits for iOS and Android apps, delivered as developer-ready Figma files.', 'UI/UX Design', 1500, 'per project', '21 days', 39, 18, 4.8, 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Savanna UX%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'AfroBeat Visuals — Music Video Production', 'Concept-to-delivery music videos with location scouting, styling, cinematography and VFX-ready editing.', 'Videography', 3000, 'per video', '30 days', 47, 25, 4.6, 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'AfroBeat Visuals%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Cape Copy Co. — Copywriting & Content', 'Website copy, ad scripts, blog articles and product descriptions written for African audiences in EN/FR/PT.', 'Content Creation', 120, 'per 1000 words', '3 days', 260, 130, 4.7, 'https://images.pexels.com/photos/261510/pexels-photo-261510.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/261510/pexels-photo-261510.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Cape Copy Co.%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Kampala Motion — Logo Animation & Stingers', 'Animated logos, lower thirds and broadcast stingers for TV stations, YouTubers and event screens.', 'Motion Graphics', 240, 'per animation', '5 days', 91, 45, 4.6, 'https://images.pexels.com/photos/4062561/pexels-photo-4062561.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/4062561/pexels-photo-4062561.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Kampala Motion%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Dakar Retouch — Photo Editing & Restoration', 'High-end retouching, background removal, colour correction and old photo restoration with 48-hour rush option.', 'Photo Editing', 15, 'per image', '2 days', 340, 150, 4.5, 'https://images.pexels.com/photos/257897/pexels-photo-257897.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/257897/pexels-photo-257897.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Dakar Retouch%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Joburg Influence — Influencer Campaign Management', 'Campaign strategy, creator sourcing, content approval and reporting across African influencer networks.', 'Influencer Marketing', 1000, 'per campaign', '30 days', 52, 27, 4.4, 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Joburg Influence%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Timbuktu Voices — Voice-Over in 6 Languages', 'Professional voice-over for ads, IVR and e-learning in English, French, Swahili, Hausa, Yoruba and Pidgin. Broadcast-ready audio.', 'Voice-Over', 90, 'per finished minute', '2 days', 205, 93, 4.7, 'https://images.pexels.com/photos/744318/pexels-photo-744318.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/744318/pexels-photo-744318.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Timbuktu Voices%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Cape Estates Media — Real Estate Photo & Virtual Tours', 'HDR interiors, twilight exteriors, floor plans and 360° virtual tours that help listings sell faster.', 'Real Estate Media', 250, 'per listing', '3 days', 130, 61, 4.8, 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Cape Estates Media%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Naija Live — Livestream & Event Streaming', 'Multi-camera livestreams for conferences, weddings and product launches to YouTube, Facebook and private feeds.', 'Live Streaming', 600, 'per event', 'same day', 75, 38, 4.6, 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Naija Live%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Serengeti Signs — Billboard & OOH Creative', 'High-impact large-format artwork for billboards, transit wraps and mall screens, sized to any placement spec.', 'Graphic Design', 320, 'per design', '5 days', 88, 41, 4.5, 'https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Serengeti Signs%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Atlas Media — TV Commercial Production', 'Broadcast-standard TV commercials: casting, studio or location shoots, licensed music and clearance-ready masters.', 'Videography', 4500, 'per commercial', '45 days', 29, 15, 4.9, 'https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/3062541/pexels-photo-3062541.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Atlas Media%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Accra Food Frames — Menu & Food Photography', 'Appetising menu, delivery-app and social photography for restaurants — styled, shot and delivered ready to upload.', 'Photography', 220, 'per menu shoot', '4 days', 112, 57, 4.7, 'https://images.pexels.com/photos/279906/pexels-photo-279906.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/279906/pexels-photo-279906.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Accra Food Frames%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Meridian Media Buying — Radio, TV & Outdoor', 'Media planning and buying across radio, TV and billboards. Audience research, rate negotiation, spot scheduling and a post-campaign reach report.', 'Advertising', 650, 'per month retainer', 'ongoing', 68, 31, 4.5, 'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Meridian Media Buying%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Kwanza Ads — Paid Social & Search', 'Meta, TikTok and Google campaigns built and managed end to end: creative testing, audience targeting, budget pacing and weekly reporting.', 'Advertising', 380, 'per month retainer', 'ongoing', 143, 71, 4.6, 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Kwanza Ads%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Indigo & Ochre — Brand Strategy Workshop', 'A facilitated two-day session that settles positioning, tone of voice and messaging before any design starts. Ends with a written brand platform.', 'Branding', 600, 'per workshop', '10 days', 47, 22, 4.8, 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Indigo & Ochre%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Harmattan Commerce — Online Store Build', 'Shopify or WooCommerce storefronts with payment gateways set up for African cards and mobile money, plus product upload and staff training.', 'Web Design', 1400, 'per store', '25 days', 73, 36, 4.7, 'https://images.pexels.com/photos/265685/pexels-photo-265685.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/265685/pexels-photo-265685.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Harmattan Commerce%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Content Kitchen — Monthly Shoot & Scheduling', 'One shoot day a month producing 30 photos and 8 short videos, captioned, scheduled and posted across your channels.', 'Social Media Management', 320, 'per month', 'ongoing', 118, 63, 4.6, 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Content Kitchen%');

INSERT INTO media_services (title, description, service_type, pricing, pricing_model, delivery_time, clients_served, review_count, rating, image_url, thumbnail_url, status)
SELECT 'Summit Frames — Conference & Awards Coverage', 'Corporate event coverage with same-day social edits and a full gallery within 72 hours. Two photographers and on-site backup included.', 'Event Photography', 480, 'per event day', '3 days', 96, 44, 4.7, 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=640', 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=640', 'open'
WHERE NOT EXISTS (SELECT 1 FROM media_services WHERE title LIKE 'Summit Frames%');
