-- Repoints the advertisements table at realistic titles and rate-card pricing.
--
-- NON-DESTRUCTIVE, unlike seed_african_ad_placements.sql which deletes every
-- row first. This only touches the 58 seeded placements, matched by their
-- previous title, so an owner-submitted placement is left alone.
--
-- WHY: every seeded rate was 3-23x the real market. Port Harcourt was priced
-- at ~N11.7m a month against a published N500k, Ibadan at ~N8.1m against a
-- published N500k. Day rates below are derived from Nigerian OOH monthly rate
-- cards (Aug 2026) at N1,500/USD: usd_per_day = naira_per_month / 30 / 1500.
--
-- Images are set too: the seeded pools held 3 billboard photos for 26
-- billboard placements, so the same picture appeared nine times down the
-- page. Each placement now carries its own, and every id was loaded before
-- being written here.
--
-- Safe to re-run: after the first pass the old titles no longer match, so
-- every statement becomes a no-op.

UPDATE advertisements SET title = '3-Face Gantry Billboard, Third Mainland Bridge, Lagos', price_per_day = 56, pricing = 56, description = 'Large-format outdoor billboard with premium visibility — 18m x 9m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/33644177/pexels-photo-33644177.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '3-Face Gantry Billboard, Third Mainland Bridge, Lagos';
UPDATE advertisements SET title = '3-Face Unipole Billboard, Lekki-Epe Expressway, Lagos', price_per_day = 102, pricing = 102, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/29812611/pexels-photo-29812611.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '3-Face Unipole Billboard, Lekki-Epe Expressway, Lagos';
UPDATE advertisements SET title = '2-Sided LED Tower, Akin Adesola, Victoria Island, Lagos', price_per_day = 289, pricing = 289, description = 'High-brightness digital LED screen with rotating 10-second slots — 10m x 6m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/3927753/pexels-photo-3927753.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Sided LED Tower, Akin Adesola, Victoria Island, Lagos';
UPDATE advertisements SET title = 'Double-Sided Freestanding Screens, Ikeja City Mall, Lagos', price_per_day = 33, pricing = 33, description = 'Indoor retail advertising reaching shoppers at point of purchase — 4m x 3m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/13100935/pexels-photo-13100935.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Double-Sided Freestanding Screens, Ikeja City Mall, Lagos';
UPDATE advertisements SET title = 'Arrivals Wall Lightbox, Murtala Muhammed Airport, Lagos', price_per_day = 78, pricing = 78, description = 'Premium airport advertising reaching business and leisure travellers — 8m x 3m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/30220728/pexels-photo-30220728.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Arrivals Wall Lightbox, Murtala Muhammed Airport, Lagos';
UPDATE advertisements SET title = 'Full Vehicle Wrap, Danfo Fleet of 10, Lagos', price_per_day = 27, pricing = 27, description = 'Moving vehicle advertising reaching commuters across the city — Full vehicle, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/12641815/pexels-photo-12641815.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Full Vehicle Wrap, Danfo Fleet of 10, Lagos';
UPDATE advertisements SET title = '2-Face Digital Board, Oshodi Interchange, Lagos', price_per_day = 80, pricing = 80, description = 'High-brightness digital LED screen with rotating 10-second slots — 8m x 4m, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/18187188/pexels-photo-18187188.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Digital Board, Oshodi Interchange, Lagos';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Wuse Market Entrance, Abuja', price_per_day = 27, pricing = 27, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Abuja, Nigeria.', image_url = 'https://images.pexels.com/photos/8181296/pexels-photo-8181296.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Unipole Billboard, Wuse Market Entrance, Abuja';
UPDATE advertisements SET title = 'Baggage Hall Lightbox, Nnamdi Azikiwe Airport, Abuja', price_per_day = 49, pricing = 49, description = 'Premium airport advertising reaching business and leisure travellers — 6m x 3m, medium traffic. Located at Abuja, Nigeria.', image_url = 'https://images.pexels.com/photos/392265/pexels-photo-392265.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Baggage Hall Lightbox, Nnamdi Azikiwe Airport, Abuja';
UPDATE advertisements SET title = 'Lamp Post Network (20 units), Maitama District, Abuja', price_per_day = 20, pricing = 20, description = 'Eye-level street advertising in high-footfall areas — 1.2m x 1.8m each, medium traffic. Located at Abuja, Nigeria.', image_url = 'https://images.pexels.com/photos/1661496/pexels-photo-1661496.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Lamp Post Network (20 units), Maitama District, Abuja';
UPDATE advertisements SET title = '2-Sided Unipole Billboard, Aba Road, Port Harcourt', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Port Harcourt, Nigeria.', image_url = 'https://images.pexels.com/photos/4913828/pexels-photo-4913828.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Sided Unipole Billboard, Aba Road, Port Harcourt';
UPDATE advertisements SET title = 'Double-Face Eyecatcher Billboard, Ring Road, Ibadan', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, medium traffic. Located at Ibadan, Nigeria.', image_url = 'https://images.pexels.com/photos/38162696/pexels-photo-38162696.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Double-Face Eyecatcher Billboard, Ring Road, Ibadan';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Kofar Mata Roundabout, Kano', price_per_day = 13, pricing = 13, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Kano, Nigeria.', image_url = 'https://images.pexels.com/photos/8655746/pexels-photo-8655746.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Unipole Billboard, Kofar Mata Roundabout, Kano';
UPDATE advertisements SET title = 'Drive-Time Radio Slot (60s), Wazobia FM, Lagos', price_per_day = 33, pricing = 33, description = 'Prime-time radio advertising slot with mass local reach — 60 seconds, high traffic. Located at Lagos, Nigeria.', image_url = 'https://images.pexels.com/photos/164829/pexels-photo-164829.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Drive-Time Radio Slot (60s), Wazobia FM, Lagos';
UPDATE advertisements SET title = '2-Face Gantry Billboard, Kwame Nkrumah Circle, Accra', price_per_day = 40, pricing = 40, description = 'Large-format outdoor billboard with premium visibility — 14m x 7m, high traffic. Located at Accra, Ghana.', image_url = 'https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Gantry Billboard, Kwame Nkrumah Circle, Accra';
UPDATE advertisements SET title = 'Food Court Screen Network, Accra Mall, Accra', price_per_day = 22, pricing = 22, description = 'Indoor retail advertising reaching shoppers at point of purchase — Network of 8, high traffic. Located at Accra, Ghana.', image_url = 'https://images.pexels.com/photos/37713979/pexels-photo-37713979.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Food Court Screen Network, Accra Mall, Accra';
UPDATE advertisements SET title = 'Departure Lounge Lightboxes, Kotoka Airport, Accra', price_per_day = 52, pricing = 52, description = 'Premium airport advertising reaching business and leisure travellers — 5m x 2.5m, medium traffic. Located at Accra, Ghana.', image_url = 'https://images.pexels.com/photos/13716228/pexels-photo-13716228.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Departure Lounge Lightboxes, Kotoka Airport, Accra';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Tema Motorway, Tema', price_per_day = 18, pricing = 18, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Tema, Ghana.', image_url = 'https://images.pexels.com/photos/1580625/pexels-photo-1580625.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Unipole Billboard, Tema Motorway, Tema';
UPDATE advertisements SET title = 'Wall Panel Billboard, Kejetia Market, Kumasi', price_per_day = 12, pricing = 12, description = 'Large-format outdoor billboard with premium visibility — 15m x 4m, high traffic. Located at Kumasi, Ghana.', image_url = 'https://images.pexels.com/photos/1058759/pexels-photo-1058759.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Wall Panel Billboard, Kejetia Market, Kumasi';
UPDATE advertisements SET title = 'Rear Window Network (50 vehicles), Trotro Fleet, Accra', price_per_day = 16, pricing = 16, description = 'Moving vehicle advertising reaching commuters across the city — 1m x 0.6m each, high traffic. Located at Accra, Ghana.', image_url = 'https://images.pexels.com/photos/35611756/pexels-photo-35611756.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Rear Window Network (50 vehicles), Trotro Fleet, Accra';
UPDATE advertisements SET title = '2-Sided Digital Gantry, Mombasa Road, Nairobi', price_per_day = 120, pricing = 120, description = 'High-brightness digital LED screen with rotating 10-second slots — 12m x 5m, high traffic. Located at Nairobi, Kenya.', image_url = 'https://images.pexels.com/photos/14363740/pexels-photo-14363740.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Sided Digital Gantry, Mombasa Road, Nairobi';
UPDATE advertisements SET title = '2-Face Static Billboard, Kenyatta Avenue CBD, Nairobi', price_per_day = 45, pricing = 45, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Nairobi, Kenya.', image_url = 'https://images.pexels.com/photos/13986019/pexels-photo-13986019.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Static Billboard, Kenyatta Avenue CBD, Nairobi';
UPDATE advertisements SET title = 'Escalator Wrap Series, Two Rivers Mall, Nairobi', price_per_day = 24, pricing = 24, description = 'Indoor retail advertising reaching shoppers at point of purchase — 6 escalators, medium traffic. Located at Nairobi, Kenya.', image_url = 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Escalator Wrap Series, Two Rivers Mall, Nairobi';
UPDATE advertisements SET title = 'International Arrivals Corridor, JKIA, Nairobi', price_per_day = 95, pricing = 95, description = 'Premium airport advertising reaching business and leisure travellers — 10 lightboxes, high traffic. Located at Nairobi, Kenya.', image_url = 'https://images.pexels.com/photos/227690/pexels-photo-227690.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'International Arrivals Corridor, JKIA, Nairobi';
UPDATE advertisements SET title = 'Full Vehicle Branding, Matatu Route 111, Nairobi', price_per_day = 14, pricing = 14, description = 'Moving vehicle advertising reaching commuters across the city — Full vehicle, high traffic. Located at Nairobi, Kenya.', image_url = 'https://images.pexels.com/photos/2031758/pexels-photo-2031758.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Full Vehicle Branding, Matatu Route 111, Nairobi';
UPDATE advertisements SET title = '2-Face Static Billboard, Moi Avenue, Mombasa', price_per_day = 18, pricing = 18, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Mombasa, Kenya.', image_url = 'https://images.pexels.com/photos/32765072/pexels-photo-32765072.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Static Billboard, Moi Avenue, Mombasa';
UPDATE advertisements SET title = 'Digital Spectacular, N1 Highway, Johannesburg', price_per_day = 320, pricing = 320, description = 'High-brightness digital LED screen with rotating 10-second slots — 15m x 7m, high traffic. Located at Johannesburg, South Africa.', image_url = 'https://images.pexels.com/photos/12849349/pexels-photo-12849349.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Digital Spectacular, N1 Highway, Johannesburg';
UPDATE advertisements SET title = 'Rooftop Sign, Sandton City, Johannesburg', price_per_day = 180, pricing = 180, description = 'Large-format outdoor billboard with premium visibility — 20m x 8m, high traffic. Located at Johannesburg, South Africa.', image_url = 'https://images.pexels.com/photos/14536799/pexels-photo-14536799.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Rooftop Sign, Sandton City, Johannesburg';
UPDATE advertisements SET title = 'Platform Screen Network, Gautrain Stations, Johannesburg', price_per_day = 70, pricing = 70, description = 'Moving vehicle advertising reaching commuters across the city — Network of 12, high traffic. Located at Johannesburg, South Africa.', image_url = 'https://images.pexels.com/photos/3626589/pexels-photo-3626589.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Platform Screen Network, Gautrain Stations, Johannesburg';
UPDATE advertisements SET title = 'Entrance Tower Screens, V&A Waterfront, Cape Town', price_per_day = 110, pricing = 110, description = 'Indoor retail advertising reaching shoppers at point of purchase — 2 towers, 6m x 3m, high traffic. Located at Cape Town, South Africa.', image_url = 'https://images.pexels.com/photos/2861656/pexels-photo-2861656.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Entrance Tower Screens, V&A Waterfront, Cape Town';
UPDATE advertisements SET title = 'Baggage Carousel Panels, Cape Town International', price_per_day = 85, pricing = 85, description = 'Premium airport advertising reaching business and leisure travellers — 4 carousels, high traffic. Located at Cape Town, South Africa.', image_url = 'https://images.pexels.com/photos/2033343/pexels-photo-2033343.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Baggage Carousel Panels, Cape Town International';
UPDATE advertisements SET title = '2-Face Beachfront Billboard, Golden Mile, Durban', price_per_day = 48, pricing = 48, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Durban, South Africa.', image_url = 'https://images.pexels.com/photos/31432654/pexels-photo-31432654.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Beachfront Billboard, Golden Mile, Durban';
UPDATE advertisements SET title = 'LED Perimeter Boards, Moses Mabhida Stadium, Durban', price_per_day = 140, pricing = 140, description = 'Live-event advertising with broadcast camera exposure — Pitch-side LED ring, high traffic. Located at Durban, South Africa.', image_url = 'https://images.pexels.com/photos/270085/pexels-photo-270085.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'LED Perimeter Boards, Moses Mabhida Stadium, Durban';
UPDATE advertisements SET title = 'Street Pole Network (30 units), Church Square, Pretoria', price_per_day = 26, pricing = 26, description = 'Eye-level street advertising in high-footfall areas — 1m x 1.5m each, medium traffic. Located at Pretoria, South Africa.', image_url = 'https://images.pexels.com/photos/12534782/pexels-photo-12534782.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Street Pole Network (30 units), Church Square, Pretoria';
UPDATE advertisements SET title = 'Mega Board, 6th October Bridge, Cairo', price_per_day = 95, pricing = 95, description = 'Large-format outdoor billboard with premium visibility — 20m x 8m, high traffic. Located at Cairo, Egypt.', image_url = 'https://images.pexels.com/photos/5102100/pexels-photo-5102100.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Mega Board, 6th October Bridge, Cairo';
UPDATE advertisements SET title = '2-Sided Digital Unipole, Ring Road, Cairo', price_per_day = 110, pricing = 110, description = 'High-brightness digital LED screen with rotating 10-second slots — 14m x 7m, high traffic. Located at Cairo, Egypt.', image_url = 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Sided Digital Unipole, Ring Road, Cairo';
UPDATE advertisements SET title = 'Terminal 3 Lightbox Series, Cairo International', price_per_day = 60, pricing = 60, description = 'Premium airport advertising reaching business and leisure travellers — 12 lightboxes, high traffic. Located at Cairo, Egypt.', image_url = 'https://images.pexels.com/photos/358319/pexels-photo-358319.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Terminal 3 Lightbox Series, Cairo International';
UPDATE advertisements SET title = 'Seafront Billboard, Corniche, Alexandria', price_per_day = 30, pricing = 30, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Alexandria, Egypt.', image_url = 'https://images.pexels.com/photos/18037899/pexels-photo-18037899.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Seafront Billboard, Corniche, Alexandria';
UPDATE advertisements SET title = '2-Face Digital Screen, Bole Road, Addis Ababa', price_per_day = 40, pricing = 40, description = 'High-brightness digital LED screen with rotating 10-second slots — 8m x 4m, high traffic. Located at Addis Ababa, Ethiopia.', image_url = 'https://images.pexels.com/photos/2614818/pexels-photo-2614818.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Digital Screen, Bole Road, Addis Ababa';
UPDATE advertisements SET title = 'Jet Bridge Panels, Bole Airport, Addis Ababa', price_per_day = 55, pricing = 55, description = 'Premium airport advertising reaching business and leisure travellers — 6 bridge wraps, high traffic. Located at Addis Ababa, Ethiopia.', image_url = 'https://images.pexels.com/photos/16292057/pexels-photo-16292057.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Jet Bridge Panels, Bole Airport, Addis Ababa';
UPDATE advertisements SET title = '2-Face Static Billboard, Samora Avenue, Dar es Salaam', price_per_day = 20, pricing = 20, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Dar es Salaam, Tanzania.', image_url = 'https://images.pexels.com/photos/36519146/pexels-photo-36519146.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Static Billboard, Samora Avenue, Dar es Salaam';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Northern Bypass, Kampala', price_per_day = 16, pricing = 16, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, medium traffic. Located at Kampala, Uganda.', image_url = 'https://images.pexels.com/photos/33753279/pexels-photo-33753279.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Unipole Billboard, Northern Bypass, Kampala';
UPDATE advertisements SET title = 'Approach Billboard, Kigali Convention Centre, Kigali', price_per_day = 22, pricing = 22, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Kigali, Rwanda.', image_url = 'https://images.pexels.com/photos/32459947/pexels-photo-32459947.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Approach Billboard, Kigali Convention Centre, Kigali';
UPDATE advertisements SET title = 'Bus Shelter Network (25 shelters), Kigali', price_per_day = 13, pricing = 13, description = 'Eye-level street advertising in high-footfall areas — 25 backlit panels, medium traffic. Located at Kigali, Rwanda.', image_url = 'https://images.pexels.com/photos/374815/pexels-photo-374815.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Bus Shelter Network (25 shelters), Kigali';
UPDATE advertisements SET title = '2-Face Billboard, Boulevard du 30 Juin, Kinshasa', price_per_day = 24, pricing = 24, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Kinshasa, DR Congo.', image_url = 'https://images.pexels.com/photos/5983052/pexels-photo-5983052.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Boulevard du 30 Juin, Kinshasa';
UPDATE advertisements SET title = '2-Face Gantry Billboard, Autoroute Péage, Dakar', price_per_day = 28, pricing = 28, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, high traffic. Located at Dakar, Senegal.', image_url = 'https://images.pexels.com/photos/15829239/pexels-photo-15829239.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Gantry Billboard, Autoroute Péage, Dakar';
UPDATE advertisements SET title = '2-Face Billboard, Akwa Boulevard, Douala', price_per_day = 19, pricing = 19, description = 'High-brightness digital LED screen with rotating 10-second slots — 7m x 4m, high traffic. Located at Abidjan, Côte d''Ivoire.', image_url = 'https://images.pexels.com/photos/2372982/pexels-photo-2372982.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Akwa Boulevard, Douala';
UPDATE advertisements SET title = 'Digital Wall, Corniche, Casablanca', price_per_day = 85, pricing = 85, description = 'Premium airport advertising reaching business and leisure travellers — 8 lightboxes, medium traffic. Located at Abidjan, Côte d''Ivoire.', image_url = 'https://images.pexels.com/photos/12932408/pexels-photo-12932408.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Digital Wall, Corniche, Casablanca';
UPDATE advertisements SET title = 'Arrivals Hall Panels, Menara Airport, Marrakech', price_per_day = 45, pricing = 45, description = 'Large-format outdoor billboard with premium visibility — 10m x 5m, high traffic. Located at Douala, Cameroon.', image_url = 'https://images.pexels.com/photos/5785306/pexels-photo-5785306.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Arrivals Hall Panels, Menara Airport, Marrakech';
UPDATE advertisements SET title = '2-Face Billboard, Habib Bourguiba Avenue, Tunis', price_per_day = 26, pricing = 26, description = 'High-brightness digital LED screen with rotating 10-second slots — 11m x 6m, high traffic. Located at Casablanca, Morocco.', image_url = 'https://images.pexels.com/photos/12602146/pexels-photo-12602146.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Habib Bourguiba Avenue, Tunis';
UPDATE advertisements SET title = 'Street Pole Network (40 units), Didouche Mourad, Algiers', price_per_day = 22, pricing = 22, description = 'Premium airport advertising reaching business and leisure travellers — 6 lightboxes, high traffic. Located at Marrakech, Morocco.', image_url = 'https://images.pexels.com/photos/2073082/pexels-photo-2073082.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Street Pole Network (40 units), Didouche Mourad, Algiers';
UPDATE advertisements SET title = '2-Face Unipole Billboard, Great East Road, Lusaka', price_per_day = 14, pricing = 14, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, high traffic. Located at Tunis, Tunisia.', image_url = 'https://images.pexels.com/photos/788662/pexels-photo-788662.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Unipole Billboard, Great East Road, Lusaka';
UPDATE advertisements SET title = '2-Face Billboard, Samora Machel Avenue, Harare', price_per_day = 12, pricing = 12, description = 'Eye-level street advertising in high-footfall areas — 1m x 1.5m each, medium traffic. Located at Algiers, Algeria.', image_url = 'https://images.pexels.com/photos/2422588/pexels-photo-2422588.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Samora Machel Avenue, Harare';
UPDATE advertisements SET title = 'Mall Screen Network, Game City, Gaborone', price_per_day = 15, pricing = 15, description = 'Large-format outdoor billboard with premium visibility — 12m x 6m, medium traffic. Located at Lusaka, Zambia.', image_url = 'https://images.pexels.com/photos/38380369/pexels-photo-38380369.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Mall Screen Network, Game City, Gaborone';
UPDATE advertisements SET title = '2-Face Billboard, Independence Avenue, Windhoek', price_per_day = 11, pricing = 11, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, medium traffic. Located at Harare, Zimbabwe.', image_url = 'https://images.pexels.com/photos/4700105/pexels-photo-4700105.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Independence Avenue, Windhoek';
UPDATE advertisements SET title = '2-Face Billboard, Julius Nyerere Avenue, Maputo', price_per_day = 13, pricing = 13, description = 'Indoor retail advertising reaching shoppers at point of purchase — Network of 6, medium traffic. Located at Gaborone, Botswana.', image_url = 'https://images.pexels.com/photos/3962285/pexels-photo-3962285.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Face Billboard, Julius Nyerere Avenue, Maputo';
UPDATE advertisements SET title = '2-Sided Digital Corner Screen, Plateau, Abidjan', price_per_day = 62, pricing = 62, description = 'Large-format outdoor billboard with premium visibility — 8m x 4m, medium traffic. Located at Windhoek, Namibia.', image_url = 'https://images.pexels.com/photos/4700102/pexels-photo-4700102.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = '2-Sided Digital Corner Screen, Plateau, Abidjan';
UPDATE advertisements SET title = 'Terminal Lightbox Series, Félix-Houphouët-Boigny Airport, Abidjan', price_per_day = 44, pricing = 44, description = 'Large-format outdoor billboard with premium visibility — 9m x 4.5m, medium traffic. Located at Maputo, Mozambique.', image_url = 'https://images.pexels.com/photos/34149123/pexels-photo-34149123.jpeg?auto=compress&cs=tinysrgb&w=640' WHERE title = 'Terminal Lightbox Series, Félix-Houphouët-Boigny Airport, Abidjan';

-- Sanity check: no placement should sit outside the published market band.
SELECT title, price_per_day, round(price_per_day * 30 * 1500 / 1000000.0, 2) AS naira_millions_per_month
FROM advertisements ORDER BY price_per_day DESC LIMIT 5;
