import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';

/**
 * The event vocabulary exists in two places, and they must not drift.
 *
 * `EventName` in telemetry.ts makes a typo a compile error. A CHECK constraint
 * in Postgres is the only thing that stops a forged event arriving with the
 * public anon key — measured on production 2026-09-08:
 *
 *     analytics_events CHECK constraints : NONE
 *     INSERT policy : roles={anon,authenticated} WITH CHECK (true)
 *
 * so any caller could write unlimited rows with any name, any business_id and
 * any user_id.
 *
 * Two hand-maintained copies of one list drift, and this drift fails in the
 * worst direction: a new event passes typecheck, ships, and is then rejected
 * by the database inside the `try {} catch {}` that telemetry deliberately
 * swallows. The event never arrives and nothing reports it.
 *
 * So the migration is GENERATED from the union, and this test fails if the two
 * ever disagree.
 */

const MIGRATION = 'supabase/migrations/20260908120000_analytics_event_integrity.sql';
const sql = readFileSync(MIGRATION, 'utf8');

/** Mirrors the parser in scripts/gen-event-constraint.mjs. */
function declaredEvents(): string[] {
  const src = readFileSync('src/lib/telemetry.ts', 'utf8');
  const start = src.indexOf('export type EventName =');
  const names: string[] = [];
  for (const line of src.slice(start).split('\n')) {
    const m = /^\s*\|\s*'([a-z0-9_]+)'/.exec(line);
    if (m) names.push(m[1]);
    if (/'\s*;\s*$/.test(line)) break;
  }
  return names;
}

/** The vocabulary the migration actually constrains to. */
function constrainedEvents(): string[] {
  const start = sql.indexOf('analytics_events_name_known check (name in (');
  expect(start, 'name constraint not found in migration').toBeGreaterThan(-1);
  const end = sql.indexOf('))', start);
  return [...sql.slice(start, end).matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1]);
}

describe('the SQL vocabulary matches the TypeScript union', () => {
  const declared = declaredEvents();
  const constrained = constrainedEvents();

  it('parsed a plausible number of events from both', () => {
    // Guards both parsers. A regex that silently matched nothing would make
    // the equality assertion below pass against two empty lists — which is
    // exactly how the sibling test in eventCoverage.test.ts first went wrong.
    expect(declared.length).toBeGreaterThan(15);
    expect(constrained.length).toBeGreaterThan(15);
  });

  it('constrains exactly the declared events, in the same order', () => {
    expect(constrained).toEqual(declared);
  });

  it('says it is generated, so nobody edits it by hand', () => {
    expect(sql).toMatch(/GENERATED by scripts\/gen-event-constraint\.mjs/);
    expect(sql).toMatch(/Do not edit by hand/);
  });
});

describe('the migration closes the two holes it claims to', () => {
  it('stops an event being attributed to somebody else', () => {
    /*
     * The old policy was WITH CHECK (true). Anonymous events must stay
     * possible — user_id NULL is how the entire public directory is measured
     * — but claiming to BE somebody must not be.
     */
    expect(sql).toMatch(/with check \(user_id is null or user_id = auth\.uid\(\)\)/);
  });

  it('keeps anonymous inserts working', () => {
    // Removing anon here would silently blind the public site rather than
    // secure it: almost every measured visitor is signed out.
    expect(sql).toMatch(/for insert to anon, authenticated/);
  });

  it('caps props at the database, not only in the client', () => {
    expect(sql).toMatch(/pg_column_size\(props\) < 4096/);
  });
});

describe('the migration is safe to apply to a live table', () => {
  it('adds constraints NOT VALID before validating them', () => {
    /*
     * Ordering matters on a table with 43,596 rows and an open insert path:
     * NOT VALID makes the constraint apply to new rows immediately, and the
     * separate VALIDATE checks the history without holding a lock that blocks
     * writes.
     */
    for (const name of ['analytics_events_name_known', 'analytics_events_props_small']) {
      const add = sql.indexOf(`add constraint ${name}`);
      const validate = sql.indexOf(`validate constraint ${name}`);
      expect(add, `${name} is added`).toBeGreaterThan(-1);
      expect(validate, `${name} is validated`).toBeGreaterThan(add);
    }
    expect(sql.match(/not valid;/g)?.length).toBe(2);
  });

  it('is re-runnable', () => {
    // Every object is dropped if present before being created, so applying it
    // twice is a no-op rather than an error.
    expect(sql).toMatch(/drop constraint if exists analytics_events_name_known/);
    expect(sql).toMatch(/drop constraint if exists analytics_events_props_small/);
    expect(sql).toMatch(/drop policy if exists analytics_insert/);
  });

  it('writes no rows', () => {
    /*
     * A schema migration that also deletes data is how a rollback becomes
     * unreversible. The 43,354 junk `signin` rows are purged separately and
     * deliberately — see audits/NOWOPEN_APPLY_RUNBOOK.md item 5c.
     */
    const executed = sql.replace(/^\s*--.*$/gm, '');
    expect(executed).not.toMatch(/\b(insert|update|delete)\s+(into|from|public\.)/i);
  });

  it('does not attempt rate limiting in a trigger', () => {
    /*
     * Deliberate, and stated in the file. A per-insert COUNT over a growing
     * table is a self-inflicted performance problem, and an attacker holding
     * the anon key can afford to be patient. That control belongs at the edge.
     */
    expect(sql).not.toMatch(/create\s+trigger/i);
    expect(sql).toMatch(/Rate limiting is deliberately NOT attempted/);
  });
});
