import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import {
  Film, Download, ImageIcon, LayoutGrid, Loader2, Sparkles, ListVideo,
  LayoutTemplate, Check, Plus, Copy, Trash2, FolderOpen, Wand2, Clapperboard,
} from 'lucide-react';
import type { DirectorScene } from '../../lib/creativeDirector';
import {
  renderVideo, renderPoster, renderContactSheet, drawSceneFrame, buildRenderTimeline,
  RENDER_DIMENSIONS, RENDER_PALETTES,
  type RenderAspect, type SceneFrameOptions,
} from '../../lib/renderVideo';
import {
  motionScenesFromJob, motionTotalSeconds, MOTION_SCENE_COUNTS,
  type MotionConfig, type MotionStyle, type MotionDuration,
} from '../../lib/motionGraphics';
import { buildAiVideoClips, videoGenModelsForTier } from '../../lib/videoGen';
import AiVideoGenPicker from '../studio/AiVideoGenPicker';
import { MOTION_TEMPLATES, motionTemplateByKey, type MotionTemplate } from '../../data/motionTemplates';
import {
  blankMotionProject, motionProjectFromTemplate, motionProjectFromPrompt,
  saveMotionProject, deleteMotionProject, duplicateMotionProject, loadMotionProjects,
  MOTION_PROJECT_STATUSES, MOTION_PROJECT_STATUS_LABELS,
  type MotionProject, type MotionProjectStatus,
} from '../../lib/motionProject';

// Motion Studio (#3) — one editable project, three ways in.
//
// Quick Create  → pick a format and a modern template; a full MotionProject is born.
// Studio        → the editor over that project: words, shape, pace, palette, live
//                 canvas preview, storyboard and a real MP4/WebM export.
// AI Director   → describe the motion in plain English; the local rule-based
//                 director designs a full project (no cloud model, no wait).
//
// Every mode writes the SAME MotionProject (src/lib/motionProject.ts), persisted
// under nowopen_motion_projects, so anything made or generated stays editable:
// change the words, swap the palette, resize for another format and render again.
//
// The export films over either the FREE CANVAS (designed motion graphics, no
// model, no cost) or AI VIDEO clips generated by a free / paid model, with the
// same motion design layered on top. Honest about what it is either way: real,
// downloadable video from the browser — clips that fail to load fall back to
// the designed graphics, so nothing here silently fakes footage.

type Mode = 'quick' | 'studio' | 'ai';

const MODES: { key: Mode; label: string; emoji: string; blurb: string }[] = [
  { key: 'quick', label: 'Quick Create', emoji: '⚡', blurb: 'Pick a format and a modern template — a full project is born in one click.' },
  { key: 'studio', label: 'Studio', emoji: '🎛️', blurb: 'The full editor: words, shape, pace, palette, live preview and export.' },
  { key: 'ai', label: 'AI Director', emoji: '🪄', blurb: 'Describe it in plain English — the local director designs a full project for you.' },
];

const EXAMPLE_PROMPTS = [
  'A countdown reel for a Lagos coffee shop opening this Friday',
  '20% off this weekend — a promotion for a restaurant in Abuja',
  'Billboard for Ember Hotel — grand opening, luxury rooms',
  'A 30 second YouTube opener for a fashion boutique',
];

interface StyleMeta {
  key: MotionStyle;
  label: string;
  emoji: string;
  desc: string;
  defaults: { headline: string; subhead: string; cta: string; logoEmoji: string };
}

const STYLES: StyleMeta[] = [
  { key: 'logo-reveal', label: 'Logo Reveal', emoji: '✨', desc: 'The brand mark comes alive — scale and stroke onto a gradient.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'Every business, open to the world', cta: 'Find your next favourite', logoEmoji: '✦' } },
  { key: 'motion-poster', label: 'Motion Poster', emoji: '🎬', desc: 'Campaign art given life — headline, accent and a slow push-in.', defaults: { headline: 'RESTAURANT WEEK', subhead: 'Sep 1–30 · Lagos', cta: 'Get your tickets', logoEmoji: '🍽️' } },
  { key: 'kinetic-type', label: 'Kinetic Typography', emoji: '🔠', desc: 'One word per beat — the headline pops across four cards.', defaults: { headline: 'Make it local today', subhead: 'The NowOpen voice', cta: 'Join NowOpen Africa', logoEmoji: '✦' } },
  { key: 'lower-third', label: 'Lower Third', emoji: '📺', desc: 'Name + role caption card for interviews and panels.', defaults: { headline: 'Yemzo', subhead: 'Founder, NowOpen Africa', cta: '', logoEmoji: '👤' } },
  { key: 'countdown', label: 'Countdown', emoji: '⏱️', desc: '3…2…1…GO — suspense for a launch or a live stream.', defaults: { headline: 'GO!', subhead: 'The countdown is on', cta: 'Tune in now', logoEmoji: '🚀' } },
  { key: 'badge', label: 'Animated Badge', emoji: '🏷️', desc: 'A looping status stamp — Open Now, Verified, New.', defaults: { headline: 'OPEN NOW', subhead: 'NowOpen Africa', cta: 'Order ahead', logoEmoji: '✅' } },
  { key: 'reveal-title', label: 'Reveal Title', emoji: '🎞️', desc: 'A bold headline wipe for episodes and campaign headers.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'The platform for local business', cta: 'Launch yours', logoEmoji: '✦' } },
];

const ASPECTS: { key: RenderAspect; label: string; hint: string }[] = [
  { key: 'Vertical', label: 'Vertical', hint: 'Reels, TikTok, Status' },
  { key: 'Square', label: 'Square', hint: 'Feed posts' },
  { key: 'Landscape', label: 'Landscape', hint: 'YouTube, websites' },
];

const DURATIONS: { key: MotionDuration; label: string; hint: string }[] = [
  { key: 'short', label: 'Short', hint: '2s / card' },
  { key: 'medium', label: 'Medium', hint: '3s / card' },
  { key: 'long', label: 'Long', hint: '4s / card' },
];

function timeAgo(iso: string): string {
  const s = Math.max(1, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (s < 60) return `${s}s ago`;
  const m = Math.round(s / 60);
  if (m < 60) return `${m}m ago`;
  return `${Math.round(m / 60)}h ago`;
}

/** Live, looping canvas preview of the motion brief — real frames, real timing. */
function MotionPreview({ opts, scenes }: { opts: SceneFrameOptions; scenes: DirectorScene[] }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const dims = RENDER_DIMENSIONS[opts.aspect];

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return; // no 2D context (jsdom) — nothing to preview
    // Preview at half resolution; the export renders full 1080p.
    canvas.width = Math.round(dims.width / 2);
    canvas.height = Math.round(dims.height / 2);
    const timeline = buildRenderTimeline(scenes, opts);
    let frame = 0;
    let raf = 0;
    let playing = true;
    const tick = () => {
      if (!playing) return;
      drawSceneFrame(ctx, canvas.width, canvas.height, opts, scenes, timeline, frame);
      frame = (frame + 1) % timeline.totalFrames;
      raf = window.requestAnimationFrame(tick);
    };
    raf = window.requestAnimationFrame(tick);
    return () => { playing = false; window.cancelAnimationFrame(raf); };
  }, [opts, scenes, dims.width, dims.height]);

  return <canvas ref={canvasRef} className="w-full max-w-md mx-auto rounded-xl border border-gray-200 dark:border-gray-700 bg-black" />;
}

function swatchStyle(palette: [string, string, string]): React.CSSProperties {
  return { background: `linear-gradient(135deg, ${palette[0]}, ${palette[1]} 55%, ${palette[2]})` };
}

export default function MotionGraphicsStudio() {
  const [mode, setMode] = useState<Mode>('quick');
  const [project, setProject] = useState<MotionProject>(() => loadMotionProjects()[0] ?? blankMotionProject());
  const [projects, setProjects] = useState<MotionProject[]>(() => loadMotionProjects());
  const [quickAspect, setQuickAspect] = useState<RenderAspect>('Vertical');
  const [prompt, setPrompt] = useState('');
  const [aiError, setAiError] = useState<string | null>(null);

  const [rendering, setRendering] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  // Autosave — every edit lands in nowopen_motion_projects.
  useEffect(() => { setProjects(saveMotionProject(project)); }, [project]);

  const patch = (partial: Partial<MotionProject>) =>
    setProject((prev) => (prev ? { ...prev, ...partial, updatedAt: new Date().toISOString() } : prev));

  const editBrief = (partial: Partial<MotionConfig>) =>
    setProject((prev) => (prev ? { ...prev, templateKey: undefined, brief: { ...prev.brief, ...partial }, updatedAt: new Date().toISOString() } : prev));

  const editRender = (partial: Partial<MotionProject['render']>) =>
    setProject((prev) => (prev ? { ...prev, render: { ...prev.render, ...partial }, updatedAt: new Date().toISOString() } : prev));

  const openProject = (p: MotionProject, nextMode: Mode = 'studio') => {
    setProject(p);
    setMode(nextMode);
    setError(null);
    setAiError(null);
  };

  const startFromTemplate = (t: MotionTemplate) => {
    openProject(motionProjectFromTemplate(t, quickAspect));
    toast.success(`${t.name} project created — fine-tune it in Studio.`);
  };

  const startBlank = (aspect: RenderAspect = 'Vertical') => {
    openProject(blankMotionProject(aspect));
    toast.success('Blank project created — now in Studio.');
  };

  const buildFromPrompt = () => {
    const trimmed = prompt.trim();
    if (!trimmed) { setAiError('Tell the director what you want first.'); return; }
    openProject(motionProjectFromPrompt(trimmed));
    setPrompt('');
    toast.success('Designed locally — a full editable project is now in Studio.');
  };

  const duplicate = () => {
    openProject(duplicateMotionProject(project));
    toast.success('Project duplicated.');
  };

  const remove = () => {
    const next = deleteMotionProject(project.id);
    setProjects(next);
    openProject(next[0] ?? blankMotionProject('Vertical'));
    toast.success('Project deleted.');
  };

  const brief = project.brief;
  const label = STYLES.find((s) => s.key === brief.style)?.label ?? 'Motion';
  const scenes = useMemo(() => motionScenesFromJob(brief), [brief]);
  const opts: SceneFrameOptions = useMemo(
    () => ({
      businessName: brief.business || 'NowOpen',
      directionLabel: label,
      hook: brief.headline,
      cta: brief.cta,
      aspect: brief.aspect,
      logoEmoji: brief.logoEmoji || '✦',
      palette: project.palette,
      scenesCount: scenes.length,
    }),
    [brief, label, project.palette, scenes.length],
  );
  const seconds = motionTotalSeconds(brief);
  const renderSource = project.render.source;
  const templateName = project.templateKey ? motionTemplateByKey(project.templateKey)?.name : null;

  const downloadVideo = async () => {
    setRendering(true);
    setError(null);
    setProgress(0);
    try {
      let footage;
      if (renderSource === 'aivideo') {
        footage = buildAiVideoClips({
          businessName: brief.business || 'NowOpen',
          industryLabel: 'brand',
          directionLabel: label,
          scenes,
          model: project.render.model,
          aspect: brief.aspect,
        });
      }
      const result = await renderVideo(
        { ...opts, footage, footageEnabled: renderSource === 'aivideo' },
        scenes,
        (p) => setProgress(p),
      );
      const url = URL.createObjectURL(result.blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `motion-${brief.style}-${brief.aspect.toLowerCase()}.${result.mimeType.includes('mp4') ? 'mp4' : 'webm'}`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not render the video.');
    } finally {
      setRendering(false);
      setProgress(0);
    }
  };

  const downloadStill = useCallback((kind: 'poster' | 'sheet') => {
    const still = kind === 'poster' ? renderPoster(opts, scenes) : renderContactSheet(opts, scenes);
    if (!still) { toast.error('Still export is not supported in this browser.'); return; }
    const a = document.createElement('a');
    a.href = still.dataUrl;
    a.download = `motion-${brief.style}-${kind}.png`;
    a.click();
    toast.success(`${kind === 'poster' ? 'Poster' : 'Contact sheet'} exported (PNG).`);
  }, [opts, scenes, brief.style]);

  return (
    <div className="space-y-5">
      {/* Header + mode tabs */}
      <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="min-w-0">
            <h2 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <Clapperboard size={16} className="text-purple-500" /> Motion Studio
            </h2>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 max-w-2xl">
              One editable project, three ways in. Quick Create starts from a format and a modern template,
              Studio is the full editor, and the AI Director writes the brief for you.
              Every mode ends in the same MotionProject you can resize, re-edit and render.
            </p>
          </div>
          <div className="flex rounded-xl bg-gray-100 dark:bg-gray-800 p-1">
            {MODES.map((m) => (
              <button key={m.key} onClick={() => setMode(m.key)} aria-pressed={mode === m.key} title={m.blurb}
                className={`px-3.5 py-2 rounded-lg text-xs font-bold transition ${mode === m.key ? 'bg-white dark:bg-gray-700 text-gray-900 dark:text-white shadow-sm' : 'text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'}`}>
                {m.emoji} {m.label}
              </button>
            ))}
          </div>
        </div>
        <p className="mt-2.5 text-[11px] text-gray-500 dark:text-gray-400">{MODES.find((m) => m.key === mode)?.blurb}</p>
      </section>

      {/* Project bar — the shared, autosaved project behind every mode */}
      {(mode === 'studio' || mode === 'ai') && (
        <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-4">
          <div className="flex flex-wrap items-end gap-3">
            <label className="block min-w-[180px] flex-1">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Project name</span>
              <input value={project.name} onChange={(e) => patch({ name: e.target.value })}
                className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Status</span>
              <select value={project.status} onChange={(e) => patch({ status: e.target.value as MotionProjectStatus })}
                className="mt-1 px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
                {MOTION_PROJECT_STATUSES.map((s) => (
                  <option key={s} value={s}>{MOTION_PROJECT_STATUS_LABELS[s]}</option>
                ))}
              </select>
            </label>
            <div className="flex flex-wrap items-center gap-2 ml-auto">
              <span className="text-[11px] text-gray-400 inline-flex items-center gap-1" title="Saved to this browser under nowopen_motion_projects">
                <Check size={12} className="text-emerald-500" /> Autosaved · {timeAgo(project.updatedAt)}
              </span>
              <button onClick={() => startBlank()} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                <Plus size={13} /> New
              </button>
              <button onClick={duplicate} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                <Copy size={13} /> Duplicate
              </button>
              <button onClick={remove} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40 transition">
                <Trash2 size={13} /> Delete
              </button>
            </div>
          </div>
        </section>
      )}

      {/* QUICK CREATE — format + template gallery + your projects */}
      {mode === 'quick' && (
        <>
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <LayoutTemplate size={15} className="text-purple-500" /> Pick your format
            </h3>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5">
              Choose where it plays. You can switch shape again in Studio without losing anything.
            </p>
            <div className="mt-3 grid grid-cols-1 sm:grid-cols-3 gap-2">
              {ASPECTS.map((a) => (
                <button key={a.key} onClick={() => setQuickAspect(a.key)} aria-pressed={quickAspect === a.key}
                  className={`text-left p-3 rounded-xl border transition ${quickAspect === a.key ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20' : 'border-gray-200 dark:border-gray-700 hover:border-purple-300'}`}>
                  <span className="text-xs font-bold text-gray-900 dark:text-white">{a.label}</span>
                  <span className="block mt-0.5 text-[10px] text-gray-500 dark:text-gray-400">{a.hint} · {RENDER_DIMENSIONS[a.key].width}×{RENDER_DIMENSIONS[a.key].height}</span>
                </button>
              ))}
            </div>
          </section>

          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <div>
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <LayoutTemplate size={15} className="text-purple-500" /> Modern template gallery
              </h3>
              <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5">
                The latest motion design concepts, ready to film. Each one becomes a real project you can keep editing in Studio.
              </p>
            </div>
            <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              {MOTION_TEMPLATES.map((t) => (
                <button key={t.key} onClick={() => startFromTemplate(t)} title={`${t.name} — ${t.concept}`}
                  className="text-left rounded-xl border-2 border-gray-200 dark:border-gray-700 hover:border-purple-300 transition overflow-hidden">
                  <div className="relative h-20" style={swatchStyle(t.palette)}>
                    <span className="absolute inset-0 flex items-center justify-center text-3xl drop-shadow">{t.emoji}</span>
                  </div>
                  <div className="p-2.5">
                    <span className="block text-xs font-bold text-gray-900 dark:text-white">{t.name}</span>
                    <p className="mt-0.5 text-[10px] leading-snug text-gray-500 dark:text-gray-400 line-clamp-2">{t.concept}</p>
                    <div className="mt-1.5 flex flex-wrap gap-1">
                      {t.tags.map((tag) => (
                        <span key={tag} className="px-1.5 py-0.5 rounded-md bg-purple-50 dark:bg-purple-900/30 text-[9px] font-bold text-purple-600 dark:text-purple-300">{tag}</span>
                      ))}
                    </div>
                  </div>
                </button>
              ))}
            </div>
            <button onClick={() => startBlank(quickAspect)}
              className="mt-4 inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold transition">
              <Plus size={14} /> Start from a blank brief
            </button>
          </section>

          {projects.length > 0 && (
            <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <FolderOpen size={15} className="text-purple-500" /> Your projects
              </h3>
              <div className="mt-3 space-y-1.5">
                {projects.map((p) => (
                  <div key={p.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-gray-100 dark:border-gray-700 px-3.5 py-2.5">
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-xs font-bold text-gray-900 dark:text-white">{p.name}</span>
                      <span className="text-[10px] text-gray-500 dark:text-gray-400">
                        {p.source === 'ai' ? 'AI designed' : p.source === 'template' ? 'Template' : 'Blank'} · {MOTION_PROJECT_STATUS_LABELS[p.status]} · {p.brief.aspect} · {timeAgo(p.updatedAt)}
                      </span>
                    </span>
                    <span className="w-4 h-4 rounded-full shrink-0" style={swatchStyle(p.palette)} />
                    <button onClick={() => openProject(p)} className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-600 hover:bg-purple-700 text-white transition">
                      Open in Studio
                    </button>
                    <button onClick={() => { deleteMotionProject(p.id); setProjects(loadMotionProjects()); }} aria-label={`Delete ${p.name}`}
                      className="inline-flex items-center px-2 py-1.5 rounded-lg text-xs text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition">
                      <Trash2 size={13} />
                    </button>
                  </div>
                ))}
              </div>
            </section>
          )}
        </>
      )}

      {/* AI DIRECTOR — plain English → a full project */}
      {mode === 'ai' && (
        <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
            <Wand2 size={15} className="text-purple-500" /> AI Director
          </h3>
          <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 max-w-2xl">
            Describe the motion in plain English — the local director reads the offer, the format, the vibe and the length,
            and designs a complete project you can open in Studio and edit. It is honest: no cloud model, no wait,
            and nothing that cannot be changed afterwards.
          </p>
          <div className="mt-4">
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Your brief</span>
              <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={4}
                placeholder="e.g. A countdown reel for a Lagos coffee shop opening this Friday"
                className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-1.5">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Try:</span>
            {EXAMPLE_PROMPTS.map((p) => (
              <button key={p} onClick={() => setPrompt(p)}
                className="px-2.5 py-1 rounded-lg bg-gray-100 dark:bg-gray-700 text-[11px] text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                {p}
              </button>
            ))}
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <button onClick={buildFromPrompt}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold transition">
              <Sparkles size={15} /> Build motion project
            </button>
            {aiError && <p role="alert" className="text-xs text-red-600 dark:text-red-400">{aiError}</p>}
          </div>
        </section>
      )}

      {/* STUDIO — the full editor over the shared project */}
      {mode === 'studio' && (
        <>
          {templateName && (
            <p className="text-[11px] text-purple-700 dark:text-purple-300">
              Based on {templateName} — tweak the words, shape, pace and palette below; the preview updates live and the project stays editable.
            </p>
          )}

          {/* Style picker */}
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <Film size={15} className="text-purple-500" /> What are you animating?
            </h3>
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
              {STYLES.map((s) => (
                <button key={s.key} onClick={() => editBrief({ style: s.key, headline: s.defaults.headline, subhead: s.defaults.subhead, cta: s.defaults.cta, logoEmoji: s.defaults.logoEmoji })} aria-pressed={brief.style === s.key}
                  className={`text-left p-3 rounded-xl border transition ${brief.style === s.key ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20' : 'border-gray-200 dark:border-gray-700 hover:border-purple-300'}`}>
                  <span className="text-xl">{s.emoji}</span>
                  <span className="block mt-1 text-xs font-bold text-gray-900 dark:text-white">{s.label}</span>
                  <span className="block mt-0.5 text-[10px] leading-snug text-gray-500 dark:text-gray-400">{s.desc}</span>
                </button>
              ))}
            </div>
          </section>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* Editor */}
            <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <Sparkles size={15} className="text-purple-500" /> Your motion brief
              </h3>

              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
                <label className="block">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Brand lockup</span>
                  <input value={brief.business} onChange={(e) => editBrief({ business: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                </label>
                <label className="block">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Mark emoji</span>
                  <input value={brief.logoEmoji} onChange={(e) => editBrief({ logoEmoji: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                </label>
                <label className="block sm:col-span-2">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Headline</span>
                  <input value={brief.headline} onChange={(e) => editBrief({ headline: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                </label>
                <label className="block sm:col-span-2">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Sub-line (voiceover strip)</span>
                  <input value={brief.subhead} onChange={(e) => editBrief({ subhead: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                </label>
                <label className="block sm:col-span-2">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Call to action (end card)</span>
                  <input value={brief.cta} onChange={(e) => editBrief({ cta: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                </label>
              </div>

              <div className="mt-4 flex flex-wrap items-center gap-2">
                <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Shape</span>
                {ASPECTS.map((a) => (
                  <button key={a.key} onClick={() => editBrief({ aspect: a.key })} aria-pressed={brief.aspect === a.key}
                    className={`px-3 py-2 rounded-lg text-xs font-semibold transition ${brief.aspect === a.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                    {a.label}<span className="ml-1.5 font-normal opacity-70">{a.hint}</span>
                  </button>
                ))}
              </div>

              <div className="mt-3 flex flex-wrap items-center gap-2">
                <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Pace</span>
                {DURATIONS.map((d) => (
                  <button key={d.key} onClick={() => editBrief({ duration: d.key })} aria-pressed={brief.duration === d.key}
                    className={`px-3 py-2 rounded-lg text-xs font-semibold transition ${brief.duration === d.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                    {d.label}<span className="ml-1.5 font-normal opacity-70">{d.hint}</span>
                  </button>
                ))}
              </div>

              <div className="mt-3">
                <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Palette</span>
                <div className="mt-1.5 flex flex-wrap gap-2">
                  {RENDER_PALETTES.map((p, i) => (
                    <button key={i} onClick={() => patch({ palette: p, templateKey: undefined })} aria-pressed={project.palette === p} title={p.join(' → ')}
                      className={`w-8 h-8 rounded-lg border-2 transition ${project.palette === p ? 'border-purple-600 ring-2 ring-purple-300' : 'border-transparent'}`}
                      style={swatchStyle(p)} />
                  ))}
                </div>
              </div>
            </section>

            {/* Preview + storyboard */}
            <div className="space-y-5 min-w-0">
              <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
                <div className="flex items-center justify-between gap-2">
                  <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                    <Film size={15} className="text-purple-500" /> Live preview
                  </h3>
                  <span className="text-[11px] font-semibold text-gray-400">
                    {MOTION_SCENE_COUNTS[brief.style]} cards · {seconds}s · {RENDER_DIMENSIONS[brief.aspect].width}×{RENDER_DIMENSIONS[brief.aspect].height}
                  </span>
                </div>
                <div className="mt-3">
                  <MotionPreview opts={opts} scenes={scenes} />
                </div>
              </section>

              <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
                <div className="p-4 border-b border-gray-100 dark:border-gray-700">
                  <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                    <ListVideo size={15} className="text-purple-500" /> Storyboard
                  </h3>
                </div>
                <ol className="divide-y divide-gray-100 dark:divide-gray-700">
                  {scenes.map((s, i) => (
                    <li key={s.id} className="flex gap-3 p-3.5">
                      <span className="shrink-0 w-7 h-7 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 text-xs font-bold flex items-center justify-center">{i + 1}</span>
                      <div className="min-w-0 flex-1">
                        <p className="text-sm font-semibold text-gray-900 dark:text-white">{s.text}</p>
                        <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 italic">“{s.voiceover}”</p>
                      </div>
                      <span className="shrink-0 text-[11px] font-semibold text-gray-400 tabular-nums">{s.seconds}s</span>
                    </li>
                  ))}
                </ol>
              </section>
            </div>
          </div>

          {/* Export */}
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                  <Film size={15} className="text-purple-500" /> Export
                </h3>
                <p className="text-[11px] text-gray-500 dark:text-gray-400 max-w-lg">
                  {renderSource === 'canvas'
                    ? 'Films the motion graphic on the free browser canvas — real, downloadable video with captions, motion and the end card. No model, no cost.'
                    : 'Films your motion design over generated AI video clips from a free or paid model — with captions, motion and the end card on top.'}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={() => downloadStill('poster')} disabled={rendering}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
                  <ImageIcon size={13} /> Poster PNG
                </button>
                <button onClick={() => downloadStill('sheet')} disabled={rendering}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
                  <LayoutGrid size={13} /> Contact sheet
                </button>
                <button onClick={downloadVideo} disabled={rendering}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 disabled:opacity-60 text-white text-sm font-semibold transition">
                  {rendering ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
                  {rendering ? `Filming ${Math.round(progress * 100)}%` : `Render ${seconds}s video`}
                </button>
              </div>
            </div>

            <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 dark:border-gray-700 p-3">
              <div className="flex items-center gap-1.5">
                <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Render source</span>
                <div className="ml-1 flex rounded-lg bg-gray-100 dark:bg-gray-800 p-0.5">
                  {([
                    { key: 'canvas', label: 'Free canvas' },
                    { key: 'aivideo', label: 'AI video gen' },
                  ] as const).map((o) => (
                    <button key={o.key} type="button" onClick={() => editRender({ source: o.key })} aria-pressed={renderSource === o.key}
                      className={`px-3 py-1.5 rounded-md text-xs font-bold transition ${renderSource === o.key ? 'bg-purple-600 text-white shadow-sm' : 'text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-gray-700'}`}>
                      {o.label}
                    </button>
                  ))}
                </div>
              </div>
              {renderSource === 'aivideo' ? (
                <span className="text-[11px] text-gray-500 dark:text-gray-400">Designed motion graphics + {project.render.tier === 'free' ? 'free' : 'paid'} AI clips underneath.</span>
              ) : (
                <span className="text-[11px] text-gray-500 dark:text-gray-400">100% free — the canvas is the renderer.</span>
              )}
            </div>

            {renderSource === 'aivideo' && (
              <div className="mt-3">
                <AiVideoGenPicker
                  tier={project.render.tier}
                  onTier={(t) => {
                    editRender({ tier: t, model: videoGenModelsForTier(t)[0].key });
                  }}
                  model={project.render.model}
                  onModel={(m) => editRender({ model: m })}
                />
              </div>
            )}

            {rendering && (
              <div className="mt-3 h-1.5 rounded-full bg-gray-100 dark:bg-gray-700 overflow-hidden">
                <div className="h-full bg-purple-600 transition-[width] duration-200" style={{ width: `${Math.round(progress * 100)}%` }} />
              </div>
            )}

            {error && <p role="alert" className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>}
          </section>
        </>
      )}
    </div>
  );
}
