import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { Film, Download, ImageIcon, LayoutGrid, Loader2, Sparkles, ListVideo, LayoutTemplate, Check, X } from 'lucide-react';
import type { DirectorScene } from '../../lib/creativeDirector';
import {
  renderVideo, renderPoster, renderContactSheet, drawSceneFrame, buildRenderTimeline,
  RENDER_DIMENSIONS, RENDER_PALETTES,
  type RenderAspect, type SceneFrameOptions,
} from '../../lib/renderVideo';
import {
  motionScenesFromJob, motionTotalSeconds, MOTION_SCENE_COUNTS,
  type MotionConfig, type MotionStyle, type MotionDuration,
} from '../../lib/motionGraphics';
import { buildAiVideoClips, videoGenModelsForTier, type VideoGenTier } from '../../lib/videoGen';
import type { AiVideoModel } from '../../lib/pollinations';
import AiVideoGenPicker from '../studio/AiVideoGenPicker';
import { MOTION_TEMPLATES, motionTemplateByKey, type MotionTemplate } from '../../data/motionTemplates';

// The Motion Graphics Studio (#3) — a real, working motion department.
//
// The canvas engine already films title cards into real, downloadable video
// (gradients, kinetic headlines, brand lockup, accents and a call-to-action
// end card). This module is the UI over that engine built for motion jobs:
// pick a modern template concept (glassmorphism, kinetic type, neon noir…),
// or start from a blank job type, then set the words, shape, pace and palette,
// watch the live canvas preview, and render an actual MP4/WebM — plus poster
// and contact-sheet stills. Templates are starting points: selecting one loads
// it into the editor and every field stays editable.
//
// The export films over either the FREE CANVAS (designed motion graphics, no
// model, no cost) or AI VIDEO clips generated by a free / paid model, with
// the same motion design layered on top. Honest about what it is either way:
// real, downloadable video from the browser — clips that fail to load fall
// back to the designed graphics, so nothing here silently fakes footage.

interface StyleMeta {
  key: MotionStyle;
  label: string;
  emoji: string;
  desc: string;
  defaults: { headline: string; subhead: string; cta: string; logoEmoji: string };
}

const STYLES: StyleMeta[] = [
  { key: 'logo-reveal', label: 'Logo Reveal', emoji: '✨', desc: 'The brand mark comes alive — scale and stroke onto a gradient.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'Every business, open to the world', cta: 'Find your next favourite', logoEmoji: '✦' } },
  { key: 'motion-poster', label: 'Motion Poster', emoji: '🎬', desc: 'Campaign art given life — headline, accent and a slow push-in.', defaults: { headline: 'RESTAURANT WEEK', subhead: 'Sep 1–30 · Lagos', cta: 'Get your tickets', logoEmoji: '🍽️' } },
  { key: 'kinetic-type', label: 'Kinetic Typography', emoji: '🔠', desc: 'One word per beat — the headline pops across four cards.', defaults: { headline: 'Make it local today', subhead: 'The NowOpen voice', cta: 'Join NowOpen Africa', logoEmoji: '✦' } },
  { key: 'lower-third', label: 'Lower Third', emoji: '📺', desc: 'Name + role caption card for interviews and panels.', defaults: { headline: 'Yemzo', subhead: 'Founder, NowOpen Africa', cta: '', logoEmoji: '👤' } },
  { key: 'countdown', label: 'Countdown', emoji: '⏱️', desc: '3…2…1…GO — suspense for a launch or a live stream.', defaults: { headline: 'GO!', subhead: 'The countdown is on', cta: 'Tune in now', logoEmoji: '🚀' } },
  { key: 'badge', label: 'Animated Badge', emoji: '🏷️', desc: 'A looping status stamp — Open Now, Verified, New.', defaults: { headline: 'OPEN NOW', subhead: 'NowOpen Africa', cta: 'Order ahead', logoEmoji: '✅' } },
  { key: 'reveal-title', label: 'Reveal Title', emoji: '🎞️', desc: 'A bold headline wipe for episodes and campaign headers.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'The platform for local business', cta: 'Launch yours', logoEmoji: '✦' } },
];

const ASPECTS: { key: RenderAspect; label: string; hint: string }[] = [
  { key: 'Vertical', label: 'Vertical', hint: 'Reels, TikTok, Status' },
  { key: 'Square', label: 'Square', hint: 'Feed posts' },
  { key: 'Landscape', label: 'Landscape', hint: 'YouTube, websites' },
];

const DURATIONS: { key: MotionDuration; label: string; hint: string }[] = [
  { key: 'short', label: 'Short', hint: '2s / card' },
  { key: 'medium', label: 'Medium', hint: '3s / card' },
  { key: 'long', label: 'Long', hint: '4s / card' },
];

/** Live, looping canvas preview of the motion brief — real frames, real timing. */
function MotionPreview({ opts, scenes }: { opts: SceneFrameOptions; scenes: DirectorScene[] }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const dims = RENDER_DIMENSIONS[opts.aspect];

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return; // no 2D context (jsdom) — nothing to preview
    // Preview at half resolution; the export renders full 1080p.
    canvas.width = Math.round(dims.width / 2);
    canvas.height = Math.round(dims.height / 2);
    const timeline = buildRenderTimeline(scenes, opts);
    let frame = 0;
    let raf = 0;
    let playing = true;
    const tick = () => {
      if (!playing) return;
      drawSceneFrame(ctx, canvas.width, canvas.height, opts, scenes, timeline, frame);
      frame = (frame + 1) % timeline.totalFrames;
      raf = window.requestAnimationFrame(tick);
    };
    raf = window.requestAnimationFrame(tick);
    return () => { playing = false; window.cancelAnimationFrame(raf); };
  }, [opts, scenes, dims.width, dims.height]);

  return <canvas ref={canvasRef} className="w-full max-w-md mx-auto rounded-xl border border-gray-200 dark:border-gray-700 bg-black" />;
}

function swatchStyle(palette: [string, string, string]): React.CSSProperties {
  return { background: `linear-gradient(135deg, ${palette[0]}, ${palette[1]} 55%, ${palette[2]})` };
}

export default function MotionGraphicsStudio() {
  const meta = STYLES[0];
  const [style, setStyle] = useState<MotionStyle>(meta.key);
  const [brand, setBrand] = useState('NowOpen');
  const [headline, setHeadline] = useState(meta.defaults.headline);
  const [subhead, setSubhead] = useState(meta.defaults.subhead);
  const [cta, setCta] = useState(meta.defaults.cta);
  const [logoEmoji, setLogoEmoji] = useState(meta.defaults.logoEmoji);
  const [aspect, setAspect] = useState<RenderAspect>('Vertical');
  const [duration, setDuration] = useState<MotionDuration>('medium');
  const [palette, setPalette] = useState<[string, string, string]>(RENDER_PALETTES[0]);

  const [rendering, setRendering] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  // Which gallery concept is loaded into the editor — null once the owner
  // customises anything (the brief becomes theirs).
  const [activeTemplate, setActiveTemplate] = useState<string | null>(null);

  // What the export films over: the free canvas (designed motion graphics,
  // no model) or generated AI video clips from a free / paid model.
  const [renderSource, setRenderSource] = useState<'canvas' | 'aivideo'>('canvas');
  const [genTier, setGenTier] = useState<VideoGenTier>('free');
  const [genModel, setGenModel] = useState<AiVideoModel>('wan');

  const clearTemplate = () => setActiveTemplate(null);

  const applyTemplate = (t: MotionTemplate) => {
    setStyle(t.preset.style);
    setHeadline(t.preset.headline);
    setSubhead(t.preset.subhead);
    setCta(t.preset.cta);
    setLogoEmoji(t.preset.logoEmoji);
    setAspect(t.preset.aspect);
    setDuration(t.preset.duration);
    setPalette(t.palette);
    setActiveTemplate(t.key);
    setError(null);
    toast.success(`${t.name} loaded — edit anything below.`);
  };

  const pickStyle = (s: StyleMeta) => {
    setStyle(s.key);
    setHeadline(s.defaults.headline);
    setSubhead(s.defaults.subhead);
    setCta(s.defaults.cta);
    setLogoEmoji(s.defaults.logoEmoji);
    clearTemplate();
    setError(null);
  };

  const cfg: MotionConfig = useMemo(
    () => ({ business: brand, headline, subhead, cta, logoEmoji, aspect, duration, style }),
    [brand, headline, subhead, cta, logoEmoji, aspect, duration, style],
  );

  const scenes = useMemo(() => motionScenesFromJob(cfg), [cfg]);
  const label = STYLES.find((s) => s.key === style)?.label ?? 'Motion';
  const opts: SceneFrameOptions = useMemo(
    () => ({
      businessName: brand || 'NowOpen',
      directionLabel: label,
      hook: headline,
      cta,
      aspect,
      logoEmoji: logoEmoji || '✦',
      palette,
      scenesCount: scenes.length,
    }),
    [brand, label, headline, cta, aspect, logoEmoji, palette, scenes.length],
  );

  const seconds = motionTotalSeconds(cfg);

  const downloadVideo = async () => {
    setRendering(true);
    setError(null);
    setProgress(0);
    try {
      let footage;
      if (renderSource === 'aivideo') {
        footage = buildAiVideoClips({
          businessName: brand || 'NowOpen',
          industryLabel: 'brand',
          directionLabel: label,
          scenes,
          model: genModel,
          aspect,
        });
      }
      const result = await renderVideo(
        { ...opts, footage, footageEnabled: renderSource === 'aivideo' },
        scenes,
        (p) => setProgress(p),
      );
      const url = URL.createObjectURL(result.blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `motion-${style}-${aspect.toLowerCase()}.${result.mimeType.includes('mp4') ? 'mp4' : 'webm'}`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not render the video.');
    } finally {
      setRendering(false);
      setProgress(0);
    }
  };

  const downloadStill = useCallback((kind: 'poster' | 'sheet') => {
    const still = kind === 'poster' ? renderPoster(opts, scenes) : renderContactSheet(opts, scenes);
    if (!still) { toast.error('Still export is not supported in this browser.'); return; }
    const a = document.createElement('a');
    a.href = still.dataUrl;
    a.download = `motion-${style}-${kind}.png`;
    a.click();
    toast.success(`${kind === 'poster' ? 'Poster' : 'Contact sheet'} exported (PNG).`);
  }, [opts, scenes, style]);

  return (
    <div className="space-y-5">
      {/* Modern template gallery */}
      <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <LayoutTemplate size={15} className="text-purple-500" /> Modern template gallery
            </h3>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5">
              The latest motion design concepts, ready to film. Pick one to load it into the editor — every field stays editable.
            </p>
          </div>
          {activeTemplate && (
            <button onClick={clearTemplate} className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
              <X size={12} /> Custom brief
            </button>
          )}
        </div>

        <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {MOTION_TEMPLATES.map((t) => {
            const active = activeTemplate === t.key;
            return (
              <button key={t.key} onClick={() => applyTemplate(t)} aria-pressed={active} title={`${t.name} — ${t.concept}`}
                className={`text-left rounded-xl border-2 transition overflow-hidden ${active ? 'border-purple-500 ring-2 ring-purple-300' : 'border-gray-200 dark:border-gray-700 hover:border-purple-300'}`}>
                <div className="relative h-20" style={swatchStyle(t.palette)}>
                  <span className="absolute inset-0 flex items-center justify-center text-3xl drop-shadow">{t.emoji}</span>
                  {active && (
                    <span className="absolute top-1.5 right-1.5 w-5 h-5 rounded-full bg-purple-600 text-white flex items-center justify-center">
                      <Check size={12} />
                    </span>
                  )}
                </div>
                <div className="p-2.5">
                  <span className="block text-xs font-bold text-gray-900 dark:text-white">{t.name}</span>
                  <p className="mt-0.5 text-[10px] leading-snug text-gray-500 dark:text-gray-400 line-clamp-2">{t.concept}</p>
                  <div className="mt-1.5 flex flex-wrap gap-1">
                    {t.tags.map((tag) => (
                      <span key={tag} className="px-1.5 py-0.5 rounded-md bg-purple-50 dark:bg-purple-900/30 text-[9px] font-bold text-purple-600 dark:text-purple-300">{tag}</span>
                    ))}
                  </div>
                </div>
              </button>
            );
          })}
        </div>

        {activeTemplate && (
          <p role="status" className="mt-3 text-[11px] text-purple-700 dark:text-purple-300">
            Editing {motionTemplateByKey(activeTemplate)?.name} — tweak the words, shape, pace and palette below; the preview updates live.
          </p>
        )}
      </section>

      {/* Style picker */}
      <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
        <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
          <Film size={15} className="text-purple-500" /> What are you animating?
        </h3>
        <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
          {STYLES.map((s) => (
            <button key={s.key} onClick={() => pickStyle(s)} aria-pressed={style === s.key}
              className={`text-left p-3 rounded-xl border transition ${style === s.key ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20' : 'border-gray-200 dark:border-gray-700 hover:border-purple-300'}`}>
              <span className="text-xl">{s.emoji}</span>
              <span className="block mt-1 text-xs font-bold text-gray-900 dark:text-white">{s.label}</span>
              <span className="block mt-0.5 text-[10px] leading-snug text-gray-500 dark:text-gray-400">{s.desc}</span>
            </button>
          ))}
        </div>
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Editor */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
            <Sparkles size={15} className="text-purple-500" /> Your motion brief
          </h3>

          <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Brand lockup</span>
              <input value={brand} onChange={(e) => { setBrand(e.target.value); clearTemplate(); }} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Mark emoji</span>
              <input value={logoEmoji} onChange={(e) => { setLogoEmoji(e.target.value); clearTemplate(); }} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block sm:col-span-2">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Headline</span>
              <input value={headline} onChange={(e) => { setHeadline(e.target.value); clearTemplate(); }} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block sm:col-span-2">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Sub-line (voiceover strip)</span>
              <input value={subhead} onChange={(e) => { setSubhead(e.target.value); clearTemplate(); }} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block sm:col-span-2">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Call to action (end card)</span>
              <input value={cta} onChange={(e) => { setCta(e.target.value); clearTemplate(); }} className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
          </div>

          <div className="mt-4 flex flex-wrap items-center gap-2">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Shape</span>
            {ASPECTS.map((a) => (
              <button key={a.key} onClick={() => { setAspect(a.key); clearTemplate(); }} aria-pressed={aspect === a.key}
                className={`px-3 py-2 rounded-lg text-xs font-semibold transition ${aspect === a.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                {a.label}<span className="ml-1.5 font-normal opacity-70">{a.hint}</span>
              </button>
            ))}
          </div>

          <div className="mt-3 flex flex-wrap items-center gap-2">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Pace</span>
            {DURATIONS.map((d) => (
              <button key={d.key} onClick={() => { setDuration(d.key); clearTemplate(); }} aria-pressed={duration === d.key}
                className={`px-3 py-2 rounded-lg text-xs font-semibold transition ${duration === d.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                {d.label}<span className="ml-1.5 font-normal opacity-70">{d.hint}</span>
              </button>
            ))}
          </div>

          <div className="mt-3">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Palette</span>
            <div className="mt-1.5 flex flex-wrap gap-2">
              {RENDER_PALETTES.map((p, i) => (
                <button key={i} onClick={() => { setPalette(p); clearTemplate(); }} aria-pressed={palette === p} title={p.join(' → ')}
                  className={`w-8 h-8 rounded-lg border-2 transition ${palette === p ? 'border-purple-600 ring-2 ring-purple-300' : 'border-transparent'}`}
                  style={swatchStyle(p)} />
              ))}
            </div>
          </div>
        </section>

        {/* Preview + storyboard */}
        <div className="space-y-5 min-w-0">
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <div className="flex items-center justify-between gap-2">
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <Film size={15} className="text-purple-500" /> Live preview
              </h3>
              <span className="text-[11px] font-semibold text-gray-400">
                {MOTION_SCENE_COUNTS[style]} cards · {seconds}s · {RENDER_DIMENSIONS[aspect].width}×{RENDER_DIMENSIONS[aspect].height}
              </span>
            </div>
            <div className="mt-3">
              <MotionPreview opts={opts} scenes={scenes} />
            </div>
          </section>

          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
            <div className="p-4 border-b border-gray-100 dark:border-gray-700">
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <ListVideo size={15} className="text-purple-500" /> Storyboard
              </h3>
            </div>
            <ol className="divide-y divide-gray-100 dark:divide-gray-700">
              {scenes.map((s, i) => (
                <li key={s.id} className="flex gap-3 p-3.5">
                  <span className="shrink-0 w-7 h-7 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 text-xs font-bold flex items-center justify-center">{i + 1}</span>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-gray-900 dark:text-white">{s.text}</p>
                    <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 italic">“{s.voiceover}”</p>
                  </div>
                  <span className="shrink-0 text-[11px] font-semibold text-gray-400 tabular-nums">{s.seconds}s</span>
                </li>
              ))}
            </ol>
          </section>
        </div>
      </div>

      {/* Export */}
      <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="min-w-0">
            <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <Film size={15} className="text-purple-500" /> Export
            </h3>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 max-w-lg">
              {renderSource === 'canvas'
                ? 'Films the motion graphic on the free browser canvas — real, downloadable video with captions, motion and the end card. No model, no cost.'
                : 'Films your motion design over generated AI video clips from a free or paid model — with captions, motion and the end card on top.'}
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button onClick={() => downloadStill('poster')} disabled={rendering}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
              <ImageIcon size={13} /> Poster PNG
            </button>
            <button onClick={() => downloadStill('sheet')} disabled={rendering}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
              <LayoutGrid size={13} /> Contact sheet
            </button>
            <button onClick={downloadVideo} disabled={rendering}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 disabled:opacity-60 text-white text-sm font-semibold transition">
              {rendering ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
              {rendering ? `Filming ${Math.round(progress * 100)}%` : `Render ${seconds}s video`}
            </button>
          </div>
        </div>

        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 dark:border-gray-700 p-3">
          <div className="flex items-center gap-1.5">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Render source</span>
            <div className="ml-1 flex rounded-lg bg-gray-100 dark:bg-gray-800 p-0.5">
              {([
                { key: 'canvas', label: 'Free canvas' },
                { key: 'aivideo', label: 'AI video gen' },
              ] as const).map((o) => (
                <button key={o.key} type="button" onClick={() => setRenderSource(o.key)} aria-pressed={renderSource === o.key}
                  className={`px-3 py-1.5 rounded-md text-xs font-bold transition ${renderSource === o.key ? 'bg-purple-600 text-white shadow-sm' : 'text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-gray-700'}`}>
                  {o.label}
                </button>
              ))}
            </div>
          </div>
          {renderSource === 'aivideo' ? (
            <span className="text-[11px] text-gray-500 dark:text-gray-400">Designed motion graphics + {genTier === 'free' ? 'free' : 'paid'} AI clips underneath.</span>
          ) : (
            <span className="text-[11px] text-gray-500 dark:text-gray-400">100% free — the canvas is the renderer.</span>
          )}
        </div>

        {renderSource === 'aivideo' && (
          <div className="mt-3">
            <AiVideoGenPicker
              tier={genTier}
              onTier={(t) => {
                setGenTier(t);
                setGenModel(videoGenModelsForTier(t)[0].key);
              }}
              model={genModel}
              onModel={setGenModel}
            />
          </div>
        )}

        {rendering && (
          <div className="mt-3 h-1.5 rounded-full bg-gray-100 dark:bg-gray-700 overflow-hidden">
            <div className="h-full bg-purple-600 transition-[width] duration-200" style={{ width: `${Math.round(progress * 100)}%` }} />
          </div>
        )}

        {error && <p role="alert" className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>}
      </section>
    </div>
  );
}
