import { useCallback, useEffect, useMemo, useRef, useState, forwardRef, useImperativeHandle } from 'react';
import toast from 'react-hot-toast';
import {
  Film, Download, ImageIcon, LayoutGrid, Loader2, Sparkles, ListVideo,
  LayoutTemplate, Check, Plus, Copy, Trash2, FolderOpen, Wand2, Clapperboard,
  Layers, ChevronUp, ChevronDown, ArrowLeft, Undo2, Redo2, Play, Pause, Save,
  Type, Music, Palette, Shapes, Scissors, RotateCcw, Timer, GripVertical,
  Eye, EyeOff,
} from 'lucide-react';
import type { DirectorScene, TextElementStyle } from '../../lib/creativeDirector';
import {
  renderVideo, renderPoster, renderContactSheet, drawSceneFrame, buildRenderTimeline,
  sceneElementRegions, RENDER_DIMENSIONS, RENDER_PALETTES,
  createBackgroundVideo, createBackgroundImage, MOTION_FONT_DEFAULT,
  type RenderAspect, type SceneFrameOptions, type MotionTreatment,
  type SceneElementKey, type MotionLayer,
} from '../../lib/renderVideo';
import {
  motionScenesFromJob, applyMotionTimeline, emptyMotionTimeline,
  timelineMoveClip, timelineSetSeconds,
  timelineDuplicate, timelineSplit, timelineRemove,
  timelineSetElement, timelineResetElement, timelineAppendClip,
  CLIP_SECONDS_MIN, CLIP_SECONDS_MAX, MOTION_SCENE_COUNTS,
  type MotionConfig, type MotionStyle, type MotionDuration, type MotionTimeline,
} from '../../lib/motionGraphics';
import { resolveAiVideoClips, videoGenModelsForTier } from '../../lib/videoGen';
import AiVideoGenPicker from '../studio/AiVideoGenPicker';
import { MOTION_TEMPLATES, motionTemplateByKey, type MotionTemplate } from '../../data/motionTemplates';
import { pickPreviewVoice } from '../../lib/voicePreview';
import {
  blankMotionProject, motionProjectFromTemplate, motionProjectFromPrompt,
  saveMotionProject, deleteMotionProject, duplicateMotionProject, loadMotionProjects,
  MOTION_PROJECT_STATUSES, MOTION_PROJECT_STATUS_LABELS,
  type MotionProject, type MotionProjectStatus,
} from '../../lib/motionProject';

// Motion Studio (#3) — one editable project, three ways in.
//
// Quick Create  → pick a format and a modern template; a full MotionProject is born.
// Studio        → the editor over that project: words, shape, pace, palette, live
//                 canvas preview, storyboard and a real MP4/WebM export.
// AI Director   → describe the motion in plain English; the local rule-based
//                 director designs a full project (no cloud model, no wait).
//
// Every mode writes the SAME MotionProject (src/lib/motionProject.ts), persisted
// under nowopen_motion_projects, so anything made or generated stays editable:
// change the words, swap the palette, resize for another format and render again.
//
// The export films over either the FREE CANVAS (designed motion graphics, no
// model, no cost) or AI VIDEO clips generated by a free / paid model, with the
// same motion design layered on top. Honest about what it is either way: real,
// downloadable video from the browser — clips that fail to load fall back to
// the designed graphics, so nothing here silently fakes footage.

type Mode = 'quick' | 'studio' | 'ai';

const MODES: { key: Mode; label: string; emoji: string; blurb: string }[] = [
  { key: 'quick', label: 'Quick Create', emoji: '⚡', blurb: 'Pick a format and a modern template — a full project is born in one click.' },
  { key: 'studio', label: 'Studio', emoji: '🎛️', blurb: 'The full editor: words, shape, pace, palette, live preview and export.' },
  { key: 'ai', label: 'AI Director', emoji: '🪄', blurb: 'Describe it in plain English — the local director designs a full project for you.' },
];

const EXAMPLE_PROMPTS = [
  'A countdown reel for a Lagos coffee shop opening this Friday',
  '20% off this weekend — a promotion for a restaurant in Abuja',
  'Billboard for Ember Hotel — grand opening, luxury rooms',
  'A 30 second YouTube opener for a fashion boutique',
];

interface StyleMeta {
  key: MotionStyle;
  label: string;
  emoji: string;
  desc: string;
  defaults: { headline: string; subhead: string; cta: string; logoEmoji: string };
}

const STYLES: StyleMeta[] = [
  { key: 'logo-reveal', label: 'Logo Reveal', emoji: '✨', desc: 'The brand mark comes alive — scale and stroke onto a gradient.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'Every business, open to the world', cta: 'Find your next favourite', logoEmoji: '✦' } },
  { key: 'motion-poster', label: 'Motion Poster', emoji: '🎬', desc: 'Campaign art given life — headline, accent and a slow push-in.', defaults: { headline: 'RESTAURANT WEEK', subhead: 'Sep 1–30 · Lagos', cta: 'Get your tickets', logoEmoji: '🍽️' } },
  { key: 'kinetic-type', label: 'Kinetic Typography', emoji: '🔠', desc: 'One word per beat — the headline pops across four cards.', defaults: { headline: 'Make it local today', subhead: 'The NowOpen voice', cta: 'Join NowOpen Africa', logoEmoji: '✦' } },
  { key: 'lower-third', label: 'Lower Third', emoji: '📺', desc: 'Name + role caption card for interviews and panels.', defaults: { headline: 'Yemzo', subhead: 'Founder, NowOpen Africa', cta: '', logoEmoji: '👤' } },
  { key: 'countdown', label: 'Countdown', emoji: '⏱️', desc: '3…2…1…GO — suspense for a launch or a live stream.', defaults: { headline: 'GO!', subhead: 'The countdown is on', cta: 'Tune in now', logoEmoji: '🚀' } },
  { key: 'badge', label: 'Animated Badge', emoji: '🏷️', desc: 'A looping status stamp — Open Now, Verified, New.', defaults: { headline: 'OPEN NOW', subhead: 'NowOpen Africa', cta: 'Order ahead', logoEmoji: '✅' } },
  { key: 'reveal-title', label: 'Reveal Title', emoji: '🎞️', desc: 'A bold headline wipe for episodes and campaign headers.', defaults: { headline: 'NOWOPEN AFRICA', subhead: 'The platform for local business', cta: 'Launch yours', logoEmoji: '✦' } },
  { key: 'billboard-led', label: 'Billboard LED', emoji: '🪧', desc: 'Roadside LED energy — neon glow, scanlines and a scrolling marquee.', defaults: { headline: 'GRAND OPENING', subhead: 'Now open for business', cta: 'Come see us today', logoEmoji: '🪧' } },
  { key: 'premium-keyart', label: 'Apple Key Art', emoji: '🍾', desc: 'Apple TV standard — one elegant title, soft light, generous space.', defaults: { headline: 'THE PREMIUM DROP', subhead: 'Experience it first', cta: 'Reserve your seat', logoEmoji: '🍾' } },
  { key: 'glassmorphic', label: 'Glassmorphic', emoji: '🪟', desc: 'Frosted glass panels over soft colour — modern and clean.', defaults: { headline: 'OPEN FOR BUSINESS', subhead: 'Modern, clear, welcoming', cta: 'Visit us today', logoEmoji: '🪟' } },
  { key: 'isometric-3d', label: 'Isometric 3D', emoji: '📐', desc: 'Layered shapes with real parallax depth — the camera moves.', defaults: { headline: 'NEW DROP', subhead: 'Depth you can feel', cta: 'Shop the drop', logoEmoji: '📐' } },
];

/** The render engine's treatment for each motion style (default = flat look). */
const TREATMENT_FOR_STYLE: Record<MotionStyle, MotionTreatment> = {
  'logo-reveal': 'default',
  'motion-poster': 'default',
  'kinetic-type': 'default',
  'lower-third': 'default',
  countdown: 'default',
  badge: 'default',
  'reveal-title': 'default',
  'billboard-led': 'led',
  'premium-keyart': 'premium',
  glassmorphic: 'glass',
  'isometric-3d': '3d',
};

const ELEMENT_LABELS: Record<SceneElementKey, string> = {
  brand: 'Brand lockup',
  title: 'Headline',
  subline: 'Sub-line',
  cta: 'Call to action',
};

const ELEMENT_KEYS: SceneElementKey[] = ['brand', 'title', 'subline', 'cta'];

const ELEMENT_COLORS: { swatch: string; value?: string }[] = [
  { swatch: '#ffffff' },
  { swatch: '#000000' },
  { swatch: '#f8fafc' },
  { swatch: '#fde047' },
  { swatch: '#4ade80' },
  { swatch: '#22d3ee' },
  { swatch: '#60a5fa' },
  { swatch: '#a78bfa' },
  { swatch: '#f472b6' },
  { swatch: '#fb7185' },
  { swatch: '#fb923c' },
  { swatch: '#facc15' },
];

const FONT_FAMILY_OPTIONS: { label: string; value?: string }[] = [
  { label: 'NowOpen Africa' },
  { label: 'Inter', value: 'Inter, system-ui, sans-serif' },
  { label: 'Serif', value: 'Georgia, "Times New Roman", serif' },
  { label: 'Sans', value: 'Impact, "Arial Black", sans-serif' },
  { label: 'Mono', value: '"Courier New", monospace' },
];

const WEIGHT_OPTIONS: { label: string; value?: number }[] = [
  { label: 'Regular', value: 400 },
  { label: 'Medium', value: 500 },
  { label: 'Semi-bold', value: 600 },
  { label: 'Bold', value: 700 },
  { label: 'Heavy', value: 900 },
];

/** The designed (pre-customisation) caption for an element of a scene. */
function briefTextFor(scene: DirectorScene, brief: MotionConfig): string {
  switch (scene.text) {
    case 'brand': return brief.business ?? '';
    case 'title': return brief.headline ?? '';
    case 'subline': return scene.voiceover ?? '';
    case 'cta': return brief.cta ?? '';
    default: return '';
  }
}

const ASPECTS: { key: RenderAspect; label: string; hint: string }[] = [
  { key: 'Vertical', label: 'Vertical', hint: 'Reels, TikTok, Status' },
  { key: 'Square', label: 'Square', hint: 'Feed posts' },
  { key: 'Landscape', label: 'Landscape', hint: 'YouTube, websites' },
];

const DURATIONS: { key: MotionDuration; label: string; hint: string }[] = [
  { key: 'short', label: 'Short', hint: '2s / card' },
  { key: 'medium', label: 'Medium', hint: '3s / card' },
  { key: 'long', label: 'Long', hint: '4s / card' },
  { key: 'extended', label: 'Extended', hint: '5s / card' },
  { key: 'cinematic', label: 'Cinematic', hint: '6s / card' },
];

function timeAgo(iso: string): string {
  const s = Math.max(1, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (s < 60) return `${s}s ago`;
  const m = Math.round(s / 60);
  if (m < 60) return `${m}m ago`;
  return `${Math.round(m / 60)}h ago`;
}

/**
 * Live, looping canvas preview of the motion brief — real frames, real timing.
 * The parent owns the transport: when `playing` is true it loops and reports
 * progress so the timeline marker can follow; when paused it freezes on the
 * `playhead` fraction (or the last scene). In edit mode the loop freezes on a
 * chosen scene, the clickable layout elements are outlined; dragging one moves
 * it (reporting the normalised delta) and clicking one without a drag reports
 * the picked element so the parent can open an inline editor.
 */
function MotionPreview({
  opts, scenes, editMode, sceneIndex, playing, playhead, onProgress, onPick, onMoveElement, className,
}: {
  opts: SceneFrameOptions;
  scenes: DirectorScene[];
  editMode: boolean;
  sceneIndex: number;
  playing: boolean;
  playhead: number | null;
  onProgress?: (fraction: number) => void;
  onPick?: (key: SceneElementKey) => void;
  /** Called while dragging an outlined element, with the cumulative normalised delta. */
  onMoveElement?: (key: SceneElementKey, dx: number, dy: number) => void;
  className?: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const dragRef = useRef<{ key: SceneElementKey; startX: number; startY: number; dx: number; dy: number; moved: boolean } | null>(null);
  const dims = RENDER_DIMENSIONS[opts.aspect];
  // Keep the latest progress callback without re-running the drawing loop.
  const onProgressRef = useRef(onProgress);
  onProgressRef.current = onProgress;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return; // no 2D context (jsdom) — nothing to preview
    // Preview at half resolution; the export renders full 1080p.
    canvas.width = Math.round(dims.width / 2);
    canvas.height = Math.round(dims.height / 2);
    const cw = canvas.width;
    const ch = canvas.height;
    const timeline = buildRenderTimeline(scenes, opts);
    const totalFrames = Math.max(1, timeline.totalFrames);
    let frame = 0;
    let raf = 0;

    // Warm the brand webfont so captions render in it rather than the fallback.
    if (typeof document !== 'undefined' && typeof document.fonts !== 'undefined' && document.fonts.load) {
      void document.fonts.load(`700 16px ${MOTION_FONT_DEFAULT}`).catch(() => { /* fallback stays in the stack */ });
    }

    // Keep uploaded video layers animating behind the captions.
    (opts.layers ?? [])
      .filter((l) => l.kind === 'video')
      .forEach((l) => {
        if (!l.video) return;
        const p = l.video.play();
        if (p) p.catch(() => { /* autoplay-blocked — the frame draws whatever is ready */ });
      });

    const paintRegions = (si: number) => {
      const regions = sceneElementRegions(opts, scenes[si] ?? scenes[0], si);
      ctx.save();
      ctx.lineWidth = 2;
      ctx.setLineDash([6, 4]);
      for (const r of regions) {
        ctx.strokeStyle = 'rgba(244,63,94,0.9)';
        ctx.fillStyle = 'rgba(244,63,94,0.1)';
        ctx.beginPath();
        ctx.rect(r.x * cw, r.y * ch, r.w * cw, r.h * ch);
        ctx.fill();
        ctx.stroke();
        ctx.fillStyle = 'rgba(244,63,94,0.95)';
        ctx.font = '700 13px system-ui, sans-serif';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'top';
        ctx.fillText('✏️', r.x * cw + 6, r.y * ch + 6);
      }
      ctx.restore();
    };

    if (editMode) {
      // Frozen frame: the scene under edit, outlined and ready to click.
      const timing = timeline.scenes[Math.min(sceneIndex, timeline.scenes.length - 1)] ?? timeline.scenes[0];
      drawSceneFrame(ctx, cw, ch, opts, scenes, timeline, timing.startFrame);
      paintRegions(timing.index);
      return () => window.cancelAnimationFrame(raf);
    }

    const startFrame = playhead != null ? Math.round(playhead * (totalFrames - 1)) : 0;

    if (!playing) {
      // Paused: one frozen frame at the playhead position.
      drawSceneFrame(ctx, cw, ch, opts, scenes, timeline, startFrame);
      return () => window.cancelAnimationFrame(raf);
    }

    frame = startFrame;
    const tick = () => {
      drawSceneFrame(ctx, cw, ch, opts, scenes, timeline, frame);
      onProgressRef.current?.(totalFrames > 1 ? frame / (totalFrames - 1) : 0);
      frame = (frame + 1) % totalFrames;
      raf = window.requestAnimationFrame(tick);
    };
    raf = window.requestAnimationFrame(tick);
    return () => { window.cancelAnimationFrame(raf); };
  }, [opts, scenes, dims.width, dims.height, editMode, sceneIndex, playing, playhead]);

  const regionAt = (e: React.PointerEvent<HTMLCanvasElement>): SceneElementKey | null => {
    const canvas = canvasRef.current;
    if (!canvas) return null;
    const rect = canvas.getBoundingClientRect();
    if (rect.width <= 0 || rect.height <= 0) return null;
    const nx = (e.clientX - rect.left) / rect.width;
    const ny = (e.clientY - rect.top) / rect.height;
    const idx = Math.min(sceneIndex, scenes.length - 1);
    const scene = scenes[idx];
    if (!scene) return null;
    return sceneElementRegions(opts, scene, idx).find(
      (r) => nx >= r.x && nx <= r.x + r.w && ny >= r.y && ny <= r.y + r.h,
    )?.key ?? null;
  };

  const onPointerDown = (e: React.PointerEvent<HTMLCanvasElement>) => {
    if (!editMode) return;
    const key = regionAt(e);
    if (!key) return;
    const scene = scenes[Math.min(sceneIndex, scenes.length - 1)];
    const style = scene?.elements?.[key] ?? {};
    dragRef.current = { key, startX: e.clientX, startY: e.clientY, dx: style.dx ?? 0, dy: style.dy ?? 0, moved: false };
    e.currentTarget.setPointerCapture(e.pointerId);
  };

  const onPointerMove = (e: React.PointerEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (canvas) canvas.style.cursor = editMode ? 'crosshair' : 'default';
    const drag = dragRef.current;
    if (!drag || !canvas) return;
    if (!editMode) return;
    const rect = canvas.getBoundingClientRect();
    if (rect.width <= 0 || rect.height <= 0) return;
    const nw = (e.clientX - drag.startX) / rect.width;
    const nh = (e.clientY - drag.startY) / rect.height;
    if (!drag.moved && Math.abs(nw) + Math.abs(nh) < 0.02) return; // still a click
    drag.moved = true;
    const nextDx = Math.max(-0.5, Math.min(0.5, drag.dx + nw));
    const nextDy = Math.max(-0.5, Math.min(0.5, drag.dy + nh));
    if (onMoveElement) onMoveElement(drag.key, nextDx, nextDy);
  };

  const onPointerUp = () => {
    const drag = dragRef.current;
    if (!drag) return;
    dragRef.current = null;
    if (drag.moved) return;
    if (onPick) onPick(drag.key);
  };

  return (
    <canvas
      ref={canvasRef}
      onPointerMove={onPointerMove}
      onPointerDown={onPointerDown}
      onPointerUp={onPointerUp}
      onPointerCancel={() => { dragRef.current = null; }}
      className={className ?? 'w-full max-w-md mx-auto rounded-xl border border-gray-200 dark:border-gray-700 bg-black'}
    />
  );
}

/**
 * The editor timeline — CapCut-style bottom strip: transport, time ruler with a
 * scrubbing playhead, and draggable text clips (reorder via drag, trim via the
 * edge handles, split / duplicate / remove via the buttons). The background and
 * voiceover tracks are drawn full-length so the composition reads at a glance.
 */
const MotionTimeline = forwardRef<{ setMarker: (fraction: number) => void }, {
  scenes: DirectorScene[];
  selected: number;
  playing: boolean;
  totalSeconds: number;
  onSelect: (index: number) => void;
  onScrub: (fraction: number, sceneIndex: number) => void;
  onPlayPause: () => void;
  onMove: (fromIndex: number, toIndex: number) => void;
  onTrim: (id: string, seconds: number) => void;
  onReset: () => void;
}>(function MotionTimelineInner({
  scenes, selected, playing, totalSeconds,
  onSelect, onScrub, onPlayPause, onMove, onTrim, onReset,
}, ref) {
  const trackRef = useRef<HTMLDivElement>(null);
  const [marker, setMarker] = useState(0);
  const [trimming, setTrimming] = useState<{ id: string; side: 'l' | 'r' } | null>(null);
  const trimSession = useRef<{ id: string; side: 'l' | 'r'; clipStartFrac: number; clipEndFrac: number } | null>(null);
  const dragFrom = useRef<number | null>(null);
  const scrubbing = useRef(false);

  useImperativeHandle(ref, () => ({
    setMarker: (f: number) => setMarker(Math.max(0, Math.min(1, f))),
  }), []);

  const safeTotal = totalSeconds > 0 ? totalSeconds : 1;
  const markerPct = `${Math.round(marker * 100)}%`;

  const sceneIndexAt = (f: number): number => {
    if (scenes.length === 0) return 0;
    const target = f * safeTotal;
    let acc = 0;
    for (let i = 0; i < scenes.length; i += 1) {
      acc += scenes[i].seconds;
      if (target < acc) return i;
    }
    return scenes.length - 1;
  };

  const scrubTo = (clientX: number) => {
    const el = trackRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const f = rect.width > 0 ? Math.max(0, Math.min(1, (clientX - rect.left) / rect.width)) : 0;
    setMarker(f);
    onScrub(f, sceneIndexAt(f));
  };

  const beginTrim = (id: string, side: 'l' | 'r', e: React.PointerEvent) => {
    e.stopPropagation();
    e.preventDefault();
    const scene = scenes.find((s) => s.id === id);
    const idx = scenes.findIndex((s) => s.id === id);
    if (!scene || idx < 0) return;
    const startFrac = scenes.slice(0, idx).reduce((a, s) => a + s.seconds, 0) / safeTotal;
    trimSession.current = { id, side, clipStartFrac: startFrac, clipEndFrac: startFrac + scene.seconds / safeTotal };
    setTrimming({ id, side });
  };

  useEffect(() => {
    if (!trimming) return;
    const move = (ev: PointerEvent) => {
      const s = trimSession.current;
      const el = trackRef.current;
      if (!s || !el) return;
      const rect = el.getBoundingClientRect();
      const f = rect.width > 0 ? Math.max(0, Math.min(1, (ev.clientX - rect.left) / rect.width)) : 0;
      const seconds = s.side === 'l'
        ? (s.clipEndFrac - f) * safeTotal
        : (f - s.clipStartFrac) * safeTotal;
      onTrim(s.id, Math.max(CLIP_SECONDS_MIN, seconds));
    };
    const up = () => { setTrimming(null); trimSession.current = null; };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', up);
    return () => {
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', up);
    };
  }, [trimming, safeTotal, onTrim]);

  const secondsPerTick = Math.max(1, Math.ceil(safeTotal / 10));
  const ticks: number[] = [];
  for (let t = 0; t <= Math.ceil(safeTotal); t += secondsPerTick) ticks.push(t);

  return (
    <div className="border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 select-none">
      {/* Transport */}
      <div className="flex items-center gap-2 px-3 py-1.5">
        <button onClick={onPlayPause} title={playing ? 'Pause preview' : 'Play preview'}
          className="w-8 h-8 rounded-lg bg-purple-600 hover:bg-purple-700 text-white flex items-center justify-center transition">
          {playing ? <Pause size={15} /> : <Play size={15} className="ml-0.5" />}
        </button>
        <span className="text-[11px] font-semibold text-gray-700 dark:text-gray-200 tabular-nums">
          {(marker * safeTotal).toFixed(1)}s / {safeTotal.toFixed(1)}s
        </span>
        <span className="ml-auto hidden sm:inline text-[10px] text-gray-400">
          {scenes.length} clips · drag to reorder · drag clip edges to trim
        </span>
        <button onClick={onReset} title="Reset the timeline to the designed order"
          className="inline-flex items-center gap-1 px-2 py-1.5 rounded-lg text-[11px] font-semibold border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-300 hover:border-purple-300 transition">
          <RotateCcw size={12} /> Reset timeline
        </button>
      </div>

      <div className="relative px-3 pb-2">
        {/* Ruler + playhead (also the scrub surface for the whole strip) */}
        <div
          ref={trackRef}
          onPointerDown={(e) => {
            scrubbing.current = true;
            e.currentTarget.setPointerCapture(e.pointerId);
            scrubTo(e.clientX);
          }}
          onPointerMove={(e) => { if (scrubbing.current) scrubTo(e.clientX); }}
          onPointerUp={() => { scrubbing.current = false; }}
          onPointerCancel={() => { scrubbing.current = false; }}
          className="relative h-6 border-b border-gray-200 dark:border-gray-700 cursor-col-resize"
        >
          <div className="absolute inset-x-0 top-1/2 h-px bg-gray-200 dark:bg-gray-700" />
          {ticks.map((t) => (
            <span key={t} className="absolute top-1 -translate-x-1/2 text-[9px] text-gray-400 tabular-nums"
              style={{ left: `${(t / Math.max(1, Math.ceil(safeTotal))) * 100}%` }}>
              {t}
            </span>
          ))}
        </div>

        {/* Tracks */}
        <div className="space-y-1 py-1.5">
          {/* TEXT clips */}
          <div className="flex items-stretch gap-1.5 h-12">
            <span className="w-14 shrink-0 flex items-center text-[9px] font-bold uppercase tracking-wide text-gray-400">Text</span>
            <div className="relative flex-1">
              {scenes.map((s, i) => {
                const startFrac = scenes.slice(0, i).reduce((a, x) => a + x.seconds, 0) / safeTotal;
                const widthPct = (s.seconds / safeTotal) * 100;
                const selectedClip = selected === i && !trimming;
                return (
                  <div
                    key={s.id}
                    draggable
                    onDragStart={() => { dragFrom.current = i; }}
                    onDragOver={(e) => {
                      e.preventDefault();
                      if (dragFrom.current != null && dragFrom.current !== i) {
                        onMove(dragFrom.current, i);
                        dragFrom.current = i;
                      }
                    }}
                    onDrop={() => { dragFrom.current = null; }}
                    onDragEnd={() => { dragFrom.current = null; }}
                    onClick={() => onSelect(i)}
                    title={`${s.text} — ${s.seconds}s. Drag to reorder, drag the edges to trim.`}
                    className={`absolute top-0 bottom-0 rounded-lg border px-1.5 py-1 cursor-grab active:cursor-grabbing transition-colors ${selectedClip
                      ? 'border-purple-600 bg-purple-600/90 text-white shadow-md z-10'
                      : 'border-purple-300 dark:border-purple-700 bg-purple-100 dark:bg-purple-900/40 text-purple-900 dark:text-purple-100 hover:border-purple-500'}`}
                    style={{ left: `${startFrac * 100}%`, width: `${Math.max(2, widthPct)}%` }}
                  >
                    <div className="flex items-center gap-1 min-w-0 h-full">
                      <GripVertical size={12} className="shrink-0 opacity-60" />
                      <span className="shrink-0 text-[9px] font-bold tabular-nums">{i + 1}</span>
                      <span className="min-w-0 flex-1 truncate text-[10px] font-semibold">{s.text}</span>
                      <span className="shrink-0 text-[9px] font-bold tabular-nums opacity-80">{s.seconds}s</span>
                    </div>
                    {/* Trim handles */}
                    <button
                      title="Trim start"
                      onPointerDown={(e) => beginTrim(s.id, 'l', e)}
                      onClick={(e) => e.stopPropagation()}
                      className={`absolute left-0 top-0 bottom-0 w-1.5 cursor-col-resize rounded-l ${trimming?.id === s.id && trimming.side === 'l' ? 'bg-rose-500' : 'bg-transparent hover:bg-rose-400'}`}
                    />
                    <button
                      title="Trim end"
                      onPointerDown={(e) => beginTrim(s.id, 'r', e)}
                      onClick={(e) => e.stopPropagation()}
                      className={`absolute right-0 top-0 bottom-0 w-1.5 cursor-col-resize rounded-r ${trimming?.id === s.id && trimming.side === 'r' ? 'bg-rose-500' : 'bg-transparent hover:bg-rose-400'}`}
                    />
                  </div>
                );
              })}
            </div>
          </div>

          {/* Background layer track (full length) */}
          <div className="flex items-stretch gap-1.5 h-5">
            <span className="w-14 shrink-0 flex items-center text-[9px] font-bold uppercase tracking-wide text-gray-400">BG</span>
            <div className="flex-1 rounded bg-slate-200 dark:bg-slate-700/60 flex items-center px-2">
              <span className="truncate text-[9px] font-semibold text-slate-500 dark:text-slate-300">Background layers (image / video)</span>
            </div>
          </div>

          {/* Voiceover track (full length) */}
          <div className="flex items-stretch gap-1.5 h-5">
            <span className="w-14 shrink-0 flex items-center text-[9px] font-bold uppercase tracking-wide text-gray-400">Audio</span>
            <div className="flex-1 rounded bg-amber-100 dark:bg-amber-900/40 flex items-center px-2">
              <span className="truncate text-[9px] font-semibold text-amber-700 dark:text-amber-300">Voiceover · preview in the Audio panel</span>
            </div>
          </div>
        </div>

        {/* Playhead line through every track */}
        <div className="pointer-events-none absolute top-0 bottom-0 left-0 right-0">
          <div className="absolute top-0 bottom-0 w-px bg-rose-500 z-20" style={{ left: markerPct }}>
            <div className="absolute -top-0.5 left-1/2 -translate-x-1/2 w-0 h-0 border-x-[5px] border-x-transparent border-t-[7px] border-t-rose-500" />
          </div>
        </div>
      </div>
    </div>
  );
});

function swatchStyle(palette: [string, string, string]): React.CSSProperties {
  return { background: `linear-gradient(135deg, ${palette[0]}, ${palette[1]} 55%, ${palette[2]})` };
}

/**
 * Per-clip text element editor. Mirrors the designed layout by reading the same
 * hit-test the canvas uses, so every slider/toggle matches the live frame. Each
 * element row can be opened to restyle, move, hide or override the text; reset
 * restores the designed value.
 */
function ElementInspector({
  scene, opts, brief, index, onSet, onReset,
}: {
  scene: DirectorScene;
  opts: SceneFrameOptions;
  brief: MotionConfig;
  index: number;
  onSet: (key: SceneElementKey, style: TextElementStyle) => void;
  onReset: (key: SceneElementKey) => void;
}) {
  const [selected, setSelected] = useState<SceneElementKey | null>(null);
  const regions = useMemo(() => sceneElementRegions(opts, scene, index), [opts, scene, index]);

  const styleOf = (key: SceneElementKey): TextElementStyle => scene.elements?.[key] ?? {};
  const custom = (key: SceneElementKey) => Boolean(scene.elements?.[key]);

  return (
    <div className="space-y-2">
      {ELEMENT_KEYS.map((key) => {
        const st = styleOf(key);
        const isOpen = selected === key;
        const isCustom = custom(key);
        const hasRegion = regions.some((r) => r.key === key);
        return (
          <div key={key} className="rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
            <button
              type="button"
              onClick={() => setSelected(isOpen ? null : key)}
              className="w-full flex items-center justify-between px-3 py-2 text-left text-sm"
            >
              <span className="flex items-center gap-2 min-w-0">
                <span
                  className={`w-2 h-2 rounded-full shrink-0 ${hasRegion ? 'bg-rose-500' : 'bg-gray-300 dark:bg-gray-600'}`}
                />
                <span className="truncate">{ELEMENT_LABELS[key]}</span>
                {isCustom && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-300 shrink-0">custom</span>
                )}
                {st.hidden && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400 shrink-0">hidden</span>
                )}
              </span>
              <ChevronDown className={`w-4 h-4 text-gray-400 shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
            </button>
            {isOpen && (
              <div className="space-y-3 px-3 pb-3">
                <label className="block text-xs text-gray-600 dark:text-gray-300">
                  Text
                  <input
                    type="text"
                    defaultValue={st.text ?? briefTextFor(scene, brief)}
                    onBlur={(e) => onSet(key, { text: e.target.value.trim() === briefTextFor(scene, brief) ? undefined : e.target.value.trim() })}
                    className="mt-1 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 px-2 py-1 text-sm"
                  />
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <label className="block text-xs text-gray-600 dark:text-gray-300">
                    Font
                    <select
                      value={st.fontFamily ?? ''}
                      onChange={(e) => onSet(key, { fontFamily: e.target.value || undefined })}
                      className="mt-1 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 px-2 py-1 text-sm"
                    >
                      {FONT_FAMILY_OPTIONS.map((f) => (
                        <option key={f.label} value={f.value ?? ''}>{f.label}</option>
                      ))}
                    </select>
                  </label>
                  <label className="block text-xs text-gray-600 dark:text-gray-300">
                    Weight
                    <select
                      value={st.fontWeight ?? 700}
                      onChange={(e) => onSet(key, { fontWeight: Number(e.target.value) || undefined })}
                      className="mt-1 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 px-2 py-1 text-sm"
                    >
                      {WEIGHT_OPTIONS.map((w) => (
                        <option key={w.label} value={w.value ?? 400}>{w.label}</option>
                      ))}
                    </select>
                  </label>
                </div>
                <div>
                  <span className="block text-xs text-gray-600 dark:text-gray-300">Colour</span>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {ELEMENT_COLORS.map((c) => (
                      <button
                        key={c.swatch}
                        type="button"
                        title={c.swatch}
                        onClick={() => onSet(key, { color: c.swatch })}
                        className={`w-5 h-5 rounded-full border border-black/10 ${st.color === c.swatch ? 'ring-2 ring-rose-500 ring-offset-1 dark:ring-offset-gray-900' : ''}`}
                        style={{ background: c.swatch }}
                      />
                    ))}
                  </div>
                </div>
                <label className="block text-xs text-gray-600 dark:text-gray-300">
                  Size <span className="text-gray-400">{(st.scale ?? 1).toFixed(2)}×</span>
                  <input
                    type="range"
                    min={0.6}
                    max={1.8}
                    step={0.05}
                    value={st.scale ?? 1}
                    onChange={(e) => onSet(key, { scale: Number(e.target.value) })}
                    className="mt-1 w-full"
                  />
                </label>
                <label className="block text-xs text-gray-600 dark:text-gray-300">
                  Position X <span className="text-gray-400">{Math.round((st.dx ?? 0) * 100)}%</span>
                  <input
                    type="range"
                    min={-0.5}
                    max={0.5}
                    step={0.01}
                    value={st.dx ?? 0}
                    onChange={(e) => onSet(key, { dx: Number(e.target.value) })}
                    className="mt-1 w-full"
                  />
                </label>
                <label className="block text-xs text-gray-600 dark:text-gray-300">
                  Position Y <span className="text-gray-400">{Math.round((st.dy ?? 0) * 100)}%</span>
                  <input
                    type="range"
                    min={-0.5}
                    max={0.5}
                    step={0.01}
                    value={st.dy ?? 0}
                    onChange={(e) => onSet(key, { dy: Number(e.target.value) })}
                    className="mt-1 w-full"
                  />
                </label>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => onSet(key, { hidden: !st.hidden })}
                    className="flex items-center gap-1.5 rounded-md border border-gray-300 dark:border-gray-600 px-2 py-1 text-xs"
                  >
                    {st.hidden ? <Eye className="w-3.5 h-3.5" /> : <EyeOff className="w-3.5 h-3.5" />}
                    {st.hidden ? 'Show' : 'Hide'}
                  </button>
                  <button
                    type="button"
                    onClick={() => onReset(key)}
                    className="flex items-center gap-1.5 rounded-md border border-gray-300 dark:border-gray-600 px-2 py-1 text-xs"
                  >
                    <RotateCcw className="w-3.5 h-3.5" />
                    Reset
                  </button>
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function MotionGraphicsStudio() {
  const [mode, setMode] = useState<Mode>('quick');
  const [project, setProject] = useState<MotionProject>(() => loadMotionProjects()[0] ?? blankMotionProject());
  const [projects, setProjects] = useState<MotionProject[]>(() => loadMotionProjects());
  const [quickAspect, setQuickAspect] = useState<RenderAspect>('Vertical');
  const [prompt, setPrompt] = useState('');
  const [aiError, setAiError] = useState<string | null>(null);

  const [rendering, setRendering] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  // Editable preview — a selected scene freezes the canvas and lets clicks open
  // the element's field inline (headline, sub-line, brand lockup or call to action).
  const [editMode, setEditMode] = useState(false);
  const [editSceneIndex, setEditSceneIndex] = useState(0);
  const [editing, setEditing] = useState<{ key: SceneElementKey; label: string; value: string } | null>(null);

  // Editor workspace transport + toolbar.
  const [playing, setPlaying] = useState(false);
  const [playhead, setPlayhead] = useState<number | null>(null);
  const [tool, setTool] = useState<'media' | 'text' | 'elements' | 'audio' | 'brand'>('text');
  const progressRef = useRef(0);
  const timelineRef = useRef<{ setMarker: (fraction: number) => void } | null>(null);

  // Undo / redo stack over the shared project (ref + tick so the toolbar
  // buttons re-evaluate without re-rendering the whole editor on every frame).
  const historyRef = useRef<{ past: MotionProject[]; future: MotionProject[] }>({ past: [], future: [] });

  // User-uploaded layers (images/videos) that compose the film bottom-to-top in
  // the preview and every export. Session-local: kept in component state as
  // object URLs, never written to the project or the database.
  const [layers, setLayers] = useState<(MotionLayer & { name: string })[]>([]);
  const layersRef = useRef(layers);
  layersRef.current = layers;
  useEffect(() => () => {
    layersRef.current.forEach((l) => { if (l.url) URL.revokeObjectURL(l.url); });
  }, []);

  const addLayerFiles = (files: FileList | File[]) => {
    const fileList = Array.from(files);
    if (fileList.length === 0) return;
    const accepted = fileList.filter((f) => /^(image|video)\//.test(f.type));
    if (accepted.length === 0) {
      toast.error('Pick images (PNG/JPG) or videos (MP4/WebM) for the layers.');
      return;
    }
    const next: (MotionLayer & { name: string })[] = accepted.map((file) => {
      const url = URL.createObjectURL(file);
      const media: MotionLayer = file.type.startsWith('video/')
        ? { kind: 'video', url, video: createBackgroundVideo(url) }
        : { kind: 'image', url, image: createBackgroundImage(url) };
      return { ...media, name: file.name };
    });
    setLayers((prev) => [...prev, ...next]);
    toast(`Added ${accepted.length} layer${accepted.length > 1 ? 's' : ''} — composed in the preview & downloads, kept on this device only.`);
  };

  const moveLayer = (i: number, dir: -1 | 1) => {
    setLayers((prev) => {
      const j = i + dir;
      if (j < 0 || j >= prev.length) return prev;
      const next = [...prev];
      const [moved] = next.splice(i, 1);
      next.splice(j, 0, moved);
      return next;
    });
  };

  const setLayerOpacity = (i: number, v: number) => {
    setLayers((prev) => prev.map((l, idx) => (idx === i ? { ...l, opacity: v } : l)));
  };

  const removeLayer = (i: number) => {
    const target = layers[i];
    if (target?.url) URL.revokeObjectURL(target.url);
    setLayers((prev) => prev.filter((_, idx) => idx !== i));
    if (layers.length <= 1) toast('Layers removed — back to the designed motion graphic.');
  };

  const clearLayers = () => {
    layers.forEach((l) => { if (l.url) URL.revokeObjectURL(l.url); });
    setLayers([]);
    toast('Layers removed — back to the designed motion graphic.');
  };

  // Autosave — every edit lands in nowopen_motion_projects.
  useEffect(() => { setProjects(saveMotionProject(project)); }, [project]);

  const patch = (partial: Partial<MotionProject>) => {
    historyRef.current = { past: [...historyRef.current.past.slice(-49), project], future: [] };
    setProject((prev) => (prev ? { ...prev, ...partial, updatedAt: new Date().toISOString() } : prev));
  };

  const editBrief = (partial: Partial<MotionConfig>) =>
    setProject((prev) => (prev ? { ...prev, templateKey: undefined, brief: { ...prev.brief, ...partial }, updatedAt: new Date().toISOString() } : prev));

  const editRender = (partial: Partial<MotionProject['render']>) =>
    setProject((prev) => (prev ? { ...prev, render: { ...prev.render, ...partial }, updatedAt: new Date().toISOString() } : prev));

  const canUndo = historyRef.current.past.length > 0;
  const canRedo = historyRef.current.future.length > 0;

  const undo = () => {
    const h = historyRef.current;
    if (h.past.length === 0) return;
    const prev = h.past[h.past.length - 1];
    historyRef.current = { past: h.past.slice(0, -1), future: [project, ...h.future] };
    setProject(prev);
  };

  const redo = () => {
    const h = historyRef.current;
    if (h.future.length === 0) return;
    const next = h.future[0];
    historyRef.current = { past: [...h.past, project], future: h.future.slice(1) };
    setProject(next);
  };

  const saveNow = () => {
    setProjects(saveMotionProject(project));
    toast.success('Project saved.');
  };

  // --- Editor workspace: transport, scrub, clip selection and timeline ops ---

  const applyTimelineOp = (fn: (tl: MotionTimeline) => MotionTimeline) =>
    patch({ timeline: fn(project.timeline ?? emptyMotionTimeline(baseScenes)) });

  const onMoveClip = (fromIndex: number, toIndex: number) => {
    const id = scenes[fromIndex]?.id;
    if (!id) return;
    applyTimelineOp((tl) => timelineMoveClip(tl, id, toIndex));
  };

  const onTrimClip = (id: string, seconds: number) => {
    applyTimelineOp((tl) => timelineSetSeconds(tl, id, seconds));
  };

  const onSplitClip = (id: string) => {
    const src = scenes.find((s) => s.id === id);
    if (!src) return;
    const next = timelineSplit(scenes, project.timeline ?? emptyMotionTimeline(baseScenes), id, src.seconds / 2);
    patch({ timeline: next });
    toast('Clip split in two.');
  };

  const onDuplicateClip = (id: string) => {
    const next = timelineDuplicate(scenes, project.timeline ?? emptyMotionTimeline(baseScenes), id);
    patch({ timeline: next });
    toast('Clip duplicated.');
  };

  const onRemoveClip = (id: string) => {
    patch({ timeline: timelineRemove(project.timeline ?? emptyMotionTimeline(baseScenes), id) });
    if (editing) setEditing(null);
    if (scenes[editSceneIndex]?.id === id) setEditSceneIndex(Math.max(0, editSceneIndex - 1));
  };

  const onAddClip = () => {
    const base = scenes[editSceneIndex] ?? scenes[scenes.length - 1] ?? scenes[0];
    if (!base) return;
    const next = timelineAppendClip(project.timeline ?? emptyMotionTimeline(baseScenes), base);
    patch({ timeline: next });
    setEditSceneIndex(scenes.length);
    toast('Clip added — adjust the elements, then preview.');
  };

  const onSetElement = (key: SceneElementKey, style: TextElementStyle) => {
    const id = scenes[editSceneIndex]?.id;
    if (!id) return;
    applyTimelineOp((tl) => timelineSetElement(tl, id, key, style));
  };

  const onResetElement = (key: SceneElementKey) => {
    const id = scenes[editSceneIndex]?.id;
    if (!id) return;
    applyTimelineOp((tl) => timelineResetElement(tl, id, key));
  };

  const onMoveElement = (key: SceneElementKey, dx: number, dy: number) => {
    onSetElement(key, { dx, dy });
  };

  const onResetTimeline = () => {
    patch({ timeline: undefined });
    toast('Timeline reset to the designed order.');
  };

  const onProgress = useCallback((fraction: number) => {
    progressRef.current = fraction;
    timelineRef.current?.setMarker(fraction);
  }, []);

  const sceneStartFraction = (index: number) => {
    if (scenes.length === 0 || seconds <= 0) return 0;
    const acc = scenes.slice(0, Math.max(0, Math.min(index, scenes.length))).reduce((s, x) => s + x.seconds, 0);
    return Math.max(0, Math.min(1, acc / seconds));
  };

  const selectScene = (index: number) => {
    const i = Math.max(0, Math.min(index, scenes.length - 1));
    setEditSceneIndex(i);
    setEditMode(true);
    setEditing(null);
    setPlaying(false);
    const at = sceneStartFraction(i);
    progressRef.current = at;
    setPlayhead(at);
    timelineRef.current?.setMarker(at);
  };

  const onScrub = (fraction: number, sceneIndex: number) => {
    if (playing) { setPlaying(false); setEditMode(false); setEditing(null); }
    progressRef.current = fraction;
    setPlayhead(fraction);
    setEditSceneIndex(sceneIndex);
  };

  const togglePlay = () => {
    if (playing) {
      setPlaying(false);
      setEditMode(false);
      setEditing(null);
      setPlayhead(progressRef.current);
    } else {
      setEditMode(false);
      setEditing(null);
      setPlaying(true);
      setPlayhead(progressRef.current);
    }
  };

  const speakScene = (text: string) => {
    if (typeof window === 'undefined' || !window.speechSynthesis) { toast.error('Speech synthesis is not available in this browser.'); return; }
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    const v = pickPreviewVoice(window.speechSynthesis.getVoices(), 'Female', 'en');
    if (v) u.voice = v;
    window.speechSynthesis.speak(u);
  };

  const speakTrack = () => {
    if (typeof window === 'undefined' || !window.speechSynthesis) { toast.error('Speech synthesis is not available in this browser.'); return; }
    window.speechSynthesis.cancel();
    scenes.forEach((s) => {
      const u = new SpeechSynthesisUtterance(s.voiceover);
      const v = pickPreviewVoice(window.speechSynthesis.getVoices(), 'Female', 'en');
      if (v) u.voice = v;
      window.speechSynthesis.speak(u);
    });
  };

  const pickElement = (key: SceneElementKey) => {
    const scene = scenes[editSceneIndex] ?? scenes[0];
    const value = scene?.elements?.[key]?.text ?? '';
    setEditing({ key, label: ELEMENT_LABELS[key], value });
  };

  const commitEdit = () => {
    if (!editing) return;
    const scene = scenes[editSceneIndex];
    const base = scene ? briefTextFor(scene, brief) : '';
    const text = editing.value.trim();
    onSetElement(editing.key, { text: text === base ? undefined : text });
    setEditing(null);
  };

  const openProject = (p: MotionProject, nextMode: Mode = 'studio') => {
    historyRef.current = { past: [], future: [] };
    setProject(p);
    setMode(nextMode);
    setError(null);
    setAiError(null);
    setEditMode(false);
    setEditing(null);
    setPlaying(false);
    setPlayhead(null);
    progressRef.current = 0;
  };

  const startFromTemplate = (t: MotionTemplate) => {
    openProject(motionProjectFromTemplate(t, quickAspect));
    toast.success(`${t.name} project created — fine-tune it in Studio.`);
  };

  const startBlank = (aspect: RenderAspect = 'Vertical') => {
    openProject(blankMotionProject(aspect));
    toast.success('Blank project created — now in Studio.');
  };

  const buildFromPrompt = () => {
    const trimmed = prompt.trim();
    if (!trimmed) { setAiError('Tell the director what you want first.'); return; }
    openProject(motionProjectFromPrompt(trimmed));
    setPrompt('');
    toast.success('Designed locally — a full editable project is now in Studio.');
  };

  const duplicate = () => {
    openProject(duplicateMotionProject(project));
    toast.success('Project duplicated.');
  };

  const remove = () => {
    const next = deleteMotionProject(project.id);
    setProjects(next);
    openProject(next[0] ?? blankMotionProject('Vertical'));
    toast.success('Project deleted.');
  };

  const brief = project.brief;
  const label = STYLES.find((s) => s.key === brief.style)?.label ?? 'Motion';
  const baseScenes = useMemo(() => motionScenesFromJob(brief), [brief]);
  const scenes = useMemo(() => applyMotionTimeline(baseScenes, project.timeline), [baseScenes, project.timeline]);
  const opts: SceneFrameOptions = useMemo(
    () => ({
      businessName: brief.business || 'NowOpen',
      directionLabel: label,
      hook: brief.headline,
      cta: brief.cta,
      aspect: brief.aspect,
      logoEmoji: brief.logoEmoji || '✦',
      palette: project.palette,
      treatment: TREATMENT_FOR_STYLE[brief.style],
      layers: layers.length > 0 ? layers : null,
      scenesCount: scenes.length,
    }),
    [brief, label, project.palette, scenes.length, layers],
  );
  const seconds = useMemo(() => scenes.reduce((s, x) => s + x.seconds, 0), [scenes]);
  const renderSource = project.render.source;
  const templateName = project.templateKey ? motionTemplateByKey(project.templateKey)?.name : null;
  const selScene = scenes.length > 0 ? scenes[Math.min(editSceneIndex, scenes.length - 1)] : null;

  const downloadVideo = async () => {
    setRendering(true);
    setError(null);
    setProgress(0);
    try {
      let footage;
      if (renderSource === 'aivideo') {
        footage = await resolveAiVideoClips({
          businessName: brief.business || 'NowOpen',
          industryLabel: 'brand',
          directionLabel: label,
          scenes,
          model: project.render.model,
          aspect: brief.aspect,
        });
        const got = Object.keys(footage).length;
        if (got === 0) {
          toast('No AI clips could be generated — the video uses designed graphics. Connect a media key on the server and try again.');
        } else if (got < scenes.length) {
          toast(`${got} of ${scenes.length} AI clips generated; the rest use designed graphics.`);
        }
      }
      const result = await renderVideo(
        { ...opts, footage, footageEnabled: renderSource === 'aivideo' },
        scenes,
        (p) => setProgress(p),
      );
      const url = URL.createObjectURL(result.blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `motion-${brief.style}-${brief.aspect.toLowerCase()}.${result.mimeType.includes('mp4') ? 'mp4' : 'webm'}`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not render the video.');
    } finally {
      setRendering(false);
      setProgress(0);
    }
  };

  const downloadStill = useCallback((kind: 'poster' | 'sheet') => {
    const still = kind === 'poster' ? renderPoster(opts, scenes) : renderContactSheet(opts, scenes);
    if (!still) { toast.error('Still export is not supported in this browser.'); return; }
    const a = document.createElement('a');
    a.href = still.dataUrl;
    a.download = `motion-${brief.style}-${kind}.png`;
    a.click();
    toast.success(`${kind === 'poster' ? 'Poster' : 'Contact sheet'} exported (PNG).`);
  }, [opts, scenes, brief.style]);

  return (
    <div className="space-y-5">
      {/* Header + mode tabs */}
      <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="min-w-0">
            <h2 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <Clapperboard size={16} className="text-purple-500" /> Motion Studio
            </h2>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 max-w-2xl">
              One editable project, three ways in. Quick Create starts from a format and a modern template,
              Studio is the full editor, and the AI Director writes the brief for you.
              Every mode ends in the same MotionProject you can resize, re-edit and render.
            </p>
          </div>
          <div className="flex rounded-xl bg-gray-100 dark:bg-gray-800 p-1">
            {MODES.map((m) => (
              <button key={m.key} onClick={() => setMode(m.key)} aria-pressed={mode === m.key} title={m.blurb}
                className={`px-3.5 py-2 rounded-lg text-xs font-bold transition ${mode === m.key ? 'bg-white dark:bg-gray-700 text-gray-900 dark:text-white shadow-sm' : 'text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'}`}>
                {m.emoji} {m.label}
              </button>
            ))}
          </div>
        </div>
        <p className="mt-2.5 text-[11px] text-gray-500 dark:text-gray-400">{MODES.find((m) => m.key === mode)?.blurb}</p>
      </section>

      {/* Project bar — the shared, autosaved project behind the AI Director (Studio has its own top bar) */}
      {mode === 'ai' && (
        <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-4">
          <div className="flex flex-wrap items-end gap-3">
            <label className="block min-w-[180px] flex-1">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Project name</span>
              <input value={project.name} onChange={(e) => patch({ name: e.target.value })}
                className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Status</span>
              <select value={project.status} onChange={(e) => patch({ status: e.target.value as MotionProjectStatus })}
                className="mt-1 px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
                {MOTION_PROJECT_STATUSES.map((s) => (
                  <option key={s} value={s}>{MOTION_PROJECT_STATUS_LABELS[s]}</option>
                ))}
              </select>
            </label>
            <div className="flex flex-wrap items-center gap-2 ml-auto">
              <span className="text-[11px] text-gray-400 inline-flex items-center gap-1" title="Saved to this browser under nowopen_motion_projects">
                <Check size={12} className="text-emerald-500" /> Autosaved · {timeAgo(project.updatedAt)}
              </span>
              <button onClick={() => startBlank()} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                <Plus size={13} /> New
              </button>
              <button onClick={duplicate} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                <Copy size={13} /> Duplicate
              </button>
              <button onClick={remove} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40 transition">
                <Trash2 size={13} /> Delete
              </button>
            </div>
          </div>
        </section>
      )}

      {/* QUICK CREATE — format + template gallery + your projects */}
      {mode === 'quick' && (
        <>
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
              <LayoutTemplate size={15} className="text-purple-500" /> Pick your format
            </h3>
            <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5">
              Choose where it plays. You can switch shape again in Studio without losing anything.
            </p>
            <div className="mt-3 grid grid-cols-1 sm:grid-cols-3 gap-2">
              {ASPECTS.map((a) => (
                <button key={a.key} onClick={() => setQuickAspect(a.key)} aria-pressed={quickAspect === a.key}
                  className={`text-left p-3 rounded-xl border transition ${quickAspect === a.key ? 'border-purple-500 bg-purple-50 dark:bg-purple-900/20' : 'border-gray-200 dark:border-gray-700 hover:border-purple-300'}`}>
                  <span className="text-xs font-bold text-gray-900 dark:text-white">{a.label}</span>
                  <span className="block mt-0.5 text-[10px] text-gray-500 dark:text-gray-400">{a.hint} · {RENDER_DIMENSIONS[a.key].width}×{RENDER_DIMENSIONS[a.key].height}</span>
                </button>
              ))}
            </div>
          </section>

          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <div>
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <LayoutTemplate size={15} className="text-purple-500" /> Modern template gallery
              </h3>
              <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5">
                The latest motion design concepts, ready to film. Each one becomes a real project you can keep editing in Studio.
              </p>
            </div>
            <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              {MOTION_TEMPLATES.map((t) => (
                <button key={t.key} onClick={() => startFromTemplate(t)} title={`${t.name} — ${t.concept}`}
                  className="text-left rounded-xl border-2 border-gray-200 dark:border-gray-700 hover:border-purple-300 transition overflow-hidden">
                  <div className="relative h-20" style={swatchStyle(t.palette)}>
                    <span className="absolute inset-0 flex items-center justify-center text-3xl drop-shadow">{t.emoji}</span>
                  </div>
                  <div className="p-2.5">
                    <span className="block text-xs font-bold text-gray-900 dark:text-white">{t.name}</span>
                    <p className="mt-0.5 text-[10px] leading-snug text-gray-500 dark:text-gray-400 line-clamp-2">{t.concept}</p>
                    <div className="mt-1.5 flex flex-wrap gap-1">
                      {t.tags.map((tag) => (
                        <span key={tag} className="px-1.5 py-0.5 rounded-md bg-purple-50 dark:bg-purple-900/30 text-[9px] font-bold text-purple-600 dark:text-purple-300">{tag}</span>
                      ))}
                    </div>
                  </div>
                </button>
              ))}
            </div>
            <button onClick={() => startBlank(quickAspect)}
              className="mt-4 inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold transition">
              <Plus size={14} /> Start from a blank brief
            </button>
          </section>

          {projects.length > 0 && (
            <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
              <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                <FolderOpen size={15} className="text-purple-500" /> Your projects
              </h3>
              <div className="mt-3 space-y-1.5">
                {projects.map((p) => (
                  <div key={p.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-gray-100 dark:border-gray-700 px-3.5 py-2.5">
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-xs font-bold text-gray-900 dark:text-white">{p.name}</span>
                      <span className="text-[10px] text-gray-500 dark:text-gray-400">
                        {p.source === 'ai' ? 'AI designed' : p.source === 'template' ? 'Template' : 'Blank'} · {MOTION_PROJECT_STATUS_LABELS[p.status]} · {p.brief.aspect} · {timeAgo(p.updatedAt)}
                      </span>
                    </span>
                    <span className="w-4 h-4 rounded-full shrink-0" style={swatchStyle(p.palette)} />
                    <button onClick={() => openProject(p)} className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-600 hover:bg-purple-700 text-white transition">
                      Open in Studio
                    </button>
                    <button onClick={() => { deleteMotionProject(p.id); setProjects(loadMotionProjects()); }} aria-label={`Delete ${p.name}`}
                      className="inline-flex items-center px-2 py-1.5 rounded-lg text-xs text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition">
                      <Trash2 size={13} />
                    </button>
                  </div>
                ))}
              </div>
            </section>
          )}
        </>
      )}

      {/* AI DIRECTOR — plain English → a full project */}
      {mode === 'ai' && (
        <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
            <Wand2 size={15} className="text-purple-500" /> AI Director
          </h3>
          <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 max-w-2xl">
            Describe the motion in plain English — the local director reads the offer, the format, the vibe and the length,
            and designs a complete project you can open in Studio and edit. It is honest: no cloud model, no wait,
            and nothing that cannot be changed afterwards.
          </p>
          <div className="mt-4">
            <label className="block">
              <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Your brief</span>
              <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={4}
                placeholder="e.g. A countdown reel for a Lagos coffee shop opening this Friday"
                className="mt-1 w-full px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-purple-500" />
            </label>
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-1.5">
            <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Try:</span>
            {EXAMPLE_PROMPTS.map((p) => (
              <button key={p} onClick={() => setPrompt(p)}
                className="px-2.5 py-1 rounded-lg bg-gray-100 dark:bg-gray-700 text-[11px] text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                {p}
              </button>
            ))}
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <button onClick={buildFromPrompt}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold transition">
              <Sparkles size={15} /> Build motion project
            </button>
            {aiError && <p role="alert" className="text-xs text-red-600 dark:text-red-400">{aiError}</p>}
          </div>
        </section>
      )}

      {/* STUDIO — the full editor over the shared project */}
      {mode === 'studio' && (
        <>
          {templateName && (
            <p className="text-[11px] text-purple-700 dark:text-purple-300">
              Based on {templateName} — tweak the words, shape, pace and palette below; the preview updates live and the project stays editable.
            </p>
          )}

          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
            {/* Editor workspace top bar */}
            <div className="flex flex-wrap items-center gap-2 px-3 py-2 border-b border-gray-100 dark:border-gray-700">
              <button onClick={() => setMode('quick')} title="Back to Quick Create"
                className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 transition">
                <ArrowLeft size={14} /> Back
              </button>
              <div className="w-px h-5 bg-gray-200 dark:bg-gray-700" />
              <label className="block min-w-[160px]">
                <span className="sr-only">Project name</span>
                <input value={project.name} onChange={(e) => patch({ name: e.target.value })} aria-label="Project name"
                  className="w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-purple-500" />
              </label>
              <select value={project.status} onChange={(e) => patch({ status: e.target.value as MotionProjectStatus })} aria-label="Status"
                className="px-2 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-xs focus:outline-none focus:ring-2 focus:ring-purple-500">
                {MOTION_PROJECT_STATUSES.map((s) => (
                  <option key={s} value={s}>{MOTION_PROJECT_STATUS_LABELS[s]}</option>
                ))}
              </select>
              <span className="hidden md:inline-flex items-center gap-1 text-[10px] text-gray-400" title="Autosaved to nowopen_motion_projects">
                <Check size={11} className="text-emerald-500" /> Autosaved · {timeAgo(project.updatedAt)}
              </span>
              <div className="ml-auto flex flex-wrap items-center gap-1.5">
                <button onClick={undo} disabled={!canUndo} title="Undo" aria-label="Undo"
                  className="w-8 h-8 inline-flex items-center justify-center rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:border-purple-300 transition disabled:opacity-40">
                  <Undo2 size={14} />
                </button>
                <button onClick={redo} disabled={!canRedo} title="Redo" aria-label="Redo"
                  className="w-8 h-8 inline-flex items-center justify-center rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:border-purple-300 transition disabled:opacity-40">
                  <Redo2 size={14} />
                </button>
                <div className="w-px h-5 bg-gray-200 dark:bg-gray-700" />
                <button onClick={togglePlay} title={playing ? 'Pause preview' : 'Play preview'} aria-label="Play preview"
                  className="w-8 h-8 inline-flex items-center justify-center rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:border-purple-300 transition">
                  {playing ? <Pause size={14} /> : <Play size={14} className="ml-0.5" />}
                </button>
                <button onClick={saveNow} title="Save now (already autosaves)"
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 hover:border-purple-300 transition">
                  <Save size={13} /> Save
                </button>
                <button onClick={downloadVideo} disabled={rendering}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-600 hover:bg-purple-700 disabled:opacity-60 text-white transition">
                  {rendering ? <Loader2 size={13} className="animate-spin" /> : <Download size={13} />}
                  {rendering ? `Filming ${Math.round(progress * 100)}%` : 'Export'}
                </button>
              </div>
            </div>

            {/* Workspace: toolbar · canvas · properties */}
            <div className="grid grid-cols-[52px_minmax(0,1fr)_290px] min-h-[540px]">
              {/* Left toolbar */}
              <div className="border-r border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 py-2 flex flex-col items-center gap-1">
                {([
                  { key: 'media', label: 'Media', icon: ImageIcon },
                  { key: 'text', label: 'Text', icon: Type },
                  { key: 'elements', label: 'Elements', icon: Shapes },
                  { key: 'audio', label: 'Audio', icon: Music },
                  { key: 'brand', label: 'Brand', icon: Palette },
                ] as const).map((t) => (
                  <button key={t.key} onClick={() => { setTool(t.key); setEditMode(false); setEditing(null); }} title={t.label} aria-pressed={tool === t.key}
                    className={`w-full flex flex-col items-center gap-0.5 py-2 rounded-lg text-[9px] font-semibold transition ${tool === t.key ? 'bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300' : 'text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'}`}>
                    <t.icon size={17} />
                    <span>{t.label}</span>
                  </button>
                ))}
              </div>

              {/* Central canvas */}
              <div className="min-w-0 p-4 flex flex-col gap-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                    <Film size={15} className="text-purple-500" /> Live preview
                  </h3>
                  <span className="text-[11px] font-semibold text-gray-400">
                    {MOTION_SCENE_COUNTS[brief.style]} cards · {seconds}s · {RENDER_DIMENSIONS[brief.aspect].width}×{RENDER_DIMENSIONS[brief.aspect].height}
                  </span>
                </div>
                <div className="flex-1 flex items-center justify-center min-h-[380px] bg-gray-50 dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-700 p-3">
                  <MotionPreview opts={opts} scenes={scenes} editMode={editMode} sceneIndex={editSceneIndex}
                    playing={playing} playhead={playhead} onProgress={onProgress} onPick={pickElement}
                    onMoveElement={onMoveElement}
                    className="max-w-full max-h-[68vh] w-auto h-auto rounded-xl border border-gray-200 dark:border-gray-700 bg-black shadow-xl" />
                </div>
                {editMode && (
                  <div className="space-y-2">
                    <p className="text-center text-[11px] text-gray-400">
                      Clip {editSceneIndex + 1} selected — click an outlined element to edit it, or drag it to move.
                    </p>
                    {editing ? (
                      <div className="rounded-lg border border-purple-300 dark:border-purple-700 bg-purple-50 dark:bg-purple-900/20 p-2 space-y-2 max-w-md mx-auto">
                        <div className="text-[11px] font-semibold text-purple-700 dark:text-purple-300">
                          Custom text for {editing.label} — scene {editSceneIndex + 1}
                        </div>
                        <input autoFocus value={editing.value}
                          onChange={(e) => setEditing({ ...editing, value: e.target.value })}
                          onKeyDown={(e) => { if (e.key === 'Enter') commitEdit(); if (e.key === 'Escape') setEditing(null); }}
                          className="w-full px-2 py-1.5 text-sm rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 text-gray-900 dark:text-white" />
                        <div className="flex gap-2 justify-end">
                          <button onClick={() => setEditing(null)} className="px-2.5 py-1 text-[11px] font-semibold rounded-md border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-300">Cancel</button>
                          <button onClick={commitEdit} className="px-2.5 py-1 text-[11px] font-semibold rounded-md bg-purple-600 text-white">Save</button>
                        </div>
                      </div>
                    ) : (
                      <p className="text-center text-[11px] text-gray-400">Drag clips on the timeline to reorder — or press play to watch the whole film.</p>
                    )}
                  </div>
                )}
              </div>

              {/* Right properties panel */}
              <aside className="border-l border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 overflow-y-auto">
                <div className="p-3 space-y-3">
                  {editMode && selScene ? (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-2.5">
                      <div className="flex items-center justify-between">
                        <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                          <Timer size={13} className="text-purple-500" /> Clip {editSceneIndex + 1}
                        </h4>
                        <span className="text-[10px] text-gray-400 tabular-nums">{selScene.seconds}s</span>
                      </div>
                      <p className="text-[11px] font-semibold text-gray-700 dark:text-gray-200">“{selScene.text}”</p>
                      <ElementInspector
                        scene={selScene}
                        opts={opts}
                        brief={brief}
                        index={editSceneIndex}
                        onSet={onSetElement}
                        onReset={onResetElement}
                      />
                      <p className="text-[10px] text-gray-400 italic">Voiceover: “{selScene.voiceover}”</p>
                      <div>
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Trim duration</span>
                        <div className="mt-1 flex items-center gap-2">
                          <input type="range" min={CLIP_SECONDS_MIN} max={CLIP_SECONDS_MAX} step={0.5} value={selScene.seconds}
                            onChange={(e) => onTrimClip(selScene.id, Number(e.target.value))} className="flex-1" />
                          <span className="text-xs font-semibold text-gray-600 dark:text-gray-300 tabular-nums">{selScene.seconds}s</span>
                        </div>
                      </div>
                      <div className="flex flex-wrap gap-1.5">
                        <button onClick={() => onAddClip()} title="Add a new clip after the selected one"
                          className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                          <Plus size={12} /> Add clip
                        </button>
                        <button onClick={() => onSplitClip(selScene.id)} title="Split this clip in two"
                          className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                          <Scissors size={12} /> Split
                        </button>
                        <button onClick={() => onDuplicateClip(selScene.id)} title="Duplicate this clip"
                          className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                          <Copy size={12} /> Duplicate
                        </button>
                        <button onClick={() => onRemoveClip(selScene.id)} title="Remove this clip"
                          className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[11px] font-semibold bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/40 transition">
                          <Trash2 size={12} /> Remove
                        </button>
                      </div>
                    </section>
                  ) : tool === 'media' ? (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-2">
                      <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                        <Layers size={13} className="text-purple-500" /> Media layers
                      </h4>
                      <p className="text-[10px] text-gray-500 dark:text-gray-400 leading-snug">
                        Images/videos compose behind the captions. First layer = background; extra layers stack on top. Preview & downloads only, never saved.
                      </p>
                      <label title="Compose your film: the first layer is the background, extra layers stack on top under the captions (preview & downloads only, never saved)"
                        className="flex items-center justify-center gap-1.5 px-3 py-2 text-[11px] font-semibold rounded-lg border border-dashed border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-300 hover:border-purple-300 cursor-pointer">
                        <Plus size={13} /> {layers.length === 0 ? 'Add layers (image/video)' : 'Add another layer'}
                        <input type="file" accept="image/*,video/*" multiple className="hidden" onChange={(e) => {
                          if (e.target.files) addLayerFiles(e.target.files);
                          e.target.value = '';
                        }} />
                      </label>
                      {layers.length > 0 && (
                        <ul className="space-y-1.5">
                          {layers.map((l, i) => (
                            <li key={l.url} className="flex items-center gap-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 px-2.5 py-1.5">
                              <span className={`shrink-0 rounded px-1.5 py-0.5 text-[9px] font-bold uppercase ${l.kind === 'video' ? 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300' : 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300'}`}>
                                {i === 0 ? 'BG' : `L${i + 1}`} · {l.kind}
                              </span>
                              <span className="min-w-0 flex-1 truncate text-[11px] font-medium text-gray-700 dark:text-gray-200">{l.name}</span>
                              <input type="range" min={0} max={100} value={Math.round((l.opacity ?? 1) * 100)}
                                onChange={(e) => setLayerOpacity(i, Number(e.target.value) / 100)}
                                title={`Opacity ${Math.round((l.opacity ?? 1) * 100)}%`} className="w-14" />
                              <div className="flex items-center gap-0.5">
                                <button onClick={() => moveLayer(i, -1)} disabled={i === 0} className="p-0.5 rounded text-gray-400 hover:text-gray-600 disabled:opacity-30"><ChevronUp size={12} /></button>
                                <button onClick={() => moveLayer(i, 1)} disabled={i === layers.length - 1} className="p-0.5 rounded text-gray-400 hover:text-gray-600 disabled:opacity-30"><ChevronDown size={12} /></button>
                                <button onClick={() => removeLayer(i)} className="p-0.5 rounded text-red-400 hover:text-red-600"><Trash2 size={12} /></button>
                              </div>
                            </li>
                          ))}
                          <li className="flex justify-end">
                            <button onClick={clearLayers} className="flex items-center gap-1 px-2 py-1 text-[11px] font-semibold rounded-md border border-red-200 dark:border-red-900 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/40">
                              <Trash2 size={11} /> Clear layers
                            </button>
                          </li>
                        </ul>
                      )}
                    </section>
                  ) : tool === 'text' ? (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-2.5">
                      <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                        <Type size={13} className="text-purple-500" /> Captions
                      </h4>
                      <p className="text-[10px] text-gray-500 dark:text-gray-400 leading-snug">
                        These are your caption cards. They sync with the brief — edit once, every matching card updates.
                      </p>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Brand lockup</span>
                        <input value={brief.business} onChange={(e) => editBrief({ business: e.target.value })} className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                      </label>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Mark emoji</span>
                        <input value={brief.logoEmoji} onChange={(e) => editBrief({ logoEmoji: e.target.value })} className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                      </label>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Headline</span>
                        <input value={brief.headline} onChange={(e) => editBrief({ headline: e.target.value })} className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                      </label>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Sub-line (voiceover strip)</span>
                        <input value={brief.subhead} onChange={(e) => editBrief({ subhead: e.target.value })} className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                      </label>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Call to action (end card)</span>
                        <input value={brief.cta} onChange={(e) => editBrief({ cta: e.target.value })} className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500" />
                      </label>
                    </section>
                  ) : tool === 'elements' ? (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
                      <div className="p-3 border-b border-gray-100 dark:border-gray-700 flex items-center justify-between">
                        <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                          <ListVideo size={13} className="text-purple-500" /> Storyboard
                        </h4>
                        <span className="text-[10px] text-gray-400">{scenes.length} clips</span>
                      </div>
                      <ol className="divide-y divide-gray-100 dark:divide-gray-700">
                        {scenes.map((s, i) => (
                          <li key={s.id}
                            onClick={() => selectScene(i)}
                            className={`flex gap-2.5 p-2.5 cursor-pointer transition ${editSceneIndex === i ? 'bg-purple-50 dark:bg-purple-900/10' : 'hover:bg-gray-50 dark:hover:bg-gray-900'}`}>
                            <span className="shrink-0 w-6 h-6 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 text-[10px] font-bold flex items-center justify-center">{i + 1}</span>
                            <div className="min-w-0 flex-1">
                              <p className="truncate text-xs font-semibold text-gray-900 dark:text-white">{s.text}</p>
                              <p className="truncate text-[10px] text-gray-500 dark:text-gray-400 italic">“{s.voiceover}”</p>
                            </div>
                            <span className="shrink-0 text-[10px] font-semibold text-gray-400 tabular-nums">{s.seconds}s</span>
                          </li>
                        ))}
                      </ol>
                    </section>
                  ) : tool === 'audio' ? (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-2">
                      <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                        <Music size={13} className="text-purple-500" /> Voiceover
                      </h4>
                      <p className="text-[10px] text-gray-500 dark:text-gray-400 leading-snug">
                        Preview the scripted voiceover with your browser's built-in voice — no upload, no API key.
                      </p>
                      <div className="space-y-1.5">
                        <button onClick={() => speakScene(scenes[editSceneIndex]?.voiceover ?? scenes[0]?.voiceover ?? '')}
                          className="w-full inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg text-[11px] font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition">
                          <Play size={12} /> Play selected scene
                        </button>
                        <button onClick={speakTrack}
                          className="w-full inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg text-[11px] font-semibold bg-purple-600 hover:bg-purple-700 text-white transition">
                          <Play size={12} /> Play whole voiceover track
                        </button>
                        {scenes.map((s, i) => (
                          <button key={s.id} onClick={() => speakScene(s.voiceover)}
                            className="w-full text-left px-2.5 py-1.5 rounded-lg bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 hover:border-purple-300 transition">
                            <span className="block truncate text-[11px] font-semibold text-gray-700 dark:text-gray-200">{i + 1}. {s.text}</span>
                            <span className="block truncate text-[10px] text-gray-400 italic mt-0.5">“{s.voiceover}”</span>
                          </button>
                        ))}
                      </div>
                    </section>
                  ) : (
                    <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-3">
                      <h4 className="text-xs font-bold text-gray-900 dark:text-white inline-flex items-center gap-1.5">
                        <Palette size={13} className="text-purple-500" /> Brand & look
                      </h4>
                      <label className="block">
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Treatment</span>
                        <select value={brief.style} onChange={(e) => {
                          const s = STYLES.find((x) => x.key === e.target.value);
                          if (s) editBrief({ style: s.key, headline: s.defaults.headline, subhead: s.defaults.subhead, cta: s.defaults.cta, logoEmoji: s.defaults.logoEmoji });
                        }}
                          className="mt-1 w-full px-2.5 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500">
                          {STYLES.map((s) => <option key={s.key} value={s.key}>{s.emoji} {s.label}</option>)}
                        </select>
                      </label>
                      <div>
                        <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Palette</span>
                        <div className="mt-1.5 flex flex-wrap gap-1.5">
                          {RENDER_PALETTES.map((p, i) => (
                            <button key={i} onClick={() => patch({ palette: p, templateKey: undefined })} aria-pressed={project.palette === p} title={p.join(' → ')}
                              className={`w-7 h-7 rounded-lg border-2 transition ${project.palette === p ? 'border-purple-600 ring-2 ring-purple-300' : 'border-transparent'}`}
                              style={swatchStyle(p)} />
                          ))}
                        </div>
                      </div>
                    </section>
                  )}

                  {/* Format & pace — always available */}
                  <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 space-y-2.5">
                    <h4 className="text-xs font-bold text-gray-900 dark:text-white">Format & pace</h4>
                    <div>
                      <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Shape</span>
                      <div className="mt-1 flex flex-wrap gap-1.5">
                        {ASPECTS.map((a) => (
                          <button key={a.key} onClick={() => editBrief({ aspect: a.key })} aria-pressed={brief.aspect === a.key}
                            className={`px-2.5 py-1.5 rounded-lg text-[11px] font-semibold transition ${brief.aspect === a.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                            {a.label}<span className="ml-1 font-normal opacity-70">{a.hint}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <span className="text-[10px] font-bold uppercase tracking-wide text-gray-400">Pace</span>
                      <div className="mt-1 flex flex-wrap gap-1.5">
                        {DURATIONS.map((d) => (
                          <button key={d.key} onClick={() => editBrief({ duration: d.key })} aria-pressed={brief.duration === d.key}
                            className={`px-2.5 py-1.5 rounded-lg text-[11px] font-semibold transition ${brief.duration === d.key ? 'bg-purple-600 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                            {d.label}<span className="ml-1 font-normal opacity-70">{d.hint}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                  </section>
                </div>
              </aside>
            </div>

            {/* Bottom timeline */}
            <MotionTimeline
              ref={timelineRef}
              scenes={scenes}
              selected={editSceneIndex}
              playing={playing}
              totalSeconds={seconds}
              onSelect={selectScene}
              onScrub={onScrub}
              onPlayPause={togglePlay}
              onMove={onMoveClip}
              onTrim={onTrimClip}
              onReset={onResetTimeline}
            />

            {rendering && (
              <div className="mx-4 mb-3 h-1.5 rounded-full bg-gray-100 dark:bg-gray-700 overflow-hidden">
                <div className="h-full bg-purple-600 transition-[width] duration-200" style={{ width: `${Math.round(progress * 100)}%` }} />
              </div>
            )}
          </section>

          {/* Export */}
          <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <h3 className="text-sm font-bold text-gray-900 dark:text-white flex items-center gap-1.5">
                  <Film size={15} className="text-purple-500" /> Export
                </h3>
                <p className="text-[11px] text-gray-500 dark:text-gray-400 max-w-lg">
                  {renderSource === 'canvas'
                    ? 'Films the motion graphic on the free browser canvas — real, downloadable video with captions, motion and the end card. No model, no cost.'
                    : 'Films your motion design over generated AI video clips from a free or paid model — with captions, motion and the end card on top.'}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={() => downloadStill('poster')} disabled={rendering}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
                  <ImageIcon size={13} /> Poster PNG
                </button>
                <button onClick={() => downloadStill('sheet')} disabled={rendering}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 transition disabled:opacity-60">
                  <LayoutGrid size={13} /> Contact sheet
                </button>
                <button onClick={downloadVideo} disabled={rendering}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 disabled:opacity-60 text-white text-sm font-semibold transition">
                  {rendering ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
                  {rendering ? `Filming ${Math.round(progress * 100)}%` : `Render ${seconds}s video`}
                </button>
              </div>
            </div>

            <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 dark:border-gray-700 p-3">
              <div className="flex items-center gap-1.5">
                <span className="text-[11px] font-semibold text-gray-500 dark:text-gray-400">Render source</span>
                <div className="ml-1 flex rounded-lg bg-gray-100 dark:bg-gray-800 p-0.5">
                  {([
                    { key: 'canvas', label: 'Free canvas' },
                    { key: 'aivideo', label: 'AI video gen' },
                  ] as const).map((o) => (
                    <button key={o.key} type="button" onClick={() => editRender({ source: o.key })} aria-pressed={renderSource === o.key}
                      className={`px-3 py-1.5 rounded-md text-xs font-bold transition ${renderSource === o.key ? 'bg-purple-600 text-white shadow-sm' : 'text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-gray-700'}`}>
                      {o.label}
                    </button>
                  ))}
                </div>
              </div>
              {renderSource === 'aivideo' ? (
                <span className="text-[11px] text-gray-500 dark:text-gray-400">Designed motion graphics + {project.render.tier === 'free' ? 'free' : 'paid'} AI clips underneath.</span>
              ) : (
                <span className="text-[11px] text-gray-500 dark:text-gray-400">100% free — the canvas is the renderer.</span>
              )}
            </div>

            {renderSource === 'aivideo' && (
              <div className="mt-3">
                <AiVideoGenPicker
                  tier={project.render.tier}
                  onTier={(t) => {
                    editRender({ tier: t, model: videoGenModelsForTier(t)[0].key });
                  }}
                  model={project.render.model}
                  onModel={(m) => editRender({ model: m })}
                />
              </div>
            )}

            {rendering && (
              <div className="mt-3 h-1.5 rounded-full bg-gray-100 dark:bg-gray-700 overflow-hidden">
                <div className="h-full bg-purple-600 transition-[width] duration-200" style={{ width: `${Math.round(progress * 100)}%` }} />
              </div>
            )}

            {error && <p role="alert" className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>}
          </section>
        </>
      )}
    </div>
  );
}
