-- Analytics event integrity.
--
-- GENERATED by scripts/gen-event-constraint.mjs from the EventName union in
-- src/lib/telemetry.ts. Do not edit by hand — regenerate.
--
-- WHY THIS EXISTS
--
-- Measured on production 2026-09-08:
--
--   analytics_events CHECK constraints : NONE
--   INSERT policy                      : roles={anon,authenticated} WITH CHECK (true)
--
-- So the public anon key could insert unlimited rows with any name, any
-- business_id and any user_id. While the table was only a log that nothing
-- acted on, that was low-stakes. It stops being low-stakes the moment anything
-- ranks businesses on engagement, detects demand from searches, or targets
-- acquisition from it — all of which have obvious commercial motive to forge.
--
-- Two holes are closed here, and only two, because these are the two SQL can
-- close honestly:
--
--   1. An event name outside the declared vocabulary.
--   2. An event attributed to a user who did not send it.
--
-- Rate limiting is deliberately NOT attempted in a trigger; a per-insert COUNT
-- over a growing table is a self-inflicted performance problem. That belongs
-- at the edge.

-- ---------------------------------------------------------------------------
-- 1. Only declared events.
-- ---------------------------------------------------------------------------
-- NOT VALID first: the constraint applies to every new row immediately, while
-- the existing 43,596 rows are checked separately below. That ordering means a
-- slow validation can never hold a write lock on the insert path.
alter table public.analytics_events
  drop constraint if exists analytics_events_name_known;

alter table public.analytics_events
  add constraint analytics_events_name_known check (name in (
    'signup',
    'signin',
    'business_created',
    'business_viewed',
    'business_contact_clicked',
    'directions_opened',
    'business_kept',
    'profile_request_started',
    'profile_requested',
    'business_nominated',
    'create_order_requested',
    'create_order_accepted',
    'search_performed',
    'search_result_clicked',
    'enquiry_sent',
    'booking_started',
    'studio_export',
    'template_picked',
    'plan_viewed',
    'campaign_view',
    'campaign_cta_click',
    'campaign_share',
    'campaign_referral_joined',
    'client_error'
  )) not valid;

alter table public.analytics_events
  validate constraint analytics_events_name_known;

-- ---------------------------------------------------------------------------
-- 2. Props stay small.
-- ---------------------------------------------------------------------------
-- sanitizeProps already caps this client-side (12 keys, 120 chars each). This
-- is the same limit expressed where it cannot be bypassed by not using the
-- client. Generous enough that no honest event is near it.
alter table public.analytics_events
  drop constraint if exists analytics_events_props_small;

alter table public.analytics_events
  add constraint analytics_events_props_small
  check (props is null or pg_column_size(props) < 4096) not valid;

alter table public.analytics_events
  validate constraint analytics_events_props_small;

-- ---------------------------------------------------------------------------
-- 3. An event may only be attributed to the sender.
-- ---------------------------------------------------------------------------
-- The old policy was WITH CHECK (true), so an anonymous caller could write
-- events onto any account. Anonymous events stay possible — user_id NULL is
-- how the whole public directory is measured — but claiming to be somebody is
-- not.
drop policy if exists analytics_insert on public.analytics_events;

create policy analytics_insert on public.analytics_events
  for insert to anon, authenticated
  with check (user_id is null or user_id = auth.uid());

comment on constraint analytics_events_name_known on public.analytics_events is
  'Generated from the EventName union in src/lib/telemetry.ts by scripts/gen-event-constraint.mjs. Regenerate rather than editing.';
