-- ═══════════════════════════════════════════════════════════════════════
-- NOWOPEN AFRICA — EVERY PENDING MIGRATION, IN ONE PASTE
--
-- Generated 2026-09-08. Paste the whole file into the Supabase SQL editor and
-- run it once. Verification queries follow the COMMIT.
--
-- ⛔ DO NOT RUN `supabase db push`
--
--   The ledger records 20 of the 110 migration files on disk, so push would
--   replay 86 already-applied migrations. Three of those write rows, and one
--   would seed invented creative services into `media_services` — a table
--   that is deliberately empty and whose empty state the Create page shows
--   honestly. `npm run check:drift` reports all of this.
--
-- WHAT THIS CHANGES FOR VISITORS: nothing, immediately.
--
--   Every column is optional to the application, every default preserves
--   current behaviour, and no row is reclassified. The search function is
--   created but not yet called. The evidence table is created EMPTY — no
--   provenance is backfilled, because inventing provenance is the one thing
--   an evidence model must never do.
--
-- WHAT IS NOT HERE
--
--   20260907190000_users_column_guard_policy.sql. It replaces a live RLS
--   policy on the users table; a wrong WITH CHECK locks every user out of
--   their own profile, and there is no staging database to rehearse on. Apply
--   that one alone, in a transaction you watch. The escalation it defends
--   against is not currently open.
--
-- SAFETY
--
--   One transaction. If any statement fails, nothing is applied.
--   Every statement is guarded (IF NOT EXISTS / OR REPLACE / DROP … IF
--   EXISTS), so running this twice is a no-op rather than an error.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- 20260908120000_analytics_event_integrity.sql
-- Event integrity — close the anon forgery hole. FIRST, so the junk purge lands on a table that cannot be refilled.
-- ─────────────────────────────────────────────────────────────────────

-- Analytics event integrity.
--
-- GENERATED by scripts/gen-event-constraint.mjs from the EventName union in
-- src/lib/telemetry.ts. Do not edit by hand — regenerate.
--
-- WHY THIS EXISTS
--
-- Measured on production 2026-09-08:
--
--   analytics_events CHECK constraints : NONE
--   INSERT policy                      : roles={anon,authenticated} WITH CHECK (true)
--
-- So the public anon key could insert unlimited rows with any name, any
-- business_id and any user_id. While the table was only a log that nothing
-- acted on, that was low-stakes. It stops being low-stakes the moment anything
-- ranks businesses on engagement, detects demand from searches, or targets
-- acquisition from it — all of which have obvious commercial motive to forge.
--
-- Two holes are closed here, and only two, because these are the two SQL can
-- close honestly:
--
--   1. An event name outside the declared vocabulary.
--   2. An event attributed to a user who did not send it.
--
-- Rate limiting is deliberately NOT attempted in a trigger; a per-insert COUNT
-- over a growing table is a self-inflicted performance problem. That belongs
-- at the edge.

-- ---------------------------------------------------------------------------
-- 1. Only declared events.
-- ---------------------------------------------------------------------------
-- NOT VALID first: the constraint applies to every new row immediately, while
-- the existing 43,596 rows are checked separately below. That ordering means a
-- slow validation can never hold a write lock on the insert path.
alter table public.analytics_events
  drop constraint if exists analytics_events_name_known;

alter table public.analytics_events
  add constraint analytics_events_name_known check (name in (
    'signup',
    'signin',
    'business_created',
    'business_viewed',
    'business_contact_clicked',
    'directions_opened',
    'business_kept',
    'profile_request_started',
    'profile_requested',
    'business_nominated',
    'create_order_requested',
    'create_order_accepted',
    'search_performed',
    'search_result_clicked',
    'enquiry_sent',
    'booking_started',
    'studio_export',
    'template_picked',
    'plan_viewed',
    'campaign_view',
    'campaign_cta_click',
    'campaign_share',
    'campaign_referral_joined',
    'client_error'
  )) not valid;

alter table public.analytics_events
  validate constraint analytics_events_name_known;

-- ---------------------------------------------------------------------------
-- 2. Props stay small.
-- ---------------------------------------------------------------------------
-- sanitizeProps already caps this client-side (12 keys, 120 chars each). This
-- is the same limit expressed where it cannot be bypassed by not using the
-- client. Generous enough that no honest event is near it.
alter table public.analytics_events
  drop constraint if exists analytics_events_props_small;

alter table public.analytics_events
  add constraint analytics_events_props_small
  check (props is null or pg_column_size(props) < 4096) not valid;

alter table public.analytics_events
  validate constraint analytics_events_props_small;

-- ---------------------------------------------------------------------------
-- 3. An event may only be attributed to the sender.
-- ---------------------------------------------------------------------------
-- The old policy was WITH CHECK (true), so an anonymous caller could write
-- events onto any account. Anonymous events stay possible — user_id NULL is
-- how the whole public directory is measured — but claiming to be somebody is
-- not.
drop policy if exists analytics_insert on public.analytics_events;

create policy analytics_insert on public.analytics_events
  for insert to anon, authenticated
  with check (user_id is null or user_id = auth.uid());

comment on constraint analytics_events_name_known on public.analytics_events is
  'Generated from the EventName union in src/lib/telemetry.ts by scripts/gen-event-constraint.mjs. Regenerate rather than editing.';

-- ─────────────────────────────────────────────────────────────────────
-- 20260907180000_open_status_expiry_and_holidays.sql
-- Open Now — manual overrides expire; a public holiday closes a business that has not said it trades through one.
-- ─────────────────────────────────────────────────────────────────────

-- Open Now: make a manual override expire, and let a business declare that it
-- trades through public holidays.
--
-- WHY
--
-- 1. `open_status` short-circuited the schedule with no expiry of any kind. An
--    owner who marked themselves closed once — for one afternoon — appeared
--    closed forever, with no signal to them or to a customer. It is the single
--    most damaging state a listing can be stuck in: permanently telling
--    customers not to come. Nothing in the app writes the column today, so the
--    bug is latent rather than active, and this closes it before the toggle
--    that would trigger it ever ships.
--
-- 2. The status engine had no concept of a public holiday. Nigeria has six
--    fixed public holidays plus Easter and two lunar Eids, and on every one of
--    them the platform's headline promise was confidently wrong. A business
--    that genuinely trades on holidays now has a way to say so.
--
-- SAFETY. Both columns are additive and nullable, and the application already
-- treats them as optional — `overrideStillApplies` deliberately keeps honouring
-- an override that has no timestamp, precisely so that applying this migration
-- (or not applying it) cannot change what a live listing says.

ALTER TABLE public.businesses
  ADD COLUMN IF NOT EXISTS open_status_set_at timestamptz,
  ADD COLUMN IF NOT EXISTS opens_on_holidays boolean NOT NULL DEFAULT false;

ALTER TABLE public.business_locations
  ADD COLUMN IF NOT EXISTS open_status_set_at timestamptz,
  ADD COLUMN IF NOT EXISTS opens_on_holidays boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.businesses.open_status_set_at IS
  'When open_status was last set. An override applies only on the local day it was set (see overrideStillApplies in src/lib/openingHours.ts). NULL means "no timestamp recorded", which the app still honours so that pre-existing overrides are not silently reopened.';

COMMENT ON COLUMN public.businesses.opens_on_holidays IS
  'The business trades on public holidays. Default false: a holiday closes a listing unless the owner has said otherwise, because a customer wrongly told "open" travels to a locked door and blames the platform.';

-- Keep the timestamp honest without trusting the client to send it.
CREATE OR REPLACE FUNCTION public.stamp_open_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF NEW.open_status IS DISTINCT FROM OLD.open_status THEN
    NEW.open_status_set_at := now();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS stamp_open_status_change ON public.businesses;
CREATE TRIGGER stamp_open_status_change
  BEFORE UPDATE ON public.businesses
  FOR EACH ROW EXECUTE FUNCTION public.stamp_open_status_change();

DROP TRIGGER IF EXISTS stamp_open_status_change ON public.business_locations;
CREATE TRIGGER stamp_open_status_change
  BEFORE UPDATE ON public.business_locations
  FOR EACH ROW EXECUTE FUNCTION public.stamp_open_status_change();

-- Announced public holidays.
--
-- Fixed-date holidays and Easter are computed in application code, because
-- they are determinable without guessing. This table is for the ones that are
-- NOT: Eid al-Fitr and Eid al-Adha follow lunar observation and are announced
-- rather than calculated, and a guessed Eid date would be fabricated data of
-- exactly the kind this platform has spent effort removing. It is seeded
-- empty, on purpose, and filled by an admin who knows the announced date.
CREATE TABLE IF NOT EXISTS public.public_holidays (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  country text NOT NULL DEFAULT 'NG',
  holiday_date date NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  UNIQUE (country, holiday_date, name)
);

CREATE INDEX IF NOT EXISTS idx_public_holidays_lookup
  ON public.public_holidays (country, holiday_date);

ALTER TABLE public.public_holidays ENABLE ROW LEVEL SECURITY;

-- Readable by anyone: the public status engine needs it, and a holiday
-- calendar is not sensitive.
DROP POLICY IF EXISTS "Public holidays are readable" ON public.public_holidays;
CREATE POLICY "Public holidays are readable"
  ON public.public_holidays FOR SELECT USING (true);

-- Writable only by staff. A holiday closes every listing in the country for a
-- day, which makes this one of the highest-leverage tables on the platform.
DROP POLICY IF EXISTS "Staff manage public holidays" ON public.public_holidays;
CREATE POLICY "Staff manage public holidays"
  ON public.public_holidays FOR ALL
  USING (public.is_staff())
  WITH CHECK (public.is_staff());

-- ─────────────────────────────────────────────────────────────────────
-- 20260907181000_advert_inventory_provenance.sql
-- Advertising — an accountable rights holder, a currency, availability dates. Marks NOTHING as verified.
-- ─────────────────────────────────────────────────────────────────────

-- Advertising inventory: record where a placement came from and who may sell it.
--
-- THE PROBLEM THIS SOLVES
--
-- `advertisements` holds 97 rows. 89 are `status = 'active'`. `user_id` is NULL
-- on every single one. The titles name specific, real, third-party properties:
--
--   "2 Double-Sided Freestanding Screens, The Palms, Lekki, Lagos"
--   "16 Digital Screens, Railway Ticketing & Waiting Area, Lagos"
--   "LED Portrait Billboard, 5th Roundabout Lekki FTF Ajah, Lagos"
--   "2-Sided Unipole Billboard, Aba Road, Port Harcourt"
--
-- ...each with a day rate. So the platform was publicly presenting 89 bookable
-- advertising placements at named real-world sites, owned by nobody in the
-- data, and submitting all 97 to Google for indexing.
--
-- Whether NowOpen holds the rights to broker these cannot be determined from
-- the database, and it MUST NOT be guessed. This migration therefore does
-- three things and deliberately not a fourth:
--
--   1. It gives the table somewhere to record provenance, which it had no way
--      to express — that absence is the actual defect.
--   2. It defaults every existing row to `unverified_import`, which is the only
--      honest description of a row with no owner and no rights record.
--   3. It leaves `status` untouched. Silently flipping 89 rows would destroy
--      information about the founder's intent, and these may well be a
--      legitimate rate card.
--   4. It does NOT mark anything verified. No row gains `rights_verified_at`
--      here. Verification is a human act with a counterparty, and fabricating
--      it in SQL would be precisely the invented-data problem this platform has
--      spent real effort removing.
--
-- The public sitemap already stopped requesting indexation for any placement
-- without an accountable owner (see api/sitemap.xml.ts). Nothing was deleted.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'advert_provenance') THEN
    CREATE TYPE public.advert_provenance AS ENUM (
      -- The owner of the site listed it themselves and holds the rights.
      'owner_submitted',
      -- A media owner or broker supplied a rate card under an agreement.
      'partner_rate_card',
      -- NowOpen owns or directly controls the placement.
      'platform_owned',
      -- Present in the data with no established provenance. The default, and
      -- the honest description of all 97 existing rows.
      'unverified_import'
    );
  END IF;
END $$;

ALTER TABLE public.advertisements
  ADD COLUMN IF NOT EXISTS provenance public.advert_provenance
    NOT NULL DEFAULT 'unverified_import',
  -- Who NowOpen believes may sell this placement. Free text on purpose: a
  -- structured party table is premature while the count is 97 and the rights
  -- question is unanswered.
  ADD COLUMN IF NOT EXISTS rights_holder text,
  -- Set ONLY by a human who has seen an agreement. Never defaulted, never
  -- backfilled.
  ADD COLUMN IF NOT EXISTS rights_verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS rights_verified_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rights_note text,
  -- A rate with no currency is a 1000× mispricing waiting to happen: `14`
  -- could be ₦14, $14 or ₦14,000.
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'NGN',
  -- Inventory that is no longer available should stop being offered without
  -- anybody having to remember.
  ADD COLUMN IF NOT EXISTS available_from date,
  ADD COLUMN IF NOT EXISTS available_to date;

COMMENT ON COLUMN public.advertisements.provenance IS
  'Where this placement came from. Defaults to unverified_import: a row with no owner and no rights record is not verified inventory, whatever its status says.';

COMMENT ON COLUMN public.advertisements.rights_verified_at IS
  'Set only by a human who has seen an agreement authorising NowOpen to sell this placement. Never defaulted and never backfilled — verification cannot be manufactured in SQL.';

COMMENT ON COLUMN public.advertisements.currency IS
  'ISO-4217 for price_per_day. Defaults to NGN, the platform''s working currency.';

CREATE INDEX IF NOT EXISTS idx_advertisements_sellable
  ON public.advertisements (provenance, status)
  WHERE rights_verified_at IS NOT NULL;

/*
 * One definition of "may we offer this", so every surface agrees.
 *
 * A placement is sellable when somebody is accountable for it: either a real
 * owner listed it, or a human recorded verified rights. `status = 'active'` is
 * explicitly NOT sufficient — 89 rows carry it today with neither.
 */
CREATE OR REPLACE FUNCTION public.advert_is_sellable(a public.advertisements)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    (a.user_id IS NOT NULL OR a.rights_verified_at IS NOT NULL)
    AND a.status = 'active'
    AND (a.available_from IS NULL OR a.available_from <= current_date)
    AND (a.available_to   IS NULL OR a.available_to   >= current_date);
$$;

COMMENT ON FUNCTION public.advert_is_sellable IS
  'Whether a placement may be publicly offered. Requires an accountable party — an owner, or human-verified rights — not merely status = active.';

-- ─────────────────────────────────────────────────────────────────────
-- 20260907182000_business_search_index.sql
-- Search — generated tsvector, GIN + trigram, paged search_businesses(). No behaviour change until the directory is wired to it.
-- ─────────────────────────────────────────────────────────────────────

-- Directory search: give Postgres something to search with.
--
-- THE PROBLEM
--
-- `src/pages/Businesses.tsx` runs `select('*')` with `.eq('is_listable', true)`
-- and no `.limit()` or `.range()`, then filters by category, location, text and
-- open-status entirely in the browser. The live index list on `businesses`
-- contains only btree indexes, so there is nothing a substring search can use.
--
-- At two listings this is invisible. The failure modes as supply arrives:
--
--   ~1,000    a multi-megabyte response, re-scanned in the browser on every
--             keystroke, paid for out of a Nigerian mobile data bundle
--   ~10,000   unusable on the connections this audience actually has
--   beyond    PostgREST's row cap truncates the response SILENTLY. Search then
--             reports "no results" for businesses that demonstrably exist —
--             a correctness failure wearing the costume of an empty state,
--             and the worst possible bug for a directory
--
-- This migration builds the index side. It is additive and changes no
-- behaviour on its own: the page keeps working exactly as it does today, and
-- the query can be moved server-side against a real index rather than against
-- a sequential scan.
--
-- WHY pg_trgm AS WELL AS tsvector. Full-text handles whole words; it does not
-- help someone typing "barbin salon" or "resturant". Measured: the directory
-- currently returns nothing for either. Trigram similarity is what makes a
-- misspelling still find the shop, and in this market — where business names
-- are typed on phone keyboards, often in a second language — that is not a
-- nicety.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Full-text over the fields a customer actually searches.
--
-- 'simple' rather than 'english': Nigerian business names are full of words no
-- English stemmer should touch — "Buka", "Suya", "Aso-Oke", "Okrika", "Mama
-- Put", "Keke". Stemming them produces worse matches, not better ones.
ALTER TABLE public.businesses
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector(
      'simple',
      coalesce(name, '') || ' ' ||
      coalesce(category, '') || ' ' ||
      coalesce(location, '') || ' ' ||
      coalesce(description, '')
    )
  ) STORED;

CREATE INDEX IF NOT EXISTS idx_businesses_search_vector
  ON public.businesses USING gin (search_vector);

-- Typo tolerance on the two fields worth being forgiving about.
CREATE INDEX IF NOT EXISTS idx_businesses_name_trgm
  ON public.businesses USING gin (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_businesses_location_trgm
  ON public.businesses USING gin (location gin_trgm_ops);

COMMENT ON COLUMN public.businesses.search_vector IS
  'Generated full-text vector over name, category, location and description. Configuration is ''simple'' on purpose: an English stemmer mangles Nigerian business vocabulary (Buka, Suya, Aso-Oke, Okrika).';

/*
 * One paged, ranked, server-side search.
 *
 * Replaces "fetch every listable row and filter in the browser". Ranking is
 * deliberately explicit rather than clever:
 *
 *   1. a full-text match on the query, weighted by rank
 *   2. then trigram similarity, so a misspelling still lands
 *   3. then the directory's existing order — listing_score, then recency —
 *      which is what already decides what a visitor sees first
 *
 * Keyset pagination on (listing_score, created_at, id) rather than OFFSET:
 * OFFSET re-scans everything it skips, so deep pages get slower and slower,
 * and a row inserted mid-scroll shifts every subsequent page.
 */
CREATE OR REPLACE FUNCTION public.search_businesses(
  q            text    DEFAULT NULL,
  in_category  text    DEFAULT NULL,
  in_place     text    DEFAULT NULL,
  page_size    integer DEFAULT 24,
  after_score  integer DEFAULT NULL,
  after_created timestamptz DEFAULT NULL,
  after_id     uuid    DEFAULT NULL
)
RETURNS SETOF public.businesses
LANGUAGE sql
STABLE
SECURITY INVOKER            -- RLS stays the visibility authority, as everywhere else
SET search_path TO 'public'
AS $$
  SELECT b.*
  FROM public.businesses b
  WHERE b.is_listable
    AND (in_category IS NULL OR in_category = ''
         OR b.category = in_category
         OR in_category = ANY (coalesce(b.secondary_categories, '{}')))
    AND (in_place IS NULL OR in_place = ''
         OR b.location ILIKE '%' || in_place || '%')
    AND (
      q IS NULL OR q = ''
      OR b.search_vector @@ plainto_tsquery('simple', q)
      OR b.name     ILIKE '%' || q || '%'
      OR b.location ILIKE '%' || q || '%'
      /*
       * TYPO TOLERANCE — word_similarity, not similarity.
       *
       * This shipped as `similarity(b.name, q) > 0.25` and caught nothing.
       * Measured on production the day it was applied:
       *
       *   similarity('Eko Hotels & Suites', 'hotle')       = 0.143   MISS
       *   word_similarity('hotle', 'Eko Hotels & Suites')  = 0.500   hit
       *
       * `similarity` compares whole strings, so a short query against a long
       * business name is dragged down by every trigram in the name it does not
       * share. `word_similarity` finds the best-matching run of words inside
       * the target, which is what a search box actually needs.
       *
       * And it has to cover CATEGORY and LOCATION, not only the name: in this
       * directory "restaurant" and "fashion" appear in 12 and 32 category
       * values and in zero names, so a customer typing "resturant" found
       * nothing while twelve restaurants sat in the table.
       *
       * Threshold 0.4, chosen against real data rather than picked: it catches
       * hotle (16), resturant (12), fashon (32), insurnce (14) and rejects
       * zzzqqq, xkcdqq and a single character.
       *
       * AT SCALE this should move to the `<%` operator so the trigram GIN
       * index is used; the operator's threshold is a GUC (0.6 by default),
       * which is too strict for the cases above and awkward to set inside a
       * STABLE function. At a few hundred rows the sequential scan is free,
       * and correctness now beats an index later.
       */
      OR word_similarity(q, b.name) > 0.4
      OR word_similarity(q, coalesce(b.category, '')) > 0.4
      OR word_similarity(q, coalesce(b.location, '')) > 0.4
    )
    -- Keyset cursor: strictly "after" the last row of the previous page.
    AND (
      after_id IS NULL
      OR (coalesce(b.listing_score, 0), b.created_at, b.id)
         < (coalesce(after_score, 0), after_created, after_id)
    )
  ORDER BY
    CASE WHEN q IS NULL OR q = '' THEN 0
         ELSE ts_rank(b.search_vector, plainto_tsquery('simple', q)) END DESC,
    coalesce(b.listing_score, 0) DESC,
    b.created_at DESC,
    b.id DESC
  LIMIT least(greatest(page_size, 1), 100);
$$;

COMMENT ON FUNCTION public.search_businesses IS
  'Paged, ranked directory search. SECURITY INVOKER so RLS remains the single visibility authority. Keyset pagination on (listing_score, created_at, id) — OFFSET degrades on deep pages and shifts under concurrent inserts.';

-- ─────────────────────────────────────────────────────────────────────
-- 20260908140000_business_evidence.sql
-- AutoAcquire evidence — field-level provenance, plus the claim/verification values §12 was missing and a data_confidence column beside data_status.
-- ─────────────────────────────────────────────────────────────────────

-- AutoAcquire §8 — field-level provenance, and the status values §12 is missing.
--
-- WHY THIS IS THE MOST IMPORTANT MIGRATION IN THE ACQUISITION ENGINE
--
-- Today provenance is per RECORD: `businesses.source_name`, `source_url`,
-- `source_license`. That answers "where did this row come from" and cannot
-- answer the question that actually matters:
--
--     "Why do we believe this phone number?"
--
-- Without a per-field answer there is no way to distinguish a phone read from
-- a business's own website from one a model inferred from a name — and §10
-- forbids ever presenting the second as the first. An acquisition engine that
-- cannot separate them will eventually publish a guess as a fact, and nobody
-- will be able to tell which facts are guesses.
--
-- SAFETY
--
-- Entirely additive. One new table, two new CHECK values on existing columns,
-- one new column. No existing row changes meaning, and nothing is backfilled:
-- a business with no evidence rows is a business we have not yet recorded
-- evidence for, which is the truth about every row in the table today.

-- ═══════════════════════════════════════════════════════════════════════
-- 1. THE EVIDENCE TABLE
-- ═══════════════════════════════════════════════════════════════════════

create table if not exists public.business_evidence (
  id            uuid primary key default gen_random_uuid(),
  business_id   uuid not null references public.businesses(id) on delete cascade,

  -- Which field this is evidence for. Free text rather than an enum: the
  -- field list belongs to the application (UPDATABLE_FIELDS in
  -- src/lib/imports/matchExisting.ts), and a database enum would need a
  -- migration every time a field is added.
  field_name    text not null,

  -- The value as observed. Kept even when the business row later changes, so
  -- a correction can be compared against what the source actually said.
  field_value   text,

  source_id     text references public.radar_sources(key) on delete set null,
  source_url    text,
  source_type   text,

  -- 0-100. NOT a probability — a deterministic score from the extraction
  -- method and the source tier (§11), so two operators reading the same
  -- evidence reach the same number.
  confidence    integer not null default 0 check (confidence between 0 and 100),

  observed_at   timestamptz not null default now(),

  /*
   * HOW the value was obtained. This is the field that makes §10 enforceable:
   * `ai_inferred` can never be displayed as confirmed, and the distinction
   * has to be recorded at the moment of extraction because it cannot be
   * recovered afterwards.
   */
  extraction_method text not null check (extraction_method in (
    'structured_data',   -- schema.org / JSON-LD on the page
    'dom_extraction',    -- parsed from markup
    'regex',             -- pattern matched from text
    'api',               -- an authorised provider returned it as a field
    'owner_submitted',   -- the business told us
    'admin_entered',     -- a person on our side typed it
    'csv_import',        -- an admin's file
    'ai_extracted',      -- a model read the page and returned this field
    'ai_inferred'        -- a model produced it WITHOUT direct page support
  )),

  /*
   * §11's source hierarchy, as data. `ai_inferred` is deliberately its own
   * lowest tier and must never be rendered as "verified".
   */
  status text not null check (status in (
    'owner_confirmed',
    'admin_verified',
    'source_confirmed',
    'multiple_sources',
    'single_source',
    'ai_inferred',
    'disputed',
    'superseded'
  )),

  -- Hash of the raw evidence (the fetched bytes, or the CSV cell), so the same
  -- observation is not recorded twice and a claim can be traced to what was
  -- actually seen.
  evidence_hash text,

  created_at timestamptz not null default now()
);

-- One observation per (business, field, source, hash). A re-run of the same
-- extraction updates rather than accumulating identical rows.
create unique index if not exists business_evidence_unique_observation
  on public.business_evidence (business_id, field_name, coalesce(source_id, ''), coalesce(evidence_hash, ''));

-- The read the profile page makes: every field's best evidence for one business.
create index if not exists business_evidence_business_field_idx
  on public.business_evidence (business_id, field_name, confidence desc);

-- The read §31's learning loop makes: how accurate has each source been?
create index if not exists business_evidence_source_idx
  on public.business_evidence (source_id, status, observed_at desc);

comment on table public.business_evidence is
  'Field-level provenance. Answers "why do we believe this?" per field, which record-level source_url cannot. extraction_method ai_inferred must never be displayed as confirmed (AutoAcquire §10).';

-- ═══════════════════════════════════════════════════════════════════════
-- 2. RLS — evidence is readable with the business, writable by staff only
-- ═══════════════════════════════════════════════════════════════════════

alter table public.business_evidence enable row level security;

drop policy if exists business_evidence_public_read on public.business_evidence;
drop policy if exists business_evidence_staff_write on public.business_evidence;

/*
 * Public READ, and deliberately so: "why do we believe this" is a claim
 * NowOpen makes in public, and a provenance trail nobody can inspect is not a
 * provenance trail. Scoped to listable businesses so it cannot be used to
 * enumerate hidden rows.
 */
create policy business_evidence_public_read on public.business_evidence
  for select to anon, authenticated
  using (exists (
    select 1 from public.businesses b
     where b.id = business_evidence.business_id
       and b.is_listable
  ));

-- Only staff write evidence. A claimant correcting their own listing goes
-- through the correction queue, which records WHO said so — it does not get
-- to assert `owner_confirmed` about itself.
create policy business_evidence_staff_write on public.business_evidence
  for all to authenticated
  using (public.is_staff())
  with check (public.is_staff());

-- ═══════════════════════════════════════════════════════════════════════
-- 3. THE §12 STATUS VALUES THAT ARE MISSING
-- ═══════════════════════════════════════════════════════════════════════

/*
 * claim_rejected / claim_suspended.
 *
 * Without them a rejected claim returns the business to plain `unclaimed`, so
 * the platform forgets it was ever contested and a bad-faith claimant simply
 * tries again with nothing on the record. `claim_suspended` is the state an
 * ownership dispute or takedown actually needs.
 */
alter table public.businesses
  drop constraint if exists businesses_claim_status_check;

alter table public.businesses
  add constraint businesses_claim_status_check check (claim_status in (
    'unclaimed', 'claim_pending', 'claimed', 'claim_rejected', 'claim_suspended'
  ));

/*
 * verification_status: `expired`.
 *
 * `last_verified_at` exists and nothing ages it out, so a 2026 verification
 * would still read "verified" in 2029. Adding the value does not expire
 * anything by itself — that is a policy decision with a duration attached —
 * but without the value there is nowhere for the decision to land.
 */
alter table public.businesses
  drop constraint if exists businesses_verification_status_check;

alter table public.businesses
  add constraint businesses_verification_status_check check (verification_status in (
    'unverified', 'pending', 'verified', 'expired', 'rejected'
  ));

-- ═══════════════════════════════════════════════════════════════════════
-- 4. DATA CONFIDENCE — a second axis, not a rename
-- ═══════════════════════════════════════════════════════════════════════

/*
 * `data_status` describes ORIGIN (synthetic_unverified, imported_authorized,
 * submitted, user_created, admin_curated). §12's data confidence describes
 * CONFIRMATION. They are different questions and a record can be
 * `imported_authorized` while only `partially_confirmed`.
 *
 * data_status is NOT renamed. It feeds the generated `is_listable` column and
 * the sitemap gate, so changing its vocabulary would silently change who is
 * visible on the internet.
 *
 * Defaults to `unconfirmed`, which is the honest starting point for all
 * 2 existing rows and every row an importer will create.
 */
alter table public.businesses
  add column if not exists data_confidence text not null default 'unconfirmed';

alter table public.businesses
  drop constraint if exists businesses_data_confidence_check;

alter table public.businesses
  add constraint businesses_data_confidence_check check (data_confidence in (
    'unconfirmed',
    'source_confirmed',
    'partially_confirmed',
    'owner_confirmed',
    'admin_verified'
  ));

comment on column public.businesses.data_confidence is
  'How well the CONTENT is confirmed. Separate from data_status, which describes where the record came from. Never rename data_status — it feeds the generated is_listable column and the sitemap gate.';

-- ═══════════════════════════════════════════════════════════════════════
-- VERIFY
-- ═══════════════════════════════════════════════════════════════════════
-- Run these after applying. Each should return what the comment says.

-- 1. The table exists, is empty, and RLS is on.
--    Empty is correct: no evidence has been recorded for any business yet,
--    and backfilling it would be inventing provenance.
-- select relrowsecurity from pg_class where relname = 'business_evidence';
-- select count(*) from business_evidence;                    -- expect 0

-- 2. The new status values are accepted and nothing was reclassified.
-- select claim_status, verification_status, data_confidence, count(*)
--   from businesses group by 1,2,3;                          -- expect all unconfirmed

-- 3. is_listable is unchanged — this migration must not alter visibility.
-- select count(*) from businesses where is_listable;         -- expect 2


COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- VERIFY — run after the COMMIT.
-- ═══════════════════════════════════════════════════════════════════════

-- 1. Event forgery is closed: a name outside the vocabulary is refused, and
--    an event cannot be attributed to another account.
select conname from pg_constraint
 where conrelid = 'public.analytics_events'::regclass and contype = 'c';
-- expect analytics_events_name_known and analytics_events_props_small

select with_check from pg_policies
 where schemaname = 'public' and tablename = 'analytics_events' and cmd = 'INSERT';
-- expect (user_id IS NULL) OR (user_id = auth.uid())

-- 2. Open Now columns exist on both tables.
select table_name, column_name from information_schema.columns
 where table_schema = 'public'
   and column_name in ('open_status_set_at', 'opens_on_holidays')
 order by table_name, column_name;

-- 3. Advertising gained accountability columns and NOTHING claims to be
--    rights-verified. A row here would mean something asserted it in SQL,
--    which is exactly the invented data this platform has removed.
select count(*) filter (where provenance is not null)         as have_provenance,
       count(*) filter (where rights_verified_at is not null) as claimed_verified
  from advertisements;
-- expect claimed_verified = 0

-- 4. The search function exists and answers.
select count(*) from search_businesses('lagos', null, null, 10, 0);

-- 5. The evidence table exists, is EMPTY, and RLS is on.
--    Empty is the correct result. No evidence has been recorded for any
--    business, and backfilling it would be inventing provenance.
select relrowsecurity from pg_class where relname = 'business_evidence';
select count(*) from business_evidence;                    -- expect 0

-- 6. Nothing was reclassified, and visibility did not move.
select claim_status, verification_status, data_confidence, count(*)
  from businesses group by 1,2,3;
select count(*) from businesses where is_listable;         -- expect 2

-- ═══════════════════════════════════════════════════════════════════════
-- THEN
--
--   a) `npm run check:drift` — should report no missing tables or columns.
--      The ledger warning about `db push` stays, and is still correct.
--
--   b) Purge the junk telemetry. 43,354 of 43,596 rows are `signin` from the
--      emitter bug fixed on 2026-09-07 — 677 per session, 99.4% of the table.
--      Scoped so genuine sign-ins survive:
--
--        delete from analytics_events
--         where name = 'signin' and created_at < '2026-09-07T18:00:00Z';
--
--      Check the count first:
--        select count(*) from analytics_events
--         where name = 'signin' and created_at < '2026-09-07T18:00:00Z';
--
--   c) Tell Claude that 20260907182000 is applied, and the directory can be
--      wired to search_businesses(). That was left undone deliberately —
--      building against a function that does not exist cannot be verified.
-- ═══════════════════════════════════════════════════════════════════════
